package queries

const GetQuantidadeTotalAlocacaoPedidoVendaLocalInspecao = `
SELECT SUM(QUANTIDADE_APROVAR) + SUM(QUANTIDADE_REPROVAR) AS QuantidadeTotalAlocada,
SUM(QUANTIDADE_APROVAR) AS QuantidadeAprovada,
SUM(QUANTIDADE_REPROVAR) AS QuantidadeReprovada
FROM QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB
WHERE
RECNO_INSPECAO_ENTRADA = @` + NamedRecnoInspecaoEntrada + "\n"

const GetAlocacaoPedidoVendaLocalInspecao = `
  SELECT DISTINCT
    QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.ID AS IdPedidoVenda,
    ESTOQUE_PEDIDO_VENDA.NUMPED AS NumeroPedido,
    ESTOQUE_PEDIDO_VENDA.NUMODF AS NumeroOdf,
    ESTOQUE_PEDIDO_VENDA.QTDE AS QuantidadeTotalPedido,
    QA_INSPECAO_ENTRADA_MAIN.QTD_LOTE AS QuantidadeLote,
    COALESCE(
        CASE 
            WHEN ESTOQUE_PEDIDO_VENDA.NUMPED = 'ESTOQUE' 
            THEN DadosEstoque.QtdePedido 
            ELSE DadosPedidoNormal.QtdePedido 
        END,
        ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE
    ) AS QuantidadeAlocadaLoteLocal,

    CASE 
        WHEN ESTOQUE_PEDIDO_VENDA.NUMPED = 'ESTOQUE' 
        THEN DadosEstoque.QtdeEntrada 
        ELSE DadosPedidoNormal.QtdeEntrada 
    END AS QuantidadeEntrada,

    CASE 
        WHEN ESTOQUE_PEDIDO_VENDA.NUMPED = 'ESTOQUE' 
        THEN DadosEstoque.QtdeEntrada 
        ELSE DadosPedidoNormal.QtdeEntrada 
    END - ISNULL(
        (
            SELECT
                SUM(HISREAL.QTRECEB)
            FROM
                QA_INSPECAO_ENTRADA_MOVIMENTACAO_HISTORICO
                INNER JOIN HISREAL ON HISREAL.R_E_C_N_O_ = QA_INSPECAO_ENTRADA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
                AND HISREAL.ODF = ESTOQUE_PEDIDO_VENDA.NUMODF
            WHERE
                QA_INSPECAO_ENTRADA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO IN (
                    SELECT R_E_C_N_O_
                    FROM QA_INSPECAO_ENTRADA AS QA_INSPECAO_ENTRADA_AUX
                    WHERE QA_INSPECAO_ENTRADA_AUX.RECNO_HISTLISE = QA_INSPECAO_ENTRADA_MAIN.RECNO_HISTLISE
                )
        ), 0
    ) AS QuantidadeRestanteInspecionar,
    ESTOQUE.DESCRI AS DescricaoProduto,
    LocalReprovado.DESCRICAO AS DescricaoLocalReprovado,
    LocalAprovado.DESCRICAO AS DescricaoLocalAprovado,
    LocalReprovado.CODIGO AS CodigoLocalReprovado,
    LocalAprovado.CODIGO AS CodigoLocalAprovado,
    QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.QUANTIDADE_APROVAR AS QuantidadeAprovada,
    QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.QUANTIDADE_REPROVAR AS QuantidadeReprovada
    FROM QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB
	INNER JOIN LOCAIS ON LOCAIS.LOCAL_CQ_ENTRADA = 'S'
	INNER JOIN ESTOQUE_PEDIDO_VENDA ON ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_ = QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.RECNO_ESTOQUE_PEDIDO_VENDA
	INNER JOIN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL ON ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_ = ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_PEDIDO_VENDA
	INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.R_E_C_N_O_ = ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_LOCAL
	INNER JOIN QA_INSPECAO_ENTRADA AS QA_INSPECAO_ENTRADA_MAIN ON QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.RECNO_INSPECAO_ENTRADA = QA_INSPECAO_ENTRADA_MAIN.R_E_C_N_O_
	INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = ESTOQUE_PEDIDO_VENDA.CODIGO
	LEFT JOIN QA_INSPECAO_ENTRADA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_ENTRADA_MAIN.R_E_C_N_O_ = QA_INSPECAO_ENTRADA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO
	LEFT JOIN PCP_NFENTRADA_PEDIDO ON PCP_NFENTRADA_PEDIDO.RECNO_HISTLISE = QA_INSPECAO_ENTRADA_MAIN.RECNO_HISTLISE
	AND PCP_NFENTRADA_PEDIDO.NUMPED = ESTOQUE_PEDIDO_VENDA.NUMPED AND PCP_NFENTRADA_PEDIDO.NUMODF = ESTOQUE_PEDIDO_VENDA.NUMODF
	LEFT JOIN LOCAIS LocalReprovado ON LocalReprovado.CODIGO = QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.CODIGO_LOCAL_REPROVAR
	AND LocalReprovado.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
	LEFT JOIN LOCAIS LocalAprovado ON LocalAprovado.CODIGO = QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.CODIGO_LOCAL_APROVAR
	AND LocalAprovado.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
	OUTER APPLY (
        SELECT
            SUM(QTDE_PEDIDO) AS QtdePedido,
            SUM(QTDE_ENTRADA) AS QtdeEntrada
        FROM PCP_NFENTRADA_PEDIDO
        WHERE
            PCP_NFENTRADA_PEDIDO.RECNO_HISTLISE = QA_INSPECAO_ENTRADA_MAIN.RECNO_HISTLISE
            AND PCP_NFENTRADA_PEDIDO.NUMPED = 'ESTOQUE'
    ) AS DadosEstoque
    OUTER APPLY (
        SELECT
            SUM(QTDE_PEDIDO) AS QtdePedido,
            SUM(QTDE_ENTRADA) AS QtdeEntrada
        FROM PCP_NFENTRADA_PEDIDO
        WHERE
            PCP_NFENTRADA_PEDIDO.RECNO_HISTLISE = QA_INSPECAO_ENTRADA_MAIN.RECNO_HISTLISE
            AND PCP_NFENTRADA_PEDIDO.NUMPED = ESTOQUE_PEDIDO_VENDA.NUMPED
            AND PCP_NFENTRADA_PEDIDO.NUMODF = ESTOQUE_PEDIDO_VENDA.NUMODF
    ) AS DadosPedidoNormal
	WHERE ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO AND 
	ESTOQUE_LOCAL.LOTE = @` + NamedLote + ` AND
	QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.RECNO_INSPECAO_ENTRADA = @` + NamedRecnoInspecaoEntrada + "\n"

const GetTotalCountAlocacaoPedidoVendaLocalInspecao = `
  SELECT COUNT(*)
	FROM QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB
	INNER JOIN LOCAIS ON LOCAIS.LOCAL_CQ_ENTRADA = 'S'
	INNER JOIN ESTOQUE_PEDIDO_VENDA ON ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_ = QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.RECNO_ESTOQUE_PEDIDO_VENDA
	INNER JOIN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL ON ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_ = ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_PEDIDO_VENDA
	INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.R_E_C_N_O_ = ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_LOCAL
	INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = ESTOQUE_PEDIDO_VENDA.CODIGO
	WHERE ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO AND 
	ESTOQUE_LOCAL.LOTE = @` + NamedLote + ` AND
	QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.RECNO_INSPECAO_ENTRADA = @` + NamedRecnoInspecaoEntrada + "\n"

const GetSeedValuesAlocacaoPedidoVendaLocalInspecao = `
SELECT DISTINCT
ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_ as RecnoEstoquePedidoVenda
FROM QA_INSPECAO_ENTRADA
JOIN HISTLISE ON HISTLISE.R_E_C_N_O_ = QA_INSPECAO_ENTRADA.RECNO_HISTLISE
JOIN PCP_NFENTRADA_PEDIDO ON PCP_NFENTRADA_PEDIDO.RECNO_HISTLISE = HISTLISE.R_E_C_N_O_
JOIN ESTOQUE_PEDIDO_VENDA ON ESTOQUE_PEDIDO_VENDA.CODIGO = PCP_NFENTRADA_PEDIDO.ITEM
AND ESTOQUE_PEDIDO_VENDA.NUMPED = PCP_NFENTRADA_PEDIDO.NUMPED AND ESTOQUE_PEDIDO_VENDA.EMPRESA_RECNO = PCP_NFENTRADA_PEDIDO.EMPRESA_RECNO
AND ESTOQUE_PEDIDO_VENDA.NUMODF = PCP_NFENTRADA_PEDIDO.NUMODF
WHERE
QA_INSPECAO_ENTRADA.R_E_C_N_O_ = @` + NamedRecnoInspecaoEntrada + `
AND ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_ NOT IN (
	SELECT
	RECNO_ESTOQUE_PEDIDO_VENDA
	FROM QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB 
	WHERE
	RECNO_INSPECAO_ENTRADA = @` + NamedRecnoInspecaoEntrada + `
)
`

const GetAlocacaoPedidoVendaLocalInspecaoPagination = `ORDER BY ESTOQUE_PEDIDO_VENDA.NUMPED OFFSET @Skip ROWS FETCH NEXT @PageSize ROWS ONLY`

const BuscarEstoqueLocalValoresPorProduto = `
SELECT
ESTOQUE_LOCAL.R_E_C_N_O_ AS Recno,
ESTOQUE_LOCAL.QTDE AS Quantidade,
ESTOQUE_LOCAL.PESO_BRUTO AS PesoBruto,
ESTOQUE_LOCAL.PESO_LIQUIDO AS PesoLiquido,
ESTOQUE_LOCAL.VALIDADE AS DataValidade,
ESTOQUE_LOCAL.DTFABRICACAO AS DataFabricacao,
ESTOQUE_EMPRESA.VALPAGO AS ValorPago
FROM ESTOQUE_LOCAL
	INNER JOIN ESTOQUE_EMPRESA
		ON ESTOQUE_EMPRESA.CODIGO = ESTOQUE_LOCAL.CODIGO
		AND ESTOQUE_EMPRESA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
WHERE ESTOQUE_LOCAL.CODIGO = @` + NamedProdutoCodigo + ` AND ESTOQUE_LOCAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND ESTOQUE_LOCAL.LOTE = @` + NamedLote + ` AND ESTOQUE_LOCAL.LOCAL = @` + NamedLocal

const BuscarPacotes = `
SELECT
NRO_PACOTE AS NumeroPacote,
QTDE_ESTOQUE AS Quantidade
FROM ESTOQUE_PACOTE
WHERE RECNO_ESTOQUE_LOCAL = @` + NamedLocal

const BuscarSeries = `
SELECT
ESTOQUE_SERIE_PRODUCAO.R_E_C_N_O_ AS RecnoSerie,
SERIE AS Serie
FROM ESTOQUE_SERIE_PRODUCAO
WHERE RECNO_ESTOQUE_LOCAL = @` + NamedLocal
