package queries

const GetPlanosNovaInspecao = "SELECT \n" +
	"       CASE \n" +
	"           WHEN PLANOINS.DESC1 IS NULL THEN EST.DESCRICAO \n" +
	"           ELSE PLANOINS.DESC1 \n" +
	"       END AS Descricao, \n" +
	"ISNULL(EST.QTD_INSP_MAXIMA, PLANOINS.MAIORVALOR) AS MaiorValorBase, \n" +
	"ISNULL(EST.QTD_INSP_MINIMA, PLANOINS.MENORVALOR) AS MenorValorBase, \n" +
	"PLANOINS.SEQUENCIA AS Sequencia, \n" +
	"PLANOINS.METODO AS Metodo, \n" +
	"PLANOINS.DESC1 AS Descricao, \n" +
	"PLANOINS.R_E_C_N_O_, \n" +
	"PLANOINS.Id AS Id \n" +
	"FROM PLANOINS \n" +
	"LEFT JOIN PLANOINSP_ESTOQUE EST ON PLANOINS.R_E_C_N_O_ = EST.RECNO_PLANOINSP \n" +
	"WHERE PLANOINS.PLANO = @" + NamedPlano + " AND ISNULL(EST.CODIGO, @" + NamedProdutoCodigo + ") = @" + NamedProdutoCodigo + " \n" +
	"ORDER BY CAST(PLANOINS.SEQUENCIA AS INT) \n"

const GetPlanosNovaInspecaoPagination = "OFFSET @" + NamedSkip + " ROWS \n" +
	"FETCH NEXT @" + NamedPageSize + " ROWS ONLY"

const GetCountPlanosNovaInspecao = "SELECT COUNT(*) \n" +
	"FROM PLANOINS \n" +
	"LEFT JOIN PLANOINSP_ESTOQUE EST ON PLANOINS.R_E_C_N_O_ = EST.RECNO_PLANOINSP \n" +
	"WHERE PLANOINS.PLANO = @" + NamedPlano + " AND ISNULL(EST.CODIGO, @" + NamedProdutoCodigo + ") = @" + NamedProdutoCodigo + " \n"

const GetInspecaoItensSelect = `
QA_ITEM_INSPECAO_ENTRADA.ID AS Id,
QA_ITEM_INSPECAO_ENTRADA.PLANO AS Plano,
QA_ITEM_INSPECAO_ENTRADA.DESCRICAO_PLANO AS Descricao,
QA_ITEM_INSPECAO_ENTRADA.METODO AS Metodo,
QA_ITEM_INSPECAO_ENTRADA.SEQUENCIA AS Sequencia,
QA_ITEM_INSPECAO_ENTRADA.RESULTADO AS Resultado,
QA_ITEM_INSPECAO_ENTRADA.MAIORVALOR AS MaiorValorInspecionado,
QA_ITEM_INSPECAO_ENTRADA.MENORVALOR AS MenorValorInspecionado, 
COALESCE(EST.QTD_INSP_MAXIMA, PLANOINS.MAIORVALOR) AS MaiorValorBase,
COALESCE(EST.QTD_INSP_MINIMA, PLANOINS.MENORVALOR) AS MenorValorBase,
QA_ITEM_INSPECAO_ENTRADA.CODINSPECAO AS CodigoInspecao,
QA_ITEM_INSPECAO_ENTRADA.OBSERVACAO AS Observacao
`

const GetInspecaoItensJoin = `
INNER JOIN PLANOINS ON QA_ITEM_INSPECAO_ENTRADA.SEQUENCIA = PLANOINS.SEQUENCIA AND QA_ITEM_INSPECAO_ENTRADA.PLANO = CAST(PLANOINS.PLANO AS INT)
LEFT JOIN PLANOINSP_ESTOQUE EST ON PLANOINS.R_E_C_N_O_ = EST.RECNO_PLANOINSP AND EST.CODIGO = @` + NamedProdutoCodigo + " \n"

const GetInspecaoEntradaCodigo = `
SELECT
QA_INSPECAO_ENTRADA.R_E_C_N_O_ AS Recno,
QA_INSPECAO_ENTRADA.COD_INSP AS CodigoInspecao,
QA_INSPECAO_ENTRADA.CODNOTA AS NotaFiscal,
QA_INSPECAO_ENTRADA.DATAINSP AS DataInspecao,
QA_INSPECAO_ENTRADA.INSPETOR AS Inspetor,
QA_INSPECAO_ENTRADA.QTD_LOTE AS QuantidadeLote,
QA_INSPECAO_ENTRADA.QTD_INSPECAO AS QuantidadeInspecao,
QA_INSPECAO_ENTRADA.RESULTADO AS Resultado,
QA_INSPECAO_ENTRADA.QTD_ACEITO AS QuantidadeAceita,
QA_INSPECAO_ENTRADA.QTD_APROVADO AS QuantidadeAprovada,
QA_INSPECAO_ENTRADA.QTD_REJEITADO AS QuantidadeReprovada,
QA_INSPECAO_ENTRADA.RECNO_RATEIO_LOTE AS RecnoRateioLote,
QA_INSPECAO_ENTRADA.LOTE AS Lote,
HISTLISE.ITEM AS CodigoProduto
	FROM QA_INSPECAO_ENTRADA
INNER JOIN HISTLISE 
	ON HISTLISE.NFISCAL = QA_INSPECAO_ENTRADA.CODNOTA
WHERE QA_INSPECAO_ENTRADA.COD_INSP =  @` + NamedCodigoInspecaoEntrada

const GetInspecaoEntradaCodigoJoin = `
SELECT
QA_INSPECAO_ENTRADA.R_E_C_N_O_ AS Recno,
QA_INSPECAO_ENTRADA.COD_INSP AS CodigoInspecao,
QA_INSPECAO_ENTRADA.CODNOTA AS NotaFiscal,
QA_INSPECAO_ENTRADA.RESULTADO AS Resultado,
QA_INSPECAO_ENTRADA.QTD_LOTE AS QuantidadeLote,
QA_INSPECAO_ENTRADA.LOTE AS Lote,
QA_INSPECAO_ENTRADA.RECNO_RATEIO_LOTE AS RecnoRateioLote,
QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.CODIGO_LOCAL_APROVAR AS CodigoLocalAprovado,
QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.QUANTIDADE_APROVAR AS QuantidadeAprovada,
QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.CODIGO_LOCAL_REPROVAR AS CodigoLocalReprovado,
QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.QUANTIDADE_REPROVAR AS QuantidadeReprovada,
ESTOQUE_PEDIDO_VENDA.NUMPED AS NumeroPedido,
ESTOQUE_PEDIDO_VENDA.NUMODF AS Odf
FROM QA_INSPECAO_ENTRADA
	INNER JOIN QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB
		ON QA_INSPECAO_ENTRADA.R_E_C_N_O_ = QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.RECNO_INSPECAO_ENTRADA
	INNER JOIN ESTOQUE_PEDIDO_VENDA
		ON QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB.RECNO_ESTOQUE_PEDIDO_VENDA = ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_
WHERE QA_INSPECAO_ENTRADA.COD_INSP = @` + NamedCodigoInspecaoEntrada
