package queries

const GetNotasFiscaisQuery = `
	SELECT
		DISTINCT
		HISTLISE.R_E_C_N_O_ AS Recno,
	    CAST(HISTLISE.Id as varchar(36)) AS Id,
		HISTLISE.NFISCAL AS NotaFiscal,
		HISTLISE.SERIE AS Serie,
		COALESCE(FORNECED.CODIGO, CLIENTES.CODIGO) AS CodigoForneced,
		COALESCE(FORNECED.RASSOC, CLIENTES.RASSOC) AS DescricaoForneced,
		CASE WHEN HISTLISE_RATEIO_LOTE.LOTE IS NULL THEN
			ISNULL(HISTLISE.LOTE, 0)
		ELSE
			HISTLISE_RATEIO_LOTE.LOTE
		END AS Lote,
		HISTLISE.ITEM AS CodigoProduto,
		HISTLISE.DESCRI AS DescricaoProduto,
		HISTLISE.DTENT AS DataEntrada,
		COALESCE(HISTLISE_RATEIO_LOTE.QTD, HISTLISE.QTENT) AS Quantidade,
        ESTOQUE_LOCAL.DTFABRICACAO AS DataFabricacao,
        ESTOQUE_LOCAL.VALIDADE AS DataValidade,
        ESTOQUE_LOCAL.EMPRESA_RECNO AS IdEmpresa,
		HISTLISE_RATEIO_LOTE.R_E_C_N_O_ AS RecnoRateioLote,
		ESTOQUE.PLAINS AS Plano,
		PLANOINS_CABECALHO.DESCRICAO AS DescricaoPlano,
		QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS.OBSERVACAO AS Observacao,
		-- sum
		ISNULL((
		SELECT
		SUM(QA_INSPECAO_ENTRADA.QTD_INSPECAO)
		FROM
		QA_INSPECAO_ENTRADA
		WHERE
		QA_INSPECAO_ENTRADA.RECNO_HISTLISE = HISTLISE.R_E_C_N_O_
		AND QA_INSPECAO_ENTRADA.LOTE = ISNULL(COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE), 0))
		, 0) AS QuantidadeInspecionada
		FROM
		HISTLISE
		LEFT JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
		LEFT JOIN CLIENTES ON CLIENTES.CODIGO = HISTLISE.FORNECE
		INNER JOIN LOCAIS ON HISTLISE.LOCAL_DESTINO = LOCAIS.CODIGO AND LOCAIS.LOCAL_CQ_ENTRADA = 'S'
		INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
		LEFT OUTER JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
		AND HISTLISE_RATEIO_LOTE.LOTE_FORNECEDOR = 'N'
		INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.CODIGO = HISTLISE.ITEM AND ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO
    	AND ESTOQUE_LOCAL.EMPRESA_RECNO = HISTLISE.EMPRESA_RECNO AND
		ESTOQUE_LOCAL.LOTE = ISNULL(COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE), 0)
		INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
		LEFT JOIN QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS ON QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS.IdNotaFiscal = HISTLISE.Id
		@JoinFilters
		WHERE
		HISTLISE.BAIXAESTOQUE = 'S' AND
		HISTLISE.EFETUADOENTR = 'S' AND
		HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND
        HISTLISE.QTENT > ISNULL((
        SELECT
        SUM(QA_INSPECAO_ENTRADA.QTD_INSPECAO)
        FROM
        QA_INSPECAO_ENTRADA
        WHERE
        QA_INSPECAO_ENTRADA.RECNO_HISTLISE = HISTLISE.R_E_C_N_O_
		AND QA_INSPECAO_ENTRADA.LOTE = ISNULL(COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE), 0)
        AND QA_INSPECAO_ENTRADA.INSPECIONADO = 'S')
        , 0)
		@CommonFilters
		@AdvancedFilter` + "\n"

const GetNotasFiscaisPagination = "@Sorting \n" +
	"OFFSET @Skip ROWS \n" +
	"FETCH NEXT @PageSize ROWS ONLY \n"

const GetNotasFiscaisCount = `
	SELECT COUNT(DISTINCT HISTLISE.R_E_C_N_O_)
		FROM
		HISTLISE
		LEFT JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
		LEFT JOIN CLIENTES ON CLIENTES.CODIGO = HISTLISE.FORNECE
		INNER JOIN LOCAIS ON HISTLISE.LOCAL_DESTINO = LOCAIS.CODIGO AND LOCAIS.LOCAL_CQ_ENTRADA = 'S'
		INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
		LEFT OUTER JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
		AND HISTLISE_RATEIO_LOTE.LOTE_FORNECEDOR = 'N'
		INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.CODIGO = HISTLISE.ITEM AND ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO
    	AND ESTOQUE_LOCAL.EMPRESA_RECNO = HISTLISE.EMPRESA_RECNO AND
		ESTOQUE_LOCAL.LOTE = ISNULL(COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE), 0)
		INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
		LEFT JOIN QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS ON QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS.IdNotaFiscal = HISTLISE.Id
		@JoinFilters
		WHERE
		HISTLISE.BAIXAESTOQUE = 'S' AND
		HISTLISE.EFETUADOENTR = 'S' AND
		HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND
        HISTLISE.QTENT > ISNULL((
        SELECT
        SUM(QA_INSPECAO_ENTRADA.QTD_INSPECAO)
        FROM
        QA_INSPECAO_ENTRADA
        WHERE
        QA_INSPECAO_ENTRADA.RECNO_HISTLISE = HISTLISE.R_E_C_N_O_
		AND QA_INSPECAO_ENTRADA.LOTE = ISNULL(COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE), 0)
        AND QA_INSPECAO_ENTRADA.INSPECIONADO = 'S')
        , 0)
		@CommonFilters
		@AdvancedFilter` + "\n"

const GetNotaFiscal = `
	SELECT
		HISTLISE.R_E_C_N_O_ AS Recno,
		HISTLISE.NFISCAL AS NotaFiscal,
		COALESCE(FORNECED.RASSOC, CLIENTES.RASSOC) AS DescricaoForneced,
		CASE WHEN HISTLISE_RATEIO_LOTE.LOTE IS NULL THEN
			ISNULL(HISTLISE.LOTE, 0)
		ELSE
			HISTLISE_RATEIO_LOTE.LOTE
		END AS Lote,
		HISTLISE.ITEM AS CodigoProduto,
		HISTLISE.DESCRI AS DescricaoProduto,
		HISTLISE.DTENT AS DataEntrada,
		CASE WHEN HISTLISE_RATEIO_LOTE.QTD IS NULL THEN
			HISTLISE.QTENT
		ELSE
			HISTLISE_RATEIO_LOTE.QTD
		END AS Quantidade,
		HISTLISE_RATEIO_LOTE.R_E_C_N_O_ AS RecnoRateioLote,
		HISTLISE.LOCAL_DESTINO AS CodigoLocal,
		HISTLISE.SERIE AS Serie,
        HISTLISE.DTFABRICACAO AS DataFabricacao,
        HISTLISE.VALIDADE AS DataValidade
		FROM
		HISTLISE
        LEFT JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
        LEFT JOIN CLIENTES ON CLIENTES.CODIGO = HISTLISE.FORNECE
		INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
		LEFT OUTER JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE`

const GetNotasFiscaisHistoricoQuery = `
SELECT
	DISTINCT
	CAST(HISTLISE.Id as varchar(36)) AS Id,
	HISTLISE.R_E_C_N_O_ AS Recno,
	HISTLISE.NFISCAL AS NotaFiscal,
	HISTLISE.ITEM AS CodigoProduto,
	HISTLISE.DESCRI AS DescricaoProduto,
	QA_INSPECAO_ENTRADA.LOTE AS Lote,
	AVG(QA_INSPECAO_ENTRADA.QTD_LOTE) AS Quantidade,
	SUM(QA_INSPECAO_ENTRADA.QTD_INSPECAO) AS QuantidadeInspecionada,
    COALESCE(FORNECED.RASSOC, CLIENTES.RASSOC) AS DescricaoForneced,
	ESTOQUE.PLAINS AS Plano,
	PLANOINS_CABECALHO.DESCRICAO AS DescricaoPlano,
	QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS.OBSERVACAO AS Observacao
FROM 
QA_INSPECAO_ENTRADA
INNER JOIN InspecaoEntradaExecutadoWeb ON InspecaoEntradaExecutadoWeb.RECNO_INSPECAO_Entrada = QA_INSPECAO_ENTRADA.R_E_C_N_O_
INNER JOIN HISTLISE ON HISTLISE.NFISCAL = QA_INSPECAO_ENTRADA.CODNOTA
AND HISTLISE.ITEM = InspecaoEntradaExecutadoWeb.CODIGO_PRODUTO
AND HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + " \n" + `
LEFT JOIN HISTLISE_RATEIO_LOTE on HISTLISE_RATEIO_LOTE.RECNO_HISTLISE = HISTLISE.R_E_C_N_O_ 
AND QA_INSPECAO_ENTRADA.LOTE = ISNULL(COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE), 0)
AND HISTLISE_RATEIO_LOTE.LOTE_FORNECEDOR = 'N'
LEFT JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
LEFT JOIN CLIENTES ON CLIENTES.CODIGO = HISTLISE.FORNECE
INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
LEFT JOIN QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS ON QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS.IdNotaFiscal = HISTLISE.Id
@JoinFilters
WHERE 
	Estorno = 0 AND QA_INSPECAO_ENTRADA.INSPECIONADO = 'S'
	@CommonFilters
	@AdvancedFilter
GROUP BY HISTLISE.Id, HISTLISE.R_E_C_N_O_, HISTLISE.NFISCAL, HISTLISE.ITEM, HISTLISE.DESCRI, QA_INSPECAO_ENTRADA.LOTE,
FORNECED.RASSOC, CLIENTES.RASSOC, ESTOQUE.PLAINS, PLANOINS_CABECALHO.DESCRICAO, QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS.OBSERVACAO
`

const GetNotasFiscaisHistoricoCount = `
SELECT 
	 COUNT(DISTINCT QA_INSPECAO_ENTRADA.R_E_C_N_O_)
FROM 
QA_INSPECAO_ENTRADA
INNER JOIN InspecaoEntradaExecutadoWeb ON InspecaoEntradaExecutadoWeb.RECNO_INSPECAO_Entrada = QA_INSPECAO_ENTRADA.R_E_C_N_O_
INNER JOIN HISTLISE ON HISTLISE.NFISCAL = QA_INSPECAO_ENTRADA.CODNOTA
AND HISTLISE.ITEM = InspecaoEntradaExecutadoWeb.CODIGO_PRODUTO
AND HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + " \n" + `
LEFT JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
LEFT JOIN CLIENTES ON CLIENTES.CODIGO = HISTLISE.FORNECE
INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
LEFT JOIN QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS ON QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS.IdNotaFiscal = HISTLISE.Id
@JoinFilters
WHERE 
	Estorno = 0 AND QA_INSPECAO_ENTRADA.INSPECIONADO = 'S'
	@CommonFilters
	@AdvancedFilter
GROUP BY HISTLISE.NFISCAL, HISTLISE.ITEM, HISTLISE.DESCRI, QA_INSPECAO_ENTRADA.LOTE
`

const GetCaracteristicaItemNotaFiscal = `
    SELECT  HISTLISE.DIM1 AS Dimensao1, HISTLISE.DIM2 AS Dimensao2, HISTLISE.DIM3 AS Dimensao3, HISTLISE.DIM_DIFKG AS Diferenca, CAST(ROUND(@` + NamedQuantidade + ` * HISTLISE.DIM_QTDE / HISTLISE.QTENT, 0) AS INT) AS Quantidade
    FROM ESTOQUE_CARAC
    INNER JOIN HISCARAC ON HISCARAC.CODIGO = ESTOQUE_CARAC.CODIGO
    AND HISCARAC.DIM1 = ESTOQUE_CARAC.DIM1
    AND HISCARAC.DIM2 = ESTOQUE_CARAC.DIM2
    AND ESTOQUE_CARAC.DIM3 = HISCARAC.DIM3
    AND HISCARAC.LOTE = ESTOQUE_CARAC.LOTE
    INNER JOIN HISREAL ON HISREAL.R_E_C_N_O_ = HISCARAC.RECNO_HISREAL
	AND HISREAL.MOV_EFETIVA = 'S'
    INNER JOIN  HISTLISE ON HISTLISE.R_E_C_N_O_ = HISREAL.RECNO_HISTLISE
	WHERE HISTLISE.R_E_C_N_O_ = @` + NamedRecnoItemNotaFiscal + `
`
