package queries

const GetNotasFiscaisQuery = `
	SELECT
		HISTLISE.NFISCAL AS NotaFiscal,
		FORNECED.RASSOC AS DescricaoForneced,
		CASE WHEN HISTLISE_RATEIO_LOTE.LOTE IS NULL THEN
			HISTLISE.LOTE
		ELSE
			HISTLISE_RATEIO_LOTE.LOTE
		END AS Lote,
		HISTLISE.ITEM AS CodigoProduto,
		HISTLISE.DESCRI AS DescricaoProduto,
		HISTLISE.DTENT AS DataEntrada,
		ESTOQUE_LOCAL.QTDE AS Quantidade,
		HISTLISE_RATEIO_LOTE.R_E_C_N_O_ AS RecnoRateioLote,
		ESTOQUE.PLAINS AS Plano,
		PLANOINS_CABECALHO.DESCRICAO AS DescricaoPlano,
		-- sum
		ISNULL((
		SELECT
		SUM(QA_INSPECAO_ENTRADA.QTD_INSPECAO)
		FROM
		QA_INSPECAO_ENTRADA
		WHERE
		QA_INSPECAO_ENTRADA.CODNOTA = HISTLISE.NFISCAL AND
		(QA_INSPECAO_ENTRADA.LOTE = HISTLISE_RATEIO_LOTE.LOTE OR QA_INSPECAO_ENTRADA.LOTE = HISTLISE.LOTE))
		, 0) AS QuantidadeInspecionada
		FROM
		HISTLISE
		INNER JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
		INNER JOIN LOCAIS ON HISTLISE.LOCAL_DESTINO = LOCAIS.CODIGO AND LOCAIS.LOCAL_CQ_ENTRADA = 'S'
		INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
		LEFT OUTER JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
		INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.CODIGO = HISTLISE.ITEM AND ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO
    	AND ESTOQUE_LOCAL.EMPRESA_RECNO = HISTLISE.EMPRESA_RECNO AND
    	(ESTOQUE_LOCAL.LOTE = HISTLISE_RATEIO_LOTE.LOTE OR ESTOQUE_LOCAL.LOTE = HISTLISE.LOTE)
		INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
		WHERE
		HISTLISE.BAIXAESTOQUE = 'S' AND
		HISTLISE.EFETUADOENTR = 'S' AND
		HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n"

const GetNotasFiscaisPagination = "ORDER BY HISTLISE.R_E_C_N_O_ \n" +
	"OFFSET @Skip ROWS \n" +
	"FETCH NEXT @PageSize ROWS ONLY \n"

const GetNotasFiscaisCount = `
	SELECT COUNT(*)
		FROM
		HISTLISE
		INNER JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
		INNER JOIN LOCAIS ON HISTLISE.LOCAL_DESTINO = LOCAIS.CODIGO AND LOCAIS.LOCAL_CQ_ENTRADA = 'S'
		INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
		LEFT OUTER JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
		INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.CODIGO = HISTLISE.ITEM AND ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO
    	AND ESTOQUE_LOCAL.EMPRESA_RECNO = HISTLISE.EMPRESA_RECNO AND
    	(ESTOQUE_LOCAL.LOTE = HISTLISE_RATEIO_LOTE.LOTE OR ESTOQUE_LOCAL.LOTE = HISTLISE.LOTE)
		INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
		WHERE
		HISTLISE.BAIXAESTOQUE = 'S' AND
		HISTLISE.EFETUADOENTR = 'S' AND
		HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n"

const GetNotaFiscal = `
	SELECT
		HISTLISE.NFISCAL AS NotaFiscal,
		FORNECED.RASSOC AS DescricaoForneced,
		CASE WHEN HISTLISE_RATEIO_LOTE.LOTE IS NULL THEN
			HISTLISE.LOTE
		ELSE
			HISTLISE_RATEIO_LOTE.LOTE
		END AS Lote,
		HISTLISE.ITEM AS CodigoProduto,
		HISTLISE.DESCRI AS DescricaoProduto,
		HISTLISE.DTENT AS DataEntrada,
		CASE WHEN HISTLISE_RATEIO_LOTE.QTD IS NULL THEN
			HISTLISE.QTENT
		ELSE
			HISTLISE_RATEIO_LOTE.QTD
		END AS Quantidade,
		HISTLISE_RATEIO_LOTE.R_E_C_N_O_ AS RecnoRateioLote,
		HISTLISE.LOCAL_DESTINO AS CodigoLocal
		FROM
		HISTLISE
		INNER JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
		INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
		LEFT OUTER JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
		WHERE
		HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND
		HISTLISE.NFISCAL = @` + NamedNotaFiscal + ` AND
		(HISTLISE_RATEIO_LOTE.LOTE = @` + NamedLote + ` OR HISTLISE.LOTE = @` + NamedLote + `)` + "\n"

const GetNotasFiscaisHistoricoQuery = `
SELECT 
	HISTLISE.R_E_C_N_O_,
	HISTLISE.NFISCAL AS NotaFiscal,
	HISTLISE.ITEM AS CodigoProduto,
	HISTLISE.DESCRI AS DescricaoProduto,
	QA_INSPECAO_ENTRADA.LOTE AS Lote,
	AVG(QA_INSPECAO_ENTRADA.QTD_LOTE) AS Quantidade,
	SUM(QA_INSPECAO_ENTRADA.QTD_INSPECAO) AS QuantidadeInspecionada,
	FORNECED.RASSOC AS DescricaoForneced,
	ESTOQUE.PLAINS AS Plano,
	PLANOINS_CABECALHO.DESCRICAO AS DescricaoPlano
FROM 
QA_INSPECAO_ENTRADA
INNER JOIN InspecaoEntradaExecutadoWeb ON InspecaoEntradaExecutadoWeb.RECNO_INSPECAO_Entrada = QA_INSPECAO_ENTRADA.R_E_C_N_O_
INNER JOIN HISTLISE ON HISTLISE.NFISCAL = QA_INSPECAO_ENTRADA.CODNOTA
AND HISTLISE.ITEM = InspecaoEntradaExecutadoWeb.CODIGO_PRODUTO
AND HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + " \n" + `
INNER JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
WHERE 
	Estorno = 0 AND QA_INSPECAO_ENTRADA.INSPECIONADO = 'S'
	%s
GROUP BY HISTLISE.R_E_C_N_O_, HISTLISE.NFISCAL, HISTLISE.ITEM, HISTLISE.DESCRI, QA_INSPECAO_ENTRADA.LOTE,
FORNECED.RASSOC, ESTOQUE.PLAINS, PLANOINS_CABECALHO.DESCRICAO
`

const GetNotasFiscaisHistoricoCount = `
SELECT 
	 COUNT(*)
FROM 
QA_INSPECAO_ENTRADA
INNER JOIN InspecaoEntradaExecutadoWeb ON InspecaoEntradaExecutadoWeb.RECNO_INSPECAO_Entrada = QA_INSPECAO_ENTRADA.R_E_C_N_O_
INNER JOIN HISTLISE ON HISTLISE.NFISCAL = QA_INSPECAO_ENTRADA.CODNOTA
AND HISTLISE.ITEM = InspecaoEntradaExecutadoWeb.CODIGO_PRODUTO
AND HISTLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + " \n" + `
INNER JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
INNER JOIN PLANOINS_CABECALHO on PLANOINS_CABECALHO.CODIGO = ESTOQUE.PLAINS
WHERE 
	Estorno = 0 AND QA_INSPECAO_ENTRADA.INSPECIONADO = 'S'
	%s
GROUP BY HISTLISE.NFISCAL, HISTLISE.ITEM, HISTLISE.DESCRI, QA_INSPECAO_ENTRADA.LOTE
`
