package queries

const GetAllPedidoVendaLoteQuery = `
SELECT CAST(Id AS VARCHAR(36)) AS Id,
       ID_INSPECAO_ENTRADA_PEDIDO_VENDA,
       NUMERO_LOTE,
       QUANTIDADE
       FROM QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB_LOTE WHERE ID_INSPECAO_ENTRADA_PEDIDO_VENDA IN (?)
`
