// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IEstoquePedidoVendaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIEstoquePedidoVendaService is a mock of IEstoquePedidoVendaService interface.
type MockIEstoquePedidoVendaService struct {
	ctrl     *gomock.Controller
	recorder *MockIEstoquePedidoVendaServiceMockRecorder
}

// MockIEstoquePedidoVendaServiceMockRecorder is the mock recorder for MockIEstoquePedidoVendaService.
type MockIEstoquePedidoVendaServiceMockRecorder struct {
	mock *MockIEstoquePedidoVendaService
}

// NewMockIEstoquePedidoVendaService creates a new mock instance.
func NewMockIEstoquePedidoVendaService(ctrl *gomock.Controller) *MockIEstoquePedidoVendaService {
	mock := &MockIEstoquePedidoVendaService{ctrl: ctrl}
	mock.recorder = &MockIEstoquePedidoVendaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEstoquePedidoVendaService) EXPECT() *MockIEstoquePedidoVendaServiceMockRecorder {
	return m.recorder
}

// AtualizarDistribuicaoInspecaoEstoquePedidoVenda mocks base method.
func (m *MockIEstoquePedidoVendaService) AtualizarDistribuicaoInspecaoEstoquePedidoVenda(arg0 uuid.UUID, arg1 int, arg2 dto.EstoqueLocalPedidoVendaAlocacaoDTO) (*dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarDistribuicaoInspecaoEstoquePedidoVenda", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.ValidacaoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AtualizarDistribuicaoInspecaoEstoquePedidoVenda indicates an expected call of AtualizarDistribuicaoInspecaoEstoquePedidoVenda.
func (mr *MockIEstoquePedidoVendaServiceMockRecorder) AtualizarDistribuicaoInspecaoEstoquePedidoVenda(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarDistribuicaoInspecaoEstoquePedidoVenda", reflect.TypeOf((*MockIEstoquePedidoVendaService)(nil).AtualizarDistribuicaoInspecaoEstoquePedidoVenda), arg0, arg1, arg2)
}

// BuscarEstoqueLocalPedidosVendas mocks base method.
func (m *MockIEstoquePedidoVendaService) BuscarEstoqueLocalPedidosVendas(arg0 *models.BaseFilter, arg1 int, arg2, arg3 string) (*dto.GetAllEstoqueLocalPedidoVendaAlocacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarEstoqueLocalPedidosVendas", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.GetAllEstoqueLocalPedidoVendaAlocacaoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarEstoqueLocalPedidosVendas indicates an expected call of BuscarEstoqueLocalPedidosVendas.
func (mr *MockIEstoquePedidoVendaServiceMockRecorder) BuscarEstoqueLocalPedidosVendas(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarEstoqueLocalPedidosVendas", reflect.TypeOf((*MockIEstoquePedidoVendaService)(nil).BuscarEstoqueLocalPedidosVendas), arg0, arg1, arg2, arg3)
}

// BuscarQuantidadeTotalAlocadaPedidoVenda mocks base method.
func (m *MockIEstoquePedidoVendaService) BuscarQuantidadeTotalAlocadaPedidoVenda(arg0 int) (*dto.EstoqueLocalPedidoVendoTotalizacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeTotalAlocadaPedidoVenda", arg0)
	ret0, _ := ret[0].(*dto.EstoqueLocalPedidoVendoTotalizacaoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeTotalAlocadaPedidoVenda indicates an expected call of BuscarQuantidadeTotalAlocadaPedidoVenda.
func (mr *MockIEstoquePedidoVendaServiceMockRecorder) BuscarQuantidadeTotalAlocadaPedidoVenda(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeTotalAlocadaPedidoVenda", reflect.TypeOf((*MockIEstoquePedidoVendaService)(nil).BuscarQuantidadeTotalAlocadaPedidoVenda), arg0)
}
