// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: ILocaisRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockILocaisRepository is a mock of ILocaisRepository interface.
type MockILocaisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILocaisRepositoryMockRecorder
}

// MockILocaisRepositoryMockRecorder is the mock recorder for MockILocaisRepository.
type MockILocaisRepositoryMockRecorder struct {
	mock *MockILocaisRepository
}

// NewMockILocaisRepository creates a new mock instance.
func NewMockILocaisRepository(ctrl *gomock.Controller) *MockILocaisRepository {
	mock := &MockILocaisRepository{ctrl: ctrl}
	mock.recorder = &MockILocaisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILocaisRepository) EXPECT() *MockILocaisRepositoryMockRecorder {
	return m.recorder
}

// BuscarLocais mocks base method.
func (m *MockILocaisRepository) BuscarLocais(arg0 *models.BaseFilter) ([]dto.LocalOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocais", arg0)
	ret0, _ := ret[0].([]dto.LocalOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocais indicates an expected call of BuscarLocais.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocais(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocais", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocais), arg0)
}

// BuscarLocaisPrincipais mocks base method.
func (m *MockILocaisRepository) BuscarLocaisPrincipais(arg0 string) ([]dto.LocalOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocaisPrincipais", arg0)
	ret0, _ := ret[0].([]dto.LocalOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocaisPrincipais indicates an expected call of BuscarLocaisPrincipais.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocaisPrincipais(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocaisPrincipais", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocaisPrincipais), arg0)
}

// BuscarLocaisReprovados mocks base method.
func (m *MockILocaisRepository) BuscarLocaisReprovados() ([]dto.LocalOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocaisReprovados")
	ret0, _ := ret[0].([]dto.LocalOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocaisReprovados indicates an expected call of BuscarLocaisReprovados.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocaisReprovados() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocaisReprovados", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocaisReprovados))
}

// BuscarLocaisTotalCount mocks base method.
func (m *MockILocaisRepository) BuscarLocaisTotalCount(arg0 *models.BaseFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocaisTotalCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocaisTotalCount indicates an expected call of BuscarLocaisTotalCount.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocaisTotalCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocaisTotalCount", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocaisTotalCount), arg0)
}

// BuscarLocalAprovado mocks base method.
func (m *MockILocaisRepository) BuscarLocalAprovado(arg0 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocalAprovado", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocalAprovado indicates an expected call of BuscarLocalAprovado.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocalAprovado(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocalAprovado", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocalAprovado), arg0)
}

// BuscarLocalDescricao mocks base method.
func (m *MockILocaisRepository) BuscarLocalDescricao(arg0 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocalDescricao", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocalDescricao indicates an expected call of BuscarLocalDescricao.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocalDescricao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocalDescricao", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocalDescricao), arg0)
}

// BuscarLocalEntrada mocks base method.
func (m *MockILocaisRepository) BuscarLocalEntrada() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocalEntrada")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocalEntrada indicates an expected call of BuscarLocalEntrada.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocalEntrada() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocalEntrada", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocalEntrada))
}

// BuscarLocalPeloCodigo mocks base method.
func (m *MockILocaisRepository) BuscarLocalPeloCodigo(arg0 int) (*dto.LocalOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocalPeloCodigo", arg0)
	ret0, _ := ret[0].(*dto.LocalOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocalPeloCodigo indicates an expected call of BuscarLocalPeloCodigo.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocalPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocalPeloCodigo", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocalPeloCodigo), arg0)
}

// BuscarLocalReprovado mocks base method.
func (m *MockILocaisRepository) BuscarLocalReprovado() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocalReprovado")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocalReprovado indicates an expected call of BuscarLocalReprovado.
func (mr *MockILocaisRepositoryMockRecorder) BuscarLocalReprovado() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocalReprovado", reflect.TypeOf((*MockILocaisRepository)(nil).BuscarLocalReprovado))
}
