// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: ILocalService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockILocalService is a mock of ILocalService interface.
type MockILocalService struct {
	ctrl     *gomock.Controller
	recorder *MockILocalServiceMockRecorder
}

// MockILocalServiceMockRecorder is the mock recorder for MockILocalService.
type MockILocalServiceMockRecorder struct {
	mock *MockILocalService
}

// NewMockILocalService creates a new mock instance.
func NewMockILocalService(ctrl *gomock.Controller) *MockILocalService {
	mock := &MockILocalService{ctrl: ctrl}
	mock.recorder = &MockILocalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILocalService) EXPECT() *MockILocalServiceMockRecorder {
	return m.recorder
}

// BuscarLocais mocks base method.
func (m *MockILocalService) BuscarLocais(arg0 *models.BaseFilter) (*dto.GetLocais, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocais", arg0)
	ret0, _ := ret[0].(*dto.GetLocais)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocais indicates an expected call of BuscarLocais.
func (mr *MockILocalServiceMockRecorder) BuscarLocais(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocais", reflect.TypeOf((*MockILocalService)(nil).BuscarLocais), arg0)
}

// BuscarLocal mocks base method.
func (m *MockILocalService) BuscarLocal(arg0 int) (*dto.LocalOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLocal", arg0)
	ret0, _ := ret[0].(*dto.LocalOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLocal indicates an expected call of BuscarLocal.
func (mr *MockILocalServiceMockRecorder) BuscarLocal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLocal", reflect.TypeOf((*MockILocalService)(nil).BuscarLocal), arg0)
}
