// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaHistoricoRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaHistoricoRepository is a mock of IInspecaoEntradaHistoricoRepository interface.
type MockIInspecaoEntradaHistoricoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaHistoricoRepositoryMockRecorder
}

// MockIInspecaoEntradaHistoricoRepositoryMockRecorder is the mock recorder for MockIInspecaoEntradaHistoricoRepository.
type MockIInspecaoEntradaHistoricoRepositoryMockRecorder struct {
	mock *MockIInspecaoEntradaHistoricoRepository
}

// NewMockIInspecaoEntradaHistoricoRepository creates a new mock instance.
func NewMockIInspecaoEntradaHistoricoRepository(ctrl *gomock.Controller) *MockIInspecaoEntradaHistoricoRepository {
	mock := &MockIInspecaoEntradaHistoricoRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaHistoricoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaHistoricoRepository) EXPECT() *MockIInspecaoEntradaHistoricoRepositoryMockRecorder {
	return m.recorder
}

// BuscarInspecoesEntradaHistorico mocks base method.
func (m *MockIInspecaoEntradaHistoricoRepository) BuscarInspecoesEntradaHistorico(arg0 int, arg1 string, arg2 *models.BaseFilter) ([]dto.InspecaoEntradaHistoricoItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecoesEntradaHistorico", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dto.InspecaoEntradaHistoricoItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecoesEntradaHistorico indicates an expected call of BuscarInspecoesEntradaHistorico.
func (mr *MockIInspecaoEntradaHistoricoRepositoryMockRecorder) BuscarInspecoesEntradaHistorico(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecoesEntradaHistorico", reflect.TypeOf((*MockIInspecaoEntradaHistoricoRepository)(nil).BuscarInspecoesEntradaHistorico), arg0, arg1, arg2)
}

// BuscarNotasFiscaisHistorico mocks base method.
func (m *MockIInspecaoEntradaHistoricoRepository) BuscarNotasFiscaisHistorico(arg0 *models.BaseFilter, arg1 *dto.InspecaoEntradaHistoricoCabecalhoFilters) ([]models.NotaFiscalModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarNotasFiscaisHistorico", arg0, arg1)
	ret0, _ := ret[0].([]models.NotaFiscalModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarNotasFiscaisHistorico indicates an expected call of BuscarNotasFiscaisHistorico.
func (mr *MockIInspecaoEntradaHistoricoRepositoryMockRecorder) BuscarNotasFiscaisHistorico(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarNotasFiscaisHistorico", reflect.TypeOf((*MockIInspecaoEntradaHistoricoRepository)(nil).BuscarNotasFiscaisHistorico), arg0, arg1)
}

// BuscarNotasFiscaisHistoricoTotalCount mocks base method.
func (m *MockIInspecaoEntradaHistoricoRepository) BuscarNotasFiscaisHistoricoTotalCount(arg0 *dto.InspecaoEntradaHistoricoCabecalhoFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarNotasFiscaisHistoricoTotalCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarNotasFiscaisHistoricoTotalCount indicates an expected call of BuscarNotasFiscaisHistoricoTotalCount.
func (mr *MockIInspecaoEntradaHistoricoRepositoryMockRecorder) BuscarNotasFiscaisHistoricoTotalCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarNotasFiscaisHistoricoTotalCount", reflect.TypeOf((*MockIInspecaoEntradaHistoricoRepository)(nil).BuscarNotasFiscaisHistoricoTotalCount), arg0)
}

// BuscarQuantidadeInspecoesEntradaHistorico mocks base method.
func (m *MockIInspecaoEntradaHistoricoRepository) BuscarQuantidadeInspecoesEntradaHistorico(arg0 int, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeInspecoesEntradaHistorico", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeInspecoesEntradaHistorico indicates an expected call of BuscarQuantidadeInspecoesEntradaHistorico.
func (mr *MockIInspecaoEntradaHistoricoRepositoryMockRecorder) BuscarQuantidadeInspecoesEntradaHistorico(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeInspecoesEntradaHistorico", reflect.TypeOf((*MockIInspecaoEntradaHistoricoRepository)(nil).BuscarQuantidadeInspecoesEntradaHistorico), arg0, arg1)
}
