// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IParametrosRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIParametrosRepository is a mock of IParametrosRepository interface.
type MockIParametrosRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIParametrosRepositoryMockRecorder
}

// MockIParametrosRepositoryMockRecorder is the mock recorder for MockIParametrosRepository.
type MockIParametrosRepositoryMockRecorder struct {
	mock *MockIParametrosRepository
}

// NewMockIParametrosRepository creates a new mock instance.
func NewMockIParametrosRepository(ctrl *gomock.Controller) *MockIParametrosRepository {
	mock := &MockIParametrosRepository{ctrl: ctrl}
	mock.recorder = &MockIParametrosRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIParametrosRepository) EXPECT() *MockIParametrosRepositoryMockRecorder {
	return m.recorder
}

// BuscarValorParametro mocks base method.
func (m *MockIParametrosRepository) BuscarValorParametro(arg0, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarValorParametro", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarValorParametro indicates an expected call of BuscarValorParametro.
func (mr *MockIParametrosRepositoryMockRecorder) BuscarValorParametro(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarValorParametro", reflect.TypeOf((*MockIParametrosRepository)(nil).BuscarValorParametro), arg0, arg1)
}
