// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IEstoquePedidoVendaRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/entities"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIEstoquePedidoVendaRepository is a mock of IEstoquePedidoVendaRepository interface.
type MockIEstoquePedidoVendaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIEstoquePedidoVendaRepositoryMockRecorder
}

// MockIEstoquePedidoVendaRepositoryMockRecorder is the mock recorder for MockIEstoquePedidoVendaRepository.
type MockIEstoquePedidoVendaRepositoryMockRecorder struct {
	mock *MockIEstoquePedidoVendaRepository
}

// NewMockIEstoquePedidoVendaRepository creates a new mock instance.
func NewMockIEstoquePedidoVendaRepository(ctrl *gomock.Controller) *MockIEstoquePedidoVendaRepository {
	mock := &MockIEstoquePedidoVendaRepository{ctrl: ctrl}
	mock.recorder = &MockIEstoquePedidoVendaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEstoquePedidoVendaRepository) EXPECT() *MockIEstoquePedidoVendaRepositoryMockRecorder {
	return m.recorder
}

// AtualizarDistribuicaoInspecaoEstoquePedidoVenda mocks base method.
func (m *MockIEstoquePedidoVendaRepository) AtualizarDistribuicaoInspecaoEstoquePedidoVenda(arg0 uuid.UUID, arg1 dto.EstoqueLocalPedidoVendaAlocacaoDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarDistribuicaoInspecaoEstoquePedidoVenda", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarDistribuicaoInspecaoEstoquePedidoVenda indicates an expected call of AtualizarDistribuicaoInspecaoEstoquePedidoVenda.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) AtualizarDistribuicaoInspecaoEstoquePedidoVenda(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarDistribuicaoInspecaoEstoquePedidoVenda", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).AtualizarDistribuicaoInspecaoEstoquePedidoVenda), arg0, arg1)
}

// BuscarAlocacaoEstoquePedidoVenda mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarAlocacaoEstoquePedidoVenda(arg0 uuid.UUID) (entities.InspecaoEntradaPedidoVenda, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarAlocacaoEstoquePedidoVenda", arg0)
	ret0, _ := ret[0].(entities.InspecaoEntradaPedidoVenda)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarAlocacaoEstoquePedidoVenda indicates an expected call of BuscarAlocacaoEstoquePedidoVenda.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarAlocacaoEstoquePedidoVenda(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarAlocacaoEstoquePedidoVenda", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarAlocacaoEstoquePedidoVenda), arg0)
}

// BuscarEstoqueLocalPedidosVendas mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarEstoqueLocalPedidosVendas(arg0 *models.BaseFilter, arg1 int, arg2, arg3 string) ([]dto.EstoqueLocalPedidoVendaAlocacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarEstoqueLocalPedidosVendas", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]dto.EstoqueLocalPedidoVendaAlocacaoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarEstoqueLocalPedidosVendas indicates an expected call of BuscarEstoqueLocalPedidosVendas.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarEstoqueLocalPedidosVendas(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarEstoqueLocalPedidosVendas", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarEstoqueLocalPedidosVendas), arg0, arg1, arg2, arg3)
}

// BuscarEstoqueLocalValoresPorProduto mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarEstoqueLocalValoresPorProduto(arg0, arg1 string, arg2 int) (*models.EstoqueLocalValores, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarEstoqueLocalValoresPorProduto", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.EstoqueLocalValores)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarEstoqueLocalValoresPorProduto indicates an expected call of BuscarEstoqueLocalValoresPorProduto.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarEstoqueLocalValoresPorProduto(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarEstoqueLocalValoresPorProduto", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarEstoqueLocalValoresPorProduto), arg0, arg1, arg2)
}

// BuscarPacotes mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarPacotes(arg0 int) ([]models.Pacote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarPacotes", arg0)
	ret0, _ := ret[0].([]models.Pacote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarPacotes indicates an expected call of BuscarPacotes.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarPacotes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarPacotes", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarPacotes), arg0)
}

// BuscarQuantidadeTotalAlocadaPedidoVenda mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarQuantidadeTotalAlocadaPedidoVenda(arg0 int) (*dto.EstoqueLocalPedidoVendoTotalizacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeTotalAlocadaPedidoVenda", arg0)
	ret0, _ := ret[0].(*dto.EstoqueLocalPedidoVendoTotalizacaoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeTotalAlocadaPedidoVenda indicates an expected call of BuscarQuantidadeTotalAlocadaPedidoVenda.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarQuantidadeTotalAlocadaPedidoVenda(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeTotalAlocadaPedidoVenda", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarQuantidadeTotalAlocadaPedidoVenda), arg0)
}

// BuscarSeries mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarSeries(arg0 int) ([]models.Serie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSeries", arg0)
	ret0, _ := ret[0].([]models.Serie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSeries indicates an expected call of BuscarSeries.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarSeries(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSeries", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarSeries), arg0)
}

// BuscarTotalCountEstoqueLocalPedidosVendas mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarTotalCountEstoqueLocalPedidosVendas(arg0 int, arg1, arg2 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarTotalCountEstoqueLocalPedidosVendas", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarTotalCountEstoqueLocalPedidosVendas indicates an expected call of BuscarTotalCountEstoqueLocalPedidosVendas.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarTotalCountEstoqueLocalPedidosVendas(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarTotalCountEstoqueLocalPedidosVendas", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarTotalCountEstoqueLocalPedidosVendas), arg0, arg1, arg2)
}

// RemoverInspecaoEntradaPedidoVenda mocks base method.
func (m *MockIEstoquePedidoVendaRepository) RemoverInspecaoEntradaPedidoVenda(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverInspecaoEntradaPedidoVenda", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverInspecaoEntradaPedidoVenda indicates an expected call of RemoverInspecaoEntradaPedidoVenda.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) RemoverInspecaoEntradaPedidoVenda(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverInspecaoEntradaPedidoVenda", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).RemoverInspecaoEntradaPedidoVenda), arg0)
}

// SeedEstoqueLocalPedidosVendasInspecaoValues mocks base method.
func (m *MockIEstoquePedidoVendaRepository) SeedEstoqueLocalPedidosVendasInspecaoValues(arg0, arg1, arg2 int, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeedEstoqueLocalPedidosVendasInspecaoValues", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SeedEstoqueLocalPedidosVendasInspecaoValues indicates an expected call of SeedEstoqueLocalPedidosVendasInspecaoValues.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) SeedEstoqueLocalPedidosVendasInspecaoValues(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeedEstoqueLocalPedidosVendasInspecaoValues", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).SeedEstoqueLocalPedidosVendasInspecaoValues), arg0, arg1, arg2, arg3, arg4)
}
