// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaService is a mock of IInspecaoEntradaService interface.
type MockIInspecaoEntradaService struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaServiceMockRecorder
}

// MockIInspecaoEntradaServiceMockRecorder is the mock recorder for MockIInspecaoEntradaService.
type MockIInspecaoEntradaServiceMockRecorder struct {
	mock *MockIInspecaoEntradaService
}

// NewMockIInspecaoEntradaService creates a new mock instance.
func NewMockIInspecaoEntradaService(ctrl *gomock.Controller) *MockIInspecaoEntradaService {
	mock := &MockIInspecaoEntradaService{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaService) EXPECT() *MockIInspecaoEntradaServiceMockRecorder {
	return m.recorder
}

// AtualizarInspecao mocks base method.
func (m *MockIInspecaoEntradaService) AtualizarInspecao(arg0 *dto.AtualizarInspecaoInput) (*dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarInspecao", arg0)
	ret0, _ := ret[0].(*dto.ValidacaoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AtualizarInspecao indicates an expected call of AtualizarInspecao.
func (mr *MockIInspecaoEntradaServiceMockRecorder) AtualizarInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarInspecao", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).AtualizarInspecao), arg0)
}

// BuscarInspecaoEntradaItensPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaService) BuscarInspecaoEntradaItensPeloCodigo(arg0 string, arg1 int, arg2 *models.BaseFilter) (*dto.GetInspecaoEntradaItensDTO, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaItensPeloCodigo", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.GetInspecaoEntradaItensDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BuscarInspecaoEntradaItensPeloCodigo indicates an expected call of BuscarInspecaoEntradaItensPeloCodigo.
func (mr *MockIInspecaoEntradaServiceMockRecorder) BuscarInspecaoEntradaItensPeloCodigo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).BuscarInspecaoEntradaItensPeloCodigo), arg0, arg1, arg2)
}

// BuscarInspecaoEntradaPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaService) BuscarInspecaoEntradaPeloCodigo(arg0 int) (dto.InspecaoEntradaDTO, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaPeloCodigo", arg0)
	ret0, _ := ret[0].(dto.InspecaoEntradaDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BuscarInspecaoEntradaPeloCodigo indicates an expected call of BuscarInspecaoEntradaPeloCodigo.
func (mr *MockIInspecaoEntradaServiceMockRecorder) BuscarInspecaoEntradaPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).BuscarInspecaoEntradaPeloCodigo), arg0)
}

// BuscarInspecoesEntrada mocks base method.
func (m *MockIInspecaoEntradaService) BuscarInspecoesEntrada(arg0 int, arg1 string, arg2 *models.BaseFilter) (*dto.GetInspecaoEntradaDTO, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecoesEntrada", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.GetInspecaoEntradaDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BuscarInspecoesEntrada indicates an expected call of BuscarInspecoesEntrada.
func (mr *MockIInspecaoEntradaServiceMockRecorder) BuscarInspecoesEntrada(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecoesEntrada", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).BuscarInspecoesEntrada), arg0, arg1, arg2)
}

// BuscarPlanosNovaInspecao mocks base method.
func (m *MockIInspecaoEntradaService) BuscarPlanosNovaInspecao(arg0 int, arg1 string, arg2 *models.BaseFilter) (*dto.GetPlanosInspecaoDTO, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarPlanosNovaInspecao", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.GetPlanosInspecaoDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BuscarPlanosNovaInspecao indicates an expected call of BuscarPlanosNovaInspecao.
func (mr *MockIInspecaoEntradaServiceMockRecorder) BuscarPlanosNovaInspecao(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarPlanosNovaInspecao", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).BuscarPlanosNovaInspecao), arg0, arg1, arg2)
}

// BuscarResultadoInspecao mocks base method.
func (m *MockIInspecaoEntradaService) BuscarResultadoInspecao(arg0 int) (string, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarResultadoInspecao", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BuscarResultadoInspecao indicates an expected call of BuscarResultadoInspecao.
func (mr *MockIInspecaoEntradaServiceMockRecorder) BuscarResultadoInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarResultadoInspecao", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).BuscarResultadoInspecao), arg0)
}

// BuscarValorParametro mocks base method.
func (m *MockIInspecaoEntradaService) BuscarValorParametro(arg0, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarValorParametro", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarValorParametro indicates an expected call of BuscarValorParametro.
func (mr *MockIInspecaoEntradaServiceMockRecorder) BuscarValorParametro(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarValorParametro", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).BuscarValorParametro), arg0, arg1)
}

// CriarInspecao mocks base method.
func (m *MockIInspecaoEntradaService) CriarInspecao(arg0 *dto.NovaInspecaoInput) (int, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CriarInspecao", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CriarInspecao indicates an expected call of CriarInspecao.
func (mr *MockIInspecaoEntradaServiceMockRecorder) CriarInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CriarInspecao", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).CriarInspecao), arg0)
}

// RemoverInspecaoEntradaPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaService) RemoverInspecaoEntradaPeloCodigo(arg0 int) (*dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverInspecaoEntradaPeloCodigo", arg0)
	ret0, _ := ret[0].(*dto.ValidacaoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoverInspecaoEntradaPeloCodigo indicates an expected call of RemoverInspecaoEntradaPeloCodigo.
func (mr *MockIInspecaoEntradaServiceMockRecorder) RemoverInspecaoEntradaPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverInspecaoEntradaPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaService)(nil).RemoverInspecaoEntradaPeloCodigo), arg0)
}
