// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IExternalMovimentacaoService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockIExternalMovimentacaoService is a mock of IExternalMovimentacaoService interface.
type MockIExternalMovimentacaoService struct {
	ctrl     *gomock.Controller
	recorder *MockIExternalMovimentacaoServiceMockRecorder
}

// MockIExternalMovimentacaoServiceMockRecorder is the mock recorder for MockIExternalMovimentacaoService.
type MockIExternalMovimentacaoServiceMockRecorder struct {
	mock *MockIExternalMovimentacaoService
}

// NewMockIExternalMovimentacaoService creates a new mock instance.
func NewMockIExternalMovimentacaoService(ctrl *gomock.Controller) *MockIExternalMovimentacaoService {
	mock := &MockIExternalMovimentacaoService{ctrl: ctrl}
	mock.recorder = &MockIExternalMovimentacaoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExternalMovimentacaoService) EXPECT() *MockIExternalMovimentacaoServiceMockRecorder {
	return m.recorder
}

// RealizarMovimentacao mocks base method.
func (m *MockIExternalMovimentacaoService) RealizarMovimentacao(arg0 *entities.InspecaoEntrada) *dto.ValidacaoDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RealizarMovimentacao", arg0)
	ret0, _ := ret[0].(*dto.ValidacaoDTO)
	return ret0
}

// RealizarMovimentacao indicates an expected call of RealizarMovimentacao.
func (mr *MockIExternalMovimentacaoServiceMockRecorder) RealizarMovimentacao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RealizarMovimentacao", reflect.TypeOf((*MockIExternalMovimentacaoService)(nil).RealizarMovimentacao), arg0)
}
