// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/entities"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaRepository is a mock of IInspecaoEntradaRepository interface.
type MockIInspecaoEntradaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaRepositoryMockRecorder
}

// MockIInspecaoEntradaRepositoryMockRecorder is the mock recorder for MockIInspecaoEntradaRepository.
type MockIInspecaoEntradaRepositoryMockRecorder struct {
	mock *MockIInspecaoEntradaRepository
}

// NewMockIInspecaoEntradaRepository creates a new mock instance.
func NewMockIInspecaoEntradaRepository(ctrl *gomock.Controller) *MockIInspecaoEntradaRepository {
	mock := &MockIInspecaoEntradaRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaRepository) EXPECT() *MockIInspecaoEntradaRepositoryMockRecorder {
	return m.recorder
}

// AtualizarQuantidadeInspecaoPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaRepository) AtualizarQuantidadeInspecaoPeloCodigo(arg0 int, arg1 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarQuantidadeInspecaoPeloCodigo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarQuantidadeInspecaoPeloCodigo indicates an expected call of AtualizarQuantidadeInspecaoPeloCodigo.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) AtualizarQuantidadeInspecaoPeloCodigo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarQuantidadeInspecaoPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).AtualizarQuantidadeInspecaoPeloCodigo), arg0, arg1)
}

// BuscarInformacoesPreenchimentoRNC mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarInformacoesPreenchimentoRNC(arg0, arg1 int, arg2 string, arg3 string) (*dto.RncDetailsOutputDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInformacoesPreenchimentoRNC", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.RncDetailsOutputDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInformacoesPreenchimentoRNC indicates an expected call of BuscarInformacoesPreenchimentoRNC.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarInformacoesPreenchimentoRNC(arg0, arg1, arg2 interface{}, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInformacoesPreenchimentoRNC", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarInformacoesPreenchimentoRNC), arg0, arg1, arg2, arg3)
}

// BuscarInspecaoEntradaDetalhesPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarInspecaoEntradaDetalhesPeloCodigo(arg0 int) (*models.InspecaoEntrada, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaDetalhesPeloCodigo", arg0)
	ret0, _ := ret[0].(*models.InspecaoEntrada)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoEntradaDetalhesPeloCodigo indicates an expected call of BuscarInspecaoEntradaDetalhesPeloCodigo.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarInspecaoEntradaDetalhesPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaDetalhesPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarInspecaoEntradaDetalhesPeloCodigo), arg0)
}

// BuscarInspecaoEntradaDetalhesPeloCodigoJoin mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarInspecaoEntradaDetalhesPeloCodigoJoin(arg0 int) ([]models.InspecaoEntradaJoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaDetalhesPeloCodigoJoin", arg0)
	ret0, _ := ret[0].([]models.InspecaoEntradaJoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoEntradaDetalhesPeloCodigoJoin indicates an expected call of BuscarInspecaoEntradaDetalhesPeloCodigoJoin.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarInspecaoEntradaDetalhesPeloCodigoJoin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaDetalhesPeloCodigoJoin", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarInspecaoEntradaDetalhesPeloCodigoJoin), arg0)
}

// BuscarInspecaoEntradaPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarInspecaoEntradaPeloCodigo(arg0 int) (entities.InspecaoEntrada, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaPeloCodigo", arg0)
	ret0, _ := ret[0].(entities.InspecaoEntrada)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoEntradaPeloCodigo indicates an expected call of BuscarInspecaoEntradaPeloCodigo.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarInspecaoEntradaPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarInspecaoEntradaPeloCodigo), arg0)
}

// BuscarInspecaoEntradaPeloRecno mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarInspecaoEntradaPeloRecno(arg0 int) (*entities.InspecaoEntrada, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaPeloRecno", arg0)
	ret0, _ := ret[0].(*entities.InspecaoEntrada)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoEntradaPeloRecno indicates an expected call of BuscarInspecaoEntradaPeloRecno.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarInspecaoEntradaPeloRecno(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaPeloRecno", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarInspecaoEntradaPeloRecno), arg0)
}

// BuscarInspecoesEntrada mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarInspecoesEntrada(arg0 int, arg1 string, arg2 *models.BaseFilter, arg3 *dto.InspecaoEntradaFilters) ([]entities.InspecaoEntrada, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecoesEntrada", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]entities.InspecaoEntrada)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecoesEntrada indicates an expected call of BuscarInspecoesEntrada.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarInspecoesEntrada(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecoesEntrada", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarInspecoesEntrada), arg0, arg1, arg2, arg3)
}

// BuscarNovoCodigoInspecao mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarNovoCodigoInspecao() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarNovoCodigoInspecao")
	ret0, _ := ret[0].(int)
	return ret0
}

// BuscarNovoCodigoInspecao indicates an expected call of BuscarNovoCodigoInspecao.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarNovoCodigoInspecao() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarNovoCodigoInspecao", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarNovoCodigoInspecao))
}

// BuscarQuantidadeInspecoesEntrada mocks base method.
func (m *MockIInspecaoEntradaRepository) BuscarQuantidadeInspecoesEntrada(arg0 int, arg1 string, arg2 *models.BaseFilter, arg3 *dto.InspecaoEntradaFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeInspecoesEntrada", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeInspecoesEntrada indicates an expected call of BuscarQuantidadeInspecoesEntrada.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) BuscarQuantidadeInspecoesEntrada(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeInspecoesEntrada", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).BuscarQuantidadeInspecoesEntrada), arg0, arg1, arg2, arg3)
}

// CriarInspecao mocks base method.
func (m *MockIInspecaoEntradaRepository) CriarInspecao(arg0 *models.InspecaoEntrada) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CriarInspecao", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CriarInspecao indicates an expected call of CriarInspecao.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) CriarInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CriarInspecao", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).CriarInspecao), arg0)
}

// RemoverInspecaoEntrada mocks base method.
func (m *MockIInspecaoEntradaRepository) RemoverInspecaoEntrada(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverInspecaoEntrada", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverInspecaoEntrada indicates an expected call of RemoverInspecaoEntrada.
func (mr *MockIInspecaoEntradaRepositoryMockRecorder) RemoverInspecaoEntrada(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverInspecaoEntrada", reflect.TypeOf((*MockIInspecaoEntradaRepository)(nil).RemoverInspecaoEntrada), arg0)
}
