// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaSagaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaSagaService is a mock of IInspecaoEntradaSagaService interface.
type MockIInspecaoEntradaSagaService struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaSagaServiceMockRecorder
}

// MockIInspecaoEntradaSagaServiceMockRecorder is the mock recorder for MockIInspecaoEntradaSagaService.
type MockIInspecaoEntradaSagaServiceMockRecorder struct {
	mock *MockIInspecaoEntradaSagaService
}

// NewMockIInspecaoEntradaSagaService creates a new mock instance.
func NewMockIInspecaoEntradaSagaService(ctrl *gomock.Controller) *MockIInspecaoEntradaSagaService {
	mock := &MockIInspecaoEntradaSagaService{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaSagaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaSagaService) EXPECT() *MockIInspecaoEntradaSagaServiceMockRecorder {
	return m.recorder
}

// BuscarSagas mocks base method.
func (m *MockIInspecaoEntradaSagaService) BuscarSagas(arg0 *models.BaseFilter, arg1 *dto.ProcessamentoInspecaoEntradaFilters, arg2 bool) (*dto.GetAllProcessamentoInspecaoEntradaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSagas", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.GetAllProcessamentoInspecaoEntradaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSagas indicates an expected call of BuscarSagas.
func (mr *MockIInspecaoEntradaSagaServiceMockRecorder) BuscarSagas(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSagas", reflect.TypeOf((*MockIInspecaoEntradaSagaService)(nil).BuscarSagas), arg0, arg1, arg2)
}

// PublicarSagaInspecaoEntrada mocks base method.
func (m *MockIInspecaoEntradaSagaService) PublicarSagaInspecaoEntrada(arg0 *dto.FinalizarInspecaoInput) (bool, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicarSagaInspecaoEntrada", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PublicarSagaInspecaoEntrada indicates an expected call of PublicarSagaInspecaoEntrada.
func (mr *MockIInspecaoEntradaSagaServiceMockRecorder) PublicarSagaInspecaoEntrada(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicarSagaInspecaoEntrada", reflect.TypeOf((*MockIInspecaoEntradaSagaService)(nil).PublicarSagaInspecaoEntrada), arg0)
}

// PublicarSagaInspecaoEntradaEstorno mocks base method.
func (m *MockIInspecaoEntradaSagaService) PublicarSagaInspecaoEntradaEstorno(arg0 int) (bool, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicarSagaInspecaoEntradaEstorno", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PublicarSagaInspecaoEntradaEstorno indicates an expected call of PublicarSagaInspecaoEntradaEstorno.
func (mr *MockIInspecaoEntradaSagaServiceMockRecorder) PublicarSagaInspecaoEntradaEstorno(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicarSagaInspecaoEntradaEstorno", reflect.TypeOf((*MockIInspecaoEntradaSagaService)(nil).PublicarSagaInspecaoEntradaEstorno), arg0)
}

// RemoverSaga mocks base method.
func (m *MockIInspecaoEntradaSagaService) RemoverSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverSaga indicates an expected call of RemoverSaga.
func (mr *MockIInspecaoEntradaSagaServiceMockRecorder) RemoverSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverSaga", reflect.TypeOf((*MockIInspecaoEntradaSagaService)(nil).RemoverSaga), arg0)
}

// ReprocessarSaga mocks base method.
func (m *MockIInspecaoEntradaSagaService) ReprocessarSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessarSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReprocessarSaga indicates an expected call of ReprocessarSaga.
func (mr *MockIInspecaoEntradaSagaServiceMockRecorder) ReprocessarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessarSaga", reflect.TypeOf((*MockIInspecaoEntradaSagaService)(nil).ReprocessarSaga), arg0)
}
