// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IExternalInspecaoEntradaSagaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockIExternalInspecaoEntradaSagaService is a mock of IExternalInspecaoEntradaSagaService interface.
type MockIExternalInspecaoEntradaSagaService struct {
	ctrl     *gomock.Controller
	recorder *MockIExternalInspecaoEntradaSagaServiceMockRecorder
}

// MockIExternalInspecaoEntradaSagaServiceMockRecorder is the mock recorder for MockIExternalInspecaoEntradaSagaService.
type MockIExternalInspecaoEntradaSagaServiceMockRecorder struct {
	mock *MockIExternalInspecaoEntradaSagaService
}

// NewMockIExternalInspecaoEntradaSagaService creates a new mock instance.
func NewMockIExternalInspecaoEntradaSagaService(ctrl *gomock.Controller) *MockIExternalInspecaoEntradaSagaService {
	mock := &MockIExternalInspecaoEntradaSagaService{ctrl: ctrl}
	mock.recorder = &MockIExternalInspecaoEntradaSagaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExternalInspecaoEntradaSagaService) EXPECT() *MockIExternalInspecaoEntradaSagaServiceMockRecorder {
	return m.recorder
}

// BuscarSaga mocks base method.
func (m *MockIExternalInspecaoEntradaSagaService) BuscarSaga(arg0 string) (*dto.SagaInspecaoEntradaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSaga", arg0)
	ret0, _ := ret[0].(*dto.SagaInspecaoEntradaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSaga indicates an expected call of BuscarSaga.
func (mr *MockIExternalInspecaoEntradaSagaServiceMockRecorder) BuscarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSaga", reflect.TypeOf((*MockIExternalInspecaoEntradaSagaService)(nil).BuscarSaga), arg0)
}

// BuscarSagas mocks base method.
func (m *MockIExternalInspecaoEntradaSagaService) BuscarSagas(arg0, arg1 int, arg2 *dto.ProcessamentoInspecaoEntradaFilters, arg3 bool) (*dto.GetAllSagaInspecaoEntradaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSagas", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.GetAllSagaInspecaoEntradaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSagas indicates an expected call of BuscarSagas.
func (mr *MockIExternalInspecaoEntradaSagaServiceMockRecorder) BuscarSagas(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSagas", reflect.TypeOf((*MockIExternalInspecaoEntradaSagaService)(nil).BuscarSagas), arg0, arg1, arg2, arg3)
}

// PublicarSaga mocks base method.
func (m *MockIExternalInspecaoEntradaSagaService) PublicarSaga(arg0 interface{}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicarSaga", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicarSaga indicates an expected call of PublicarSaga.
func (mr *MockIExternalInspecaoEntradaSagaServiceMockRecorder) PublicarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicarSaga", reflect.TypeOf((*MockIExternalInspecaoEntradaSagaService)(nil).PublicarSaga), arg0)
}

// RemoverSaga mocks base method.
func (m *MockIExternalInspecaoEntradaSagaService) RemoverSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverSaga indicates an expected call of RemoverSaga.
func (mr *MockIExternalInspecaoEntradaSagaServiceMockRecorder) RemoverSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverSaga", reflect.TypeOf((*MockIExternalInspecaoEntradaSagaService)(nil).RemoverSaga), arg0)
}

// ReprocessarSaga mocks base method.
func (m *MockIExternalInspecaoEntradaSagaService) ReprocessarSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessarSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReprocessarSaga indicates an expected call of ReprocessarSaga.
func (mr *MockIExternalInspecaoEntradaSagaServiceMockRecorder) ReprocessarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessarSaga", reflect.TypeOf((*MockIExternalInspecaoEntradaSagaService)(nil).ReprocessarSaga), arg0)
}
