// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IImpressaoService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIImpressaoService is a mock of IImpressaoService interface.
type MockIImpressaoService struct {
	ctrl     *gomock.Controller
	recorder *MockIImpressaoServiceMockRecorder
}

// MockIImpressaoServiceMockRecorder is the mock recorder for MockIImpressaoService.
type MockIImpressaoServiceMockRecorder struct {
	mock *MockIImpressaoService
}

// NewMockIImpressaoService creates a new mock instance.
func NewMockIImpressaoService(ctrl *gomock.Controller) *MockIImpressaoService {
	mock := &MockIImpressaoService{ctrl: ctrl}
	mock.recorder = &MockIImpressaoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIImpressaoService) EXPECT() *MockIImpressaoServiceMockRecorder {
	return m.recorder
}

// ExportReportStimulsoft mocks base method.
func (m *MockIImpressaoService) ExportReportStimulsoft(arg0 interface{}, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportReportStimulsoft", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportReportStimulsoft indicates an expected call of ExportReportStimulsoft.
func (mr *MockIImpressaoServiceMockRecorder) ExportReportStimulsoft(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportReportStimulsoft", reflect.TypeOf((*MockIImpressaoService)(nil).ExportReportStimulsoft), arg0, arg1)
}
