// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: INotaFiscalService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockINotaFiscalService is a mock of INotaFiscalService interface.
type MockINotaFiscalService struct {
	ctrl     *gomock.Controller
	recorder *MockINotaFiscalServiceMockRecorder
}

// MockINotaFiscalServiceMockRecorder is the mock recorder for MockINotaFiscalService.
type MockINotaFiscalServiceMockRecorder struct {
	mock *MockINotaFiscalService
}

// NewMockINotaFiscalService creates a new mock instance.
func NewMockINotaFiscalService(ctrl *gomock.Controller) *MockINotaFiscalService {
	mock := &MockINotaFiscalService{ctrl: ctrl}
	mock.recorder = &MockINotaFiscalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotaFiscalService) EXPECT() *MockINotaFiscalServiceMockRecorder {
	return m.recorder
}

// BuscarNotasFiscais mocks base method.
func (m *MockINotaFiscalService) BuscarNotasFiscais(arg0 *models.BaseFilter, arg1 *dto.NotaFiscalFilters) (*dto.GetNotasFiscaisOutput, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarNotasFiscais", arg0, arg1)
	ret0, _ := ret[0].(*dto.GetNotasFiscaisOutput)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BuscarNotasFiscais indicates an expected call of BuscarNotasFiscais.
func (mr *MockINotaFiscalServiceMockRecorder) BuscarNotasFiscais(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarNotasFiscais", reflect.TypeOf((*MockINotaFiscalService)(nil).BuscarNotasFiscais), arg0, arg1)
}
