// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaItemRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/entities"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaItemRepository is a mock of IInspecaoEntradaItemRepository interface.
type MockIInspecaoEntradaItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaItemRepositoryMockRecorder
}

// MockIInspecaoEntradaItemRepositoryMockRecorder is the mock recorder for MockIInspecaoEntradaItemRepository.
type MockIInspecaoEntradaItemRepositoryMockRecorder struct {
	mock *MockIInspecaoEntradaItemRepository
}

// NewMockIInspecaoEntradaItemRepository creates a new mock instance.
func NewMockIInspecaoEntradaItemRepository(ctrl *gomock.Controller) *MockIInspecaoEntradaItemRepository {
	mock := &MockIInspecaoEntradaItemRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaItemRepository) EXPECT() *MockIInspecaoEntradaItemRepositoryMockRecorder {
	return m.recorder
}

// AtualizarInspecaoEntradaItens mocks base method.
func (m *MockIInspecaoEntradaItemRepository) AtualizarInspecaoEntradaItens(arg0 []*entities.InspecaoEntradaItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarInspecaoEntradaItens", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarInspecaoEntradaItens indicates an expected call of AtualizarInspecaoEntradaItens.
func (mr *MockIInspecaoEntradaItemRepositoryMockRecorder) AtualizarInspecaoEntradaItens(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarInspecaoEntradaItens", reflect.TypeOf((*MockIInspecaoEntradaItemRepository)(nil).AtualizarInspecaoEntradaItens), arg0)
}

// BuscarInspecaoEntradaItensEntitiesPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaItemRepository) BuscarInspecaoEntradaItensEntitiesPeloCodigo(arg0 int) ([]*entities.InspecaoEntradaItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaItensEntitiesPeloCodigo", arg0)
	ret0, _ := ret[0].([]*entities.InspecaoEntradaItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoEntradaItensEntitiesPeloCodigo indicates an expected call of BuscarInspecaoEntradaItensEntitiesPeloCodigo.
func (mr *MockIInspecaoEntradaItemRepositoryMockRecorder) BuscarInspecaoEntradaItensEntitiesPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaItensEntitiesPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaItemRepository)(nil).BuscarInspecaoEntradaItensEntitiesPeloCodigo), arg0)
}

// BuscarInspecaoEntradaItensPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaItemRepository) BuscarInspecaoEntradaItensPeloCodigo(arg0 string, arg1 int, arg2 *models.BaseFilter) ([]models.InspecaoEntradaItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaItensPeloCodigo", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.InspecaoEntradaItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoEntradaItensPeloCodigo indicates an expected call of BuscarInspecaoEntradaItensPeloCodigo.
func (mr *MockIInspecaoEntradaItemRepositoryMockRecorder) BuscarInspecaoEntradaItensPeloCodigo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaItemRepository)(nil).BuscarInspecaoEntradaItensPeloCodigo), arg0, arg1, arg2)
}

// BuscarQuantidadeInspecaoEntradaItensPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaItemRepository) BuscarQuantidadeInspecaoEntradaItensPeloCodigo(arg0 int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeInspecaoEntradaItensPeloCodigo", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeInspecaoEntradaItensPeloCodigo indicates an expected call of BuscarQuantidadeInspecaoEntradaItensPeloCodigo.
func (mr *MockIInspecaoEntradaItemRepositoryMockRecorder) BuscarQuantidadeInspecaoEntradaItensPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeInspecaoEntradaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaItemRepository)(nil).BuscarQuantidadeInspecaoEntradaItensPeloCodigo), arg0)
}

// CriarItensInspecao mocks base method.
func (m *MockIInspecaoEntradaItemRepository) CriarItensInspecao(arg0 []models.InspecaoEntradaItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CriarItensInspecao", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CriarItensInspecao indicates an expected call of CriarItensInspecao.
func (mr *MockIInspecaoEntradaItemRepositoryMockRecorder) CriarItensInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CriarItensInspecao", reflect.TypeOf((*MockIInspecaoEntradaItemRepository)(nil).CriarItensInspecao), arg0)
}

// RemoverInspecaoEntradaItensPeloCodigo mocks base method.
func (m *MockIInspecaoEntradaItemRepository) RemoverInspecaoEntradaItensPeloCodigo(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverInspecaoEntradaItensPeloCodigo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverInspecaoEntradaItensPeloCodigo indicates an expected call of RemoverInspecaoEntradaItensPeloCodigo.
func (mr *MockIInspecaoEntradaItemRepositoryMockRecorder) RemoverInspecaoEntradaItensPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverInspecaoEntradaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoEntradaItemRepository)(nil).RemoverInspecaoEntradaItensPeloCodigo), arg0)
}
