// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaPlanoAmostragemRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaPlanoAmostragemRepository is a mock of IInspecaoEntradaPlanoAmostragemRepository interface.
type MockIInspecaoEntradaPlanoAmostragemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder
}

// MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder is the mock recorder for MockIInspecaoEntradaPlanoAmostragemRepository.
type MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder struct {
	mock *MockIInspecaoEntradaPlanoAmostragemRepository
}

// NewMockIInspecaoEntradaPlanoAmostragemRepository creates a new mock instance.
func NewMockIInspecaoEntradaPlanoAmostragemRepository(ctrl *gomock.Controller) *MockIInspecaoEntradaPlanoAmostragemRepository {
	mock := &MockIInspecaoEntradaPlanoAmostragemRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaPlanoAmostragemRepository) EXPECT() *MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIInspecaoEntradaPlanoAmostragemRepository) Create(arg0 dto.PlanoAmostragemDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIInspecaoEntradaPlanoAmostragemRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIInspecaoEntradaPlanoAmostragemRepository) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIInspecaoEntradaPlanoAmostragemRepository)(nil).Delete), arg0)
}

// GetAll mocks base method.
func (m *MockIInspecaoEntradaPlanoAmostragemRepository) GetAll(arg0 *models.BaseFilter) (*dto.GetAllPlanoAmostragemDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].(*dto.GetAllPlanoAmostragemDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIInspecaoEntradaPlanoAmostragemRepository)(nil).GetAll), arg0)
}

// GetFaixaPlanoAmostragem mocks base method.
func (m *MockIInspecaoEntradaPlanoAmostragemRepository) GetFaixaPlanoAmostragem(arg0 float64) (*dto.PlanoAmostragemDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFaixaPlanoAmostragem", arg0)
	ret0, _ := ret[0].(*dto.PlanoAmostragemDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFaixaPlanoAmostragem indicates an expected call of GetFaixaPlanoAmostragem.
func (mr *MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder) GetFaixaPlanoAmostragem(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFaixaPlanoAmostragem", reflect.TypeOf((*MockIInspecaoEntradaPlanoAmostragemRepository)(nil).GetFaixaPlanoAmostragem), arg0)
}

// Update mocks base method.
func (m *MockIInspecaoEntradaPlanoAmostragemRepository) Update(arg0 dto.PlanoAmostragemDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIInspecaoEntradaPlanoAmostragemRepositoryMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIInspecaoEntradaPlanoAmostragemRepository)(nil).Update), arg0)
}
