// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaPedidoVendaLoteRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/entities"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIInspecaoEntradaPedidoVendaLoteRepository is a mock of IInspecaoEntradaPedidoVendaLoteRepository interface.
type MockIInspecaoEntradaPedidoVendaLoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder
}

// MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder is the mock recorder for MockIInspecaoEntradaPedidoVendaLoteRepository.
type MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder struct {
	mock *MockIInspecaoEntradaPedidoVendaLoteRepository
}

// NewMockIInspecaoEntradaPedidoVendaLoteRepository creates a new mock instance.
func NewMockIInspecaoEntradaPedidoVendaLoteRepository(ctrl *gomock.Controller) *MockIInspecaoEntradaPedidoVendaLoteRepository {
	mock := &MockIInspecaoEntradaPedidoVendaLoteRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaPedidoVendaLoteRepository) EXPECT() *MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder {
	return m.recorder
}

// BatchDelete mocks base method.
func (m *MockIInspecaoEntradaPedidoVendaLoteRepository) BatchDelete(arg0 []*uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder) BatchDelete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockIInspecaoEntradaPedidoVendaLoteRepository)(nil).BatchDelete), arg0)
}

// Create mocks base method.
func (m *MockIInspecaoEntradaPedidoVendaLoteRepository) Create(arg0 entities.InspecaoEntradaPedidoVendaLote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIInspecaoEntradaPedidoVendaLoteRepository)(nil).Create), arg0)
}

// GetAllByIdPedidoVenda mocks base method.
func (m *MockIInspecaoEntradaPedidoVendaLoteRepository) GetAllByIdPedidoVenda(arg0 []uuid.UUID) ([]*entities.InspecaoEntradaPedidoVendaLote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByIdPedidoVenda", arg0)
	ret0, _ := ret[0].([]*entities.InspecaoEntradaPedidoVendaLote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByIdPedidoVenda indicates an expected call of GetAllByIdPedidoVenda.
func (mr *MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder) GetAllByIdPedidoVenda(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByIdPedidoVenda", reflect.TypeOf((*MockIInspecaoEntradaPedidoVendaLoteRepository)(nil).GetAllByIdPedidoVenda), arg0)
}

// GetTotalCount mocks base method.
func (m *MockIInspecaoEntradaPedidoVendaLoteRepository) GetTotalCount(arg0 uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalCount indicates an expected call of GetTotalCount.
func (mr *MockIInspecaoEntradaPedidoVendaLoteRepositoryMockRecorder) GetTotalCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalCount", reflect.TypeOf((*MockIInspecaoEntradaPedidoVendaLoteRepository)(nil).GetTotalCount), arg0)
}
