// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IPlanosInspecaoRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIPlanosInspecaoRepository is a mock of IPlanosInspecaoRepository interface.
type MockIPlanosInspecaoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPlanosInspecaoRepositoryMockRecorder
}

// MockIPlanosInspecaoRepositoryMockRecorder is the mock recorder for MockIPlanosInspecaoRepository.
type MockIPlanosInspecaoRepositoryMockRecorder struct {
	mock *MockIPlanosInspecaoRepository
}

// NewMockIPlanosInspecaoRepository creates a new mock instance.
func NewMockIPlanosInspecaoRepository(ctrl *gomock.Controller) *MockIPlanosInspecaoRepository {
	mock := &MockIPlanosInspecaoRepository{ctrl: ctrl}
	mock.recorder = &MockIPlanosInspecaoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlanosInspecaoRepository) EXPECT() *MockIPlanosInspecaoRepositoryMockRecorder {
	return m.recorder
}

// BuscarPlanosNovaInspecao mocks base method.
func (m *MockIPlanosInspecaoRepository) BuscarPlanosNovaInspecao(arg0, arg1 string, arg2 *models.BaseFilter) ([]models.PlanoInspecao, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarPlanosNovaInspecao", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.PlanoInspecao)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarPlanosNovaInspecao indicates an expected call of BuscarPlanosNovaInspecao.
func (mr *MockIPlanosInspecaoRepositoryMockRecorder) BuscarPlanosNovaInspecao(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarPlanosNovaInspecao", reflect.TypeOf((*MockIPlanosInspecaoRepository)(nil).BuscarPlanosNovaInspecao), arg0, arg1, arg2)
}

// BuscarQuantidadePlanosNovaInspecao mocks base method.
func (m *MockIPlanosInspecaoRepository) BuscarQuantidadePlanosNovaInspecao(arg0, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadePlanosNovaInspecao", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadePlanosNovaInspecao indicates an expected call of BuscarQuantidadePlanosNovaInspecao.
func (mr *MockIPlanosInspecaoRepositoryMockRecorder) BuscarQuantidadePlanosNovaInspecao(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadePlanosNovaInspecao", reflect.TypeOf((*MockIPlanosInspecaoRepository)(nil).BuscarQuantidadePlanosNovaInspecao), arg0, arg1)
}

// BuscarTodosPlanosNotaFiscalProduto mocks base method.
func (m *MockIPlanosInspecaoRepository) BuscarTodosPlanosNotaFiscalProduto(arg0, arg1 string) ([]models.PlanoInspecao, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarTodosPlanosNotaFiscalProduto", arg0, arg1)
	ret0, _ := ret[0].([]models.PlanoInspecao)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarTodosPlanosNotaFiscalProduto indicates an expected call of BuscarTodosPlanosNotaFiscalProduto.
func (mr *MockIPlanosInspecaoRepositoryMockRecorder) BuscarTodosPlanosNotaFiscalProduto(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarTodosPlanosNotaFiscalProduto", reflect.TypeOf((*MockIPlanosInspecaoRepository)(nil).BuscarTodosPlanosNotaFiscalProduto), arg0, arg1)
}
