// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaHistoricoService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaHistoricoService is a mock of IInspecaoEntradaHistoricoService interface.
type MockIInspecaoEntradaHistoricoService struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaHistoricoServiceMockRecorder
}

// MockIInspecaoEntradaHistoricoServiceMockRecorder is the mock recorder for MockIInspecaoEntradaHistoricoService.
type MockIInspecaoEntradaHistoricoServiceMockRecorder struct {
	mock *MockIInspecaoEntradaHistoricoService
}

// NewMockIInspecaoEntradaHistoricoService creates a new mock instance.
func NewMockIInspecaoEntradaHistoricoService(ctrl *gomock.Controller) *MockIInspecaoEntradaHistoricoService {
	mock := &MockIInspecaoEntradaHistoricoService{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaHistoricoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaHistoricoService) EXPECT() *MockIInspecaoEntradaHistoricoServiceMockRecorder {
	return m.recorder
}

// GetAllInspecaoEntradaHistoricoCabecalho mocks base method.
func (m *MockIInspecaoEntradaHistoricoService) GetAllInspecaoEntradaHistoricoCabecalho(arg0 *models.BaseFilter, arg1 *dto.InspecaoEntradaHistoricoCabecalhoFilters) (*dto.GetNotasFiscaisOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInspecaoEntradaHistoricoCabecalho", arg0, arg1)
	ret0, _ := ret[0].(*dto.GetNotasFiscaisOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInspecaoEntradaHistoricoCabecalho indicates an expected call of GetAllInspecaoEntradaHistoricoCabecalho.
func (mr *MockIInspecaoEntradaHistoricoServiceMockRecorder) GetAllInspecaoEntradaHistoricoCabecalho(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInspecaoEntradaHistoricoCabecalho", reflect.TypeOf((*MockIInspecaoEntradaHistoricoService)(nil).GetAllInspecaoEntradaHistoricoCabecalho), arg0, arg1)
}

// GetAllInspecaoEntradaHistoricoItems mocks base method.
func (m *MockIInspecaoEntradaHistoricoService) GetAllInspecaoEntradaHistoricoItems(arg0 int, arg1 string, arg2 *models.BaseFilter, arg3 *dto.InspecaoEntradaHistoricoCabecalhoFilters) (*dto.GetAllInspecaoEntradaHistoricoItemsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInspecaoEntradaHistoricoItems", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.GetAllInspecaoEntradaHistoricoItemsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInspecaoEntradaHistoricoItems indicates an expected call of GetAllInspecaoEntradaHistoricoItems.
func (mr *MockIInspecaoEntradaHistoricoServiceMockRecorder) GetAllInspecaoEntradaHistoricoItems(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInspecaoEntradaHistoricoItems", reflect.TypeOf((*MockIInspecaoEntradaHistoricoService)(nil).GetAllInspecaoEntradaHistoricoItems), arg0, arg1, arg2, arg3)
}
