// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IInspecaoEntradaExecutadoWebRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoEntradaExecutadoWebRepository is a mock of IInspecaoEntradaExecutadoWebRepository interface.
type MockIInspecaoEntradaExecutadoWebRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder
}

// MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder is the mock recorder for MockIInspecaoEntradaExecutadoWebRepository.
type MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder struct {
	mock *MockIInspecaoEntradaExecutadoWebRepository
}

// NewMockIInspecaoEntradaExecutadoWebRepository creates a new mock instance.
func NewMockIInspecaoEntradaExecutadoWebRepository(ctrl *gomock.Controller) *MockIInspecaoEntradaExecutadoWebRepository {
	mock := &MockIInspecaoEntradaExecutadoWebRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoEntradaExecutadoWebRepository) EXPECT() *MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder {
	return m.recorder
}

// BuscarInspecaoEntradaExecutadoWeb mocks base method.
func (m *MockIInspecaoEntradaExecutadoWebRepository) BuscarInspecaoEntradaExecutadoWeb(arg0 int) (*entities.InspecaoEntradaExecutadoWeb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoEntradaExecutadoWeb", arg0)
	ret0, _ := ret[0].(*entities.InspecaoEntradaExecutadoWeb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoEntradaExecutadoWeb indicates an expected call of BuscarInspecaoEntradaExecutadoWeb.
func (mr *MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder) BuscarInspecaoEntradaExecutadoWeb(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoEntradaExecutadoWeb", reflect.TypeOf((*MockIInspecaoEntradaExecutadoWebRepository)(nil).BuscarInspecaoEntradaExecutadoWeb), arg0)
}

// InserirInspecaoEntradaExecutadoWeb mocks base method.
func (m *MockIInspecaoEntradaExecutadoWebRepository) InserirInspecaoEntradaExecutadoWeb(arg0 *entities.InspecaoEntradaExecutadoWeb) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InserirInspecaoEntradaExecutadoWeb", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InserirInspecaoEntradaExecutadoWeb indicates an expected call of InserirInspecaoEntradaExecutadoWeb.
func (mr *MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder) InserirInspecaoEntradaExecutadoWeb(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InserirInspecaoEntradaExecutadoWeb", reflect.TypeOf((*MockIInspecaoEntradaExecutadoWebRepository)(nil).InserirInspecaoEntradaExecutadoWeb), arg0)
}

// RemoverSaga mocks base method.
func (m *MockIInspecaoEntradaExecutadoWebRepository) RemoverSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverSaga indicates an expected call of RemoverSaga.
func (mr *MockIInspecaoEntradaExecutadoWebRepositoryMockRecorder) RemoverSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverSaga", reflect.TypeOf((*MockIInspecaoEntradaExecutadoWebRepository)(nil).RemoverSaga), arg0)
}
