// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/interfaces (interfaces: IProdutoService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoEntrada/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIProdutoService is a mock of IProdutoService interface.
type MockIProdutoService struct {
	ctrl     *gomock.Controller
	recorder *MockIProdutoServiceMockRecorder
}

// MockIProdutoServiceMockRecorder is the mock recorder for MockIProdutoService.
type MockIProdutoServiceMockRecorder struct {
	mock *MockIProdutoService
}

// NewMockIProdutoService creates a new mock instance.
func NewMockIProdutoService(ctrl *gomock.Controller) *MockIProdutoService {
	mock := &MockIProdutoService{ctrl: ctrl}
	mock.recorder = &MockIProdutoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProdutoService) EXPECT() *MockIProdutoServiceMockRecorder {
	return m.recorder
}

// BuscarProduto mocks base method.
func (m *MockIProdutoService) BuscarProduto(arg0 string) (*dto.ProdutoOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProduto", arg0)
	ret0, _ := ret[0].(*dto.ProdutoOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProduto indicates an expected call of BuscarProduto.
func (mr *MockIProdutoServiceMockRecorder) BuscarProduto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProduto", reflect.TypeOf((*MockIProdutoService)(nil).BuscarProduto), arg0)
}

// BuscarProdutos mocks base method.
func (m *MockIProdutoService) BuscarProdutos(arg0 *models.BaseFilter) (*dto.GetProdutos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutos", arg0)
	ret0, _ := ret[0].(*dto.GetProdutos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutos indicates an expected call of BuscarProdutos.
func (mr *MockIProdutoServiceMockRecorder) BuscarProdutos(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutos", reflect.TypeOf((*MockIProdutoService)(nil).BuscarProdutos), arg0)
}
