package queries

const BuscarEstoqueLocalValoresPorProduto = `
SELECT
HISREAL.R_E_C_N_O_ AS Recno,
HISREAL.QTRECEB AS Quantidade,
HISREAL.PESO_BRUTO AS PesoBruto,
HISREAL.PESO_LIQUIDO AS PesoLiquido,
HISREAL.DATA_VALIDADE AS DataValidade,
HISREAL.DATA_FABRICACAO AS DataFabricacao,
ESTOQUE_EMPRESA.VALPAGO AS ValorPago
FROM HISREAL
INNER JOIN ESTOQUE_EMPRESA ON ESTOQUE_EMPRESA.CODIGO = HISREAL.CODIGO AND ESTOQUE_EMPRESA.EMPRESA_RECNO = HISREAL.EMPRESA_RECNO
WHERE HISREAL.CODIGO = @` + NamedProdutoCodigo + ` AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND HISREAL.LOTE = @` + NamedLote + ` AND HISREAL.ODF = @` + NamedOdf + ` AND HISREAL.LOCAL_DESTINO = @` + NamedLocal

const BuscarPacotes = `
SELECT
NRO_PACOTE AS NumeroPacote,
QTDE_ESTOQUE AS Quantidade
FROM ESTOQUE_PACOTE
WHERE RECNO_ESTOQUE_LOCAL = @` + NamedLocal

const BuscarSeries = `
SELECT
R_E_C_N_O_ AS RecnoSerie,
SERIE AS Serie
FROM ESTOQUE_SERIE_PRODUCAO
WHERE RECNO_ESTOQUE_LOCAL = @` + NamedLocal
