package queries

const BuscarEstoqueLocalValoresPorProduto = `
SELECT
ESTOQUE_LOCAL.R_E_C_N_O_ AS Recno,
ESTOQUE_LOCAL.QTDE AS Quantidade,
ESTOQUE_LOCAL.PESO_BRUTO AS PesoBruto,
ESTOQUE_LOCAL.PESO_LIQUIDO AS PesoLiquido,
ESTOQUE_LOCAL.VALIDADE AS DataValidade,
ESTOQUE_LOCAL.DTFABRICACAO AS DataFabricacao,
ESTOQUE_EMPRESA.VALPAGO AS ValorPago
FROM ESTOQUE_LOCAL
INNER JOIN ESTOQUE_EMPRESA ON ESTOQUE_EMPRESA.CODIGO = ESTOQUE_LOCAL.CODIGO AND ESTOQUE_EMPRESA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
WHERE ESTOQUE_LOCAL.CODIGO = @` + NamedProdutoCodigo + ` AND ESTOQUE_LOCAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND ESTOQUE_LOCAL.LOTE = @` + NamedLote + ` AND ESTOQUE_LOCAL.ODF = @` + NamedOdf + ` AND ESTOQUE_LOCAL.LOCAL = @` + NamedLocal

const BuscarPacotes = `
SELECT
NRO_PACOTE AS NumeroPacote,
QTDE_ESTOQUE AS Quantidade
FROM ESTOQUE_PACOTE
WHERE RECNO_ESTOQUE_LOCAL = @` + NamedLocal

const BuscarSeries = `
SELECT
R_E_C_N_O_ AS RecnoSerie,
SERIE AS Serie
FROM ESTOQUE_SERIE_PRODUCAO
WHERE RECNO_ESTOQUE_LOCAL = @` + NamedLocal
