package queries

const GetPlanosNovaInspecao = `
SELECT
	CASE WHEN PLANOINSP_PROCESSO.DESCRICAO IS NULL THEN QA_PLANO_INS_SAIDA.DESC1
	ELSE PLANOINSP_PROCESSO.DESCRICAO
	END AS Descricao,
	QA_PLANO_INS_SAIDA.ID AS Id,
	QA_PLANO_INS_SAIDA.R_E_C_N_O_ AS LegacyId,
	QA_PLANO_INS_SAIDA.PLANO AS Plano,
	QA_PLANO_INS_SAIDA.SEQUENCIA AS Sequencia,
	QA_PLANO_INS_SAIDA.METODO AS Metodo,
	CASE WHEN PLANOINSP_PROCESSO.QTD_INSP_MAXIMA IS NOT NULL THEN PLANOINSP_PROCESSO.QTD_INSP_MAXIMA
	ELSE QA_PLANO_INS_SAIDA.MAIORVALOR
	END AS MaiorValorBase,
	CASE WHEN PLANOINSP_PROCESSO.QTD_INSP_MINIMA IS NOT NULL THEN PLANOINSP_PROCESSO.QTD_INSP_MINIMA
	ELSE QA_PLANO_INS_SAIDA.MENORVALOR
	END AS MenorValorBase
FROM QA_PLANO_INS_SAIDA
LEFT JOIN PLANOINSP_PROCESSO ON QA_PLANO_INS_SAIDA.R_E_C_N_O_ = PLANOINSP_PROCESSO.RECNO_PLANOINSP
AND PLANOINSP_PROCESSO.RECNO_PROCESSO = @` + NamedRecnoProcesso + " \n" +
	`WHERE QA_PLANO_INS_SAIDA.PLANO = @` + NamedPlano + " \n" +
	`ORDER BY QA_PLANO_INS_SAIDA.SEQUENCIA` + " \n"

const GetPlanosNovaInspecaoPagination = "OFFSET @" + NamedSkip + " ROWS \n" +
	"FETCH NEXT @" + NamedPageSize + " ROWS ONLY"

const GetCountPlanosNovaInspecao = "SELECT COUNT(*) \n" +
	"FROM QA_PLANO_INS_SAIDA \n" +
	"LEFT JOIN PLANOINSP_PROCESSO ON QA_PLANO_INS_SAIDA.R_E_C_N_O_ = PLANOINSP_PROCESSO.RECNO_PLANOINSP \n" +
	"AND PLANOINSP_PROCESSO.RECNO_PROCESSO = @" + NamedRecnoProcesso + " \n" +
	"WHERE QA_PLANO_INS_SAIDA.PLANO = @" + NamedPlano

const GetInspecoesSelect = `
	CAST(QA_INSPECAO_SAIDA.ID AS VARCHAR(36)) AS Id,
	QA_INSPECAO_SAIDA.R_E_C_N_O_ AS Recno,
	QA_INSPECAO_SAIDA.CODINSP AS CodigoInspecao,
	QA_INSPECAO_SAIDA.NUMODF AS Odf,
	COALESCE(PPEDLISE_ORDEM_FABRICACAO.NUMODF, QA_INSPECAO_SAIDA.NUMODF) AS OdfApontada,
	QA_INSPECAO_SAIDA.CLIENTE AS Cliente,
	QA_INSPECAO_SAIDA.NUMPED AS NumeroPedido,
	QA_INSPECAO_SAIDA.ISO_TS AS IsoTs,
	QA_INSPECAO_SAIDA.INSPECIONADO AS Inspecionado,
	QA_INSPECAO_SAIDA.DATAINSP AS DataInspecao,
	QA_INSPECAO_SAIDA.TIPOINSP AS TipoInspecao,
	QA_INSPECAO_SAIDA.INSPETOR AS Inspetor,
	QA_INSPECAO_SAIDA.RESULTADO AS Resultado,
	QA_INSPECAO_SAIDA.LOTE AS Lote,
	QA_INSPECAO_SAIDA.QTD_INSPECAO AS QtdInspecao,
	QA_INSPECAO_SAIDA.QTD_LOTE AS QtdLote,
	QA_INSPECAO_SAIDA.QTD_ACEITO AS QuantidadeAceita,
	QA_INSPECAO_SAIDA.QTD_RETRABALHO AS QuantidadeRetrabalhada,
	QA_INSPECAO_SAIDA.QTD_APROVADO AS QuantidadeAprovada,
	QA_INSPECAO_SAIDA.QTD_REJEITADO AS QuantidadeReprovada,
	QA_INSPECAO_SAIDA.EMPRESA_RECNO AS IdEmpresa,
	QA_INSPECAO_SAIDA.CODIGO_PRODUTO AS CodigoProduto
`

const GetInspecaoItensSelect = "CAST(QA_ITEM_INSPECAO_SAIDA.ID AS VARCHAR(36)) AS Id, QA_ITEM_INSPECAO_SAIDA.RECNO_PLANO_INSPECAO AS LegacyIdPlanoInspecao, QA_ITEM_INSPECAO_SAIDA.PLANO AS Plano," +
	"QA_ITEM_INSPECAO_SAIDA.OBSERVACAO AS Observacao, QA_ITEM_INSPECAO_SAIDA.NUMODF AS Odf, QA_ITEM_INSPECAO_SAIDA.DESCRICAO AS Descricao, QA_ITEM_INSPECAO_SAIDA.METODO AS Metodo," +
	"QA_ITEM_INSPECAO_SAIDA.SEQUENCIA AS Sequencia, QA_ITEM_INSPECAO_SAIDA.RESULTADO AS Resultado," +
	"QA_ITEM_INSPECAO_SAIDA.MAIORVALOR AS MaiorValor, QA_ITEM_INSPECAO_SAIDA.MENORVALOR AS MenorValor," +
	"QA_ITEM_INSPECAO_SAIDA.CODINSP AS CodigoInspecao, QA_ITEM_INSPECAO_SAIDA.EMPRESA_RECNO AS IdEmpresa"

const GetInspecaoItensJoinSelect = GetInspecaoItensSelect +
	", QA_PLANO_INS_SAIDA.MAIORVALOR AS MaiorValorBase, QA_PLANO_INS_SAIDA.MENORVALOR AS MenorValorBase"

const GetInspecaoItensJoin = "INNER JOIN QA_PLANO_INS_SAIDA\n" +
	"ON QA_ITEM_INSPECAO_SAIDA.RECNO_PLANO_INSPECAO = QA_PLANO_INS_SAIDA.R_E_C_N_O_"

const GetInspecaoSaidaCodigo = `
SELECT
	QA_INSPECAO_SAIDA.R_E_C_N_O_ AS Recno,
	QA_INSPECAO_SAIDA.CODINSP AS CodigoInspecao,
	QA_INSPECAO_SAIDA.CLIENTE AS Cliente,
	QA_INSPECAO_SAIDA.NUMPED AS Pedido,
	QA_INSPECAO_SAIDA.NUMODF AS Odf,
	COALESCE(PPEDLISE_ORDEM_FABRICACAO.NUMODF, QA_INSPECAO_SAIDA.NUMODF) AS OdfApontada,
	QA_INSPECAO_SAIDA.DATAINSP AS DataInspecao,
	QA_INSPECAO_SAIDA.INSPETOR AS Inspetor,
	QA_INSPECAO_SAIDA.QTD_LOTE AS QtdLote,
	QA_INSPECAO_SAIDA.QTD_INSPECAO AS QtdInspecao,
	QA_INSPECAO_SAIDA.EMPRESA_RECNO AS IdEmpresa,
	QA_INSPECAO_SAIDA.RESULTADO AS Resultado,
	QA_INSPECAO_SAIDA.QTD_ACEITO AS QuantidadeAceita,
	QA_INSPECAO_SAIDA.QTD_RETRABALHO AS QuantidadeRetrabalhada,
	QA_INSPECAO_SAIDA.QTD_APROVADO AS QuantidadeAprovada,
	QA_INSPECAO_SAIDA.QTD_REJEITADO AS QuantidadeReprovada,
	QA_INSPECAO_SAIDA.CODIGO_PRODUTO AS CodigoProduto,
	QA_INSPECAO_SAIDA.LOTE AS Lote,
	CASE WHEN PPEDLISE.NUMPED IS NOT NULL THEN
		PPEDLISE.NUMPED ELSE
		FECHA.NUMPED
	END AS NumeroPedido,
	CASE WHEN PPEDLISE.QTPEDI IS NOT NULL THEN
		CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > PPEDLISE.QTPEDI THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE PPEDLISE.QTPEDI END
	ELSE
		CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > FECHA.QTPEDE THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE FECHA.QTPEDE END
	END AS QuantidadeOrdem
FROM QA_INSPECAO_SAIDA
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO AND
	PPEDLISE.NUMODF = QA_INSPECAO_SAIDA.NUMODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO AND
	FECHA.NODF = QA_INSPECAO_SAIDA.NUMODF
LEFT JOIN ESTOQUE_PEDIDO_VENDA ON
	(ESTOQUE_PEDIDO_VENDA.NUMPED = PPEDLISE.NUMPED OR ESTOQUE_PEDIDO_VENDA.NUMPED = FECHA.NUMPED) AND
	ESTOQUE_PEDIDO_VENDA.NUMODF = QA_INSPECAO_SAIDA.NUMODF AND ESTOQUE_PEDIDO_VENDA.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO AND
	ESTOQUE_PEDIDO_VENDA.CODIGO = QA_INSPECAO_SAIDA.CODIGO_PRODUTO
LEFT JOIN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL ON
	ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_PEDIDO_VENDA = ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = QA_INSPECAO_SAIDA.NUMODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = QA_INSPECAO_SAIDA.CODIGO_PRODUTO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO
WHERE QA_INSPECAO_SAIDA.CODINSP = @` + NamedCodigoInspecaoSaida

const GetInspecoesJoin = `
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = QA_INSPECAO_SAIDA.NUMODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = QA_INSPECAO_SAIDA.CODIGO_PRODUTO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO`

const GetNotasRelatorio = `
SELECT 
NotaFiscal.NOTA AS Nota, 
NotaFiscal.NUMERO AS NumeroNota, 
NotaFiscal.CLI AS ClienteCodigo, 
NotaFiscal.RAZAO AS ClienteRazaoSocial,
ItemLote.QTDE AS QuantidadeLote
FROM HISLOTE_LOCAL AS ItemLote
INNER JOIN ITENNOTA AS ItemNota ON ItemLote.RECNO_ITENNOTA = ItemNota.R_E_C_N_O_
INNER JOIN NOTAFISC AS NotaFiscal ON ItemNota.NOTA = NotaFiscal.NOTA
WHERE ItemLote.LOTE = @` + NamedLote + `
AND ItemLote.CODIGO = @` + NamedProdutoCodigo + `
AND NotaFiscal.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@` + NamedAdvancedFilter + `
ORDER BY @` + NamedSorting + `
OFFSET @` + NamedSkip + ` ROWS
FETCH NEXT @` + NamedPageSize + ` ROWS ONLY
`

const GetNotasRelatorioCount = `
SELECT 
COUNT(NotaFiscal.NOTA)
FROM HISLOTE_LOCAL AS ItemLote
INNER JOIN ITENNOTA AS ItemNota ON ItemLote.RECNO_ITENNOTA = ItemNota.R_E_C_N_O_
INNER JOIN NOTAFISC AS NotaFiscal ON ItemNota.NOTA = NotaFiscal.NOTA
WHERE ItemLote.LOTE = @` + NamedLote + `
AND ItemLote.CODIGO = @` + NamedProdutoCodigo + `
AND NotaFiscal.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@` + NamedAdvancedFilter + `
`
