package queries

const GetCountInspecaoSaidaCabecalhoHistoricoInspecao = `
SELECT
COUNT(DISTINCT InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA)
FROM QA_INSPECAO_SAIDA
INNER JOIN QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO = QA_INSPECAO_SAIDA.R_E_C_N_O_
INNER JOIN HISREAL AS HISREAL_INSPECAO ON HISREAL_INSPECAO.R_E_C_N_O_ = QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
INNER JOIN LOCAIS ON LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON QA_INSPECAO_SAIDA.CODIGO_PRODUTO = ESTOQUE.CODIGO
INNER JOIN InspecaoSaidaExecutadoWeb ON InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA = QA_INSPECAO_SAIDA.R_E_C_N_O_
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND
	PPEDLISE.NUMODF = QA_INSPECAO_SAIDA.NUMODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND
	FECHA.NODF = QA_INSPECAO_SAIDA.NUMODF
LEFT JOIN ENGENHARIA_ROTEIRO_PROCESSO ON
	ENGENHARIA_ROTEIRO_PROCESSO.R_E_C_N_O_ = HISREAL_INSPECAO.RECNO_ENGENHARIA_ROTEIRO_PROCESSO
INNER JOIN PROCESSO ON
	PROCESSO.NUMPEC = QA_INSPECAO_SAIDA.CODIGO_PRODUTO AND
	(PROCESSO.REVISAO = PPEDLISE.REVISAO OR PROCESSO.REVISAO = FECHA.REVISAO OR ENGENHARIA_ROTEIRO_PROCESSO.RECNO_PROCESSO = PROCESSO.R_E_C_N_O_)
INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO
    ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = QA_INSPECAO_SAIDA.NUMODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = QA_INSPECAO_SAIDA.CODIGO_PRODUTO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@JoinFilters
WHERE Estorno = 0 AND INSPECIONADO = 'S' AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@AdvancedFilter
@CommonFilters
`

const GetAllInspecaoSaidaCabecalhoHistoricoInspecao = `
WITH BaseFiltrada AS (
    SELECT 
        Q.R_E_C_N_O_,
        Q.NUMODF,
        Q.CLIENTE,
        Q.NUMPED,
        Q.CODIGO_PRODUTO,
        Q.QTD_LOTE,
        Q.QTD_INSPECAO,
        Q.LOTE,
        Q.CODINSP
    FROM QA_INSPECAO_SAIDA Q
    INNER JOIN InspecaoSaidaExecutadoWeb W
        ON W.RECNO_INSPECAO_SAIDA = Q.R_E_C_N_O_
       AND W.Estorno = 0
    WHERE Q.INSPECIONADO = 'S'
      AND Q.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
	  AND Q.QTD_INSPECAO > 0
), DadosCompletos AS (
    SELECT 
        BF.CLIENTE AS Cliente,
        BF.NUMPED AS NumeroPedido,
        BF.NUMODF AS OrdemFabricacao,
        COALESCE(PPED_ORDEM.NUMODF, BF.NUMODF) AS OdfApontada,
        ESTOQUE.CODIGO AS CodigoProduto,
        ESTOQUE.DESCRI AS DescricaoProduto,
        BF.QTD_LOTE AS QuantidadeLote,
        BF.QTD_INSPECAO AS QuantidadeInspecao,
        BF.LOTE AS Lote,
        PROCESSO.PLANO_INSP AS Plano,
        QA_PLANO_INS_SAIDA_CABECALHO.DESCRICAO AS DescricaoPlano,
        PPEDLISE.DTNEGO AS DataNegociado,
        BF.CODINSP AS CodigoInspecao,
        CASE 
            WHEN PPEDLISE.REVISAO IS NOT NULL THEN PPEDLISE.REVISAO 
            ELSE FECHA.REVISAO
        END AS Revisao
    FROM BaseFiltrada BF
    INNER JOIN ESTOQUE ON BF.CODIGO_PRODUTO = ESTOQUE.CODIGO
    LEFT JOIN PPEDLISE 
        ON PPEDLISE.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND PPEDLISE.NUMODF = BF.NUMODF
    LEFT JOIN FECHA 
        ON FECHA.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND FECHA.NODF = BF.NUMODF
    INNER JOIN PROCESSO 
        ON PROCESSO.NUMPEC = BF.CODIGO_PRODUTO
       AND (
            PROCESSO.REVISAO = PPEDLISE.REVISAO
            OR PROCESSO.REVISAO = FECHA.REVISAO
            OR EXISTS (
                SELECT 1 FROM ENGENHARIA_ROTEIRO_PROCESSO ERP
                WHERE ERP.R_E_C_N_O_ IN (
                    SELECT HISREAL.RECNO_ENGENHARIA_ROTEIRO_PROCESSO
                    FROM QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO HIS
                    INNER JOIN HISREAL ON HISREAL.R_E_C_N_O_ = HIS.RECNO_HISREAL
                    WHERE HIS.RECNO_INSPECAO = BF.R_E_C_N_O_
                )
                AND ERP.RECNO_PROCESSO = PROCESSO.R_E_C_N_O_
            )
        )
    INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO
        ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
    LEFT JOIN PCP_ODF_PEDIDO 
        ON PCP_ODF_PEDIDO.ODFPED = BF.NUMODF
       AND PCP_ODF_PEDIDO.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
    LEFT JOIN PPEDLISE AS PPED_ORDEM 
        ON PPED_ORDEM.NUMODF = PCP_ODF_PEDIDO.NUMODF
       AND PPED_ORDEM.CODPCA = BF.CODIGO_PRODUTO
       AND PPED_ORDEM.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
	@JoinFilters
), DadosUnicos AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY 
                Cliente, NumeroPedido, OrdemFabricacao, CodigoProduto, QuantidadeLote, QuantidadeInspecao, Lote, CodigoInspecao
            ORDER BY OrdemFabricacao
        ) AS rn
    FROM DadosCompletos
)
SELECT *
FROM DadosUnicos
WHERE rn = 1
@AdvancedFilter
@CommonFilters
`

const GetInspecaoSaidaCabecalhoHistoricoInspecaoPagination = `
@Sorting
OFFSET @Skip ROWS
FETCH NEXT @PageSize ROWS ONLY
`

const GetCountInspecaoSaidaItensHistoricoInspecao = `
SELECT
COUNT(DISTINCT InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA)
FROM QA_INSPECAO_SAIDA
INNER JOIN QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO = QA_INSPECAO_SAIDA.R_E_C_N_O_
INNER JOIN HISREAL AS HISREAL_INSPECAO ON HISREAL_INSPECAO.R_E_C_N_O_ = QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
INNER JOIN LOCAIS ON LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON HISREAL_INSPECAO.CODIGO = ESTOQUE.CODIGO
INNER JOIN InspecaoSaidaExecutadoWeb ON InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA = QA_INSPECAO_SAIDA.R_E_C_N_O_
LEFT JOIN HISREAL ON
	HISREAL.LOTE = HISREAL_INSPECAO.LOTE AND HISREAL.CODIGO = HISREAL_INSPECAO.CODIGO AND HISREAL.LOCAL_DESTINO = LOCAIS.CODIGO AND
	HISREAL.FORMA = 'E' AND HISREAL.ESTORNADO_APT_PRODUCAO = 'N' AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = QA_INSPECAO_SAIDA.NUMODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = QA_INSPECAO_SAIDA.CODIGO_PRODUTO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@JoinFilters
WHERE Estorno = 0 AND LOCAIS.CODIGO <> HISREAL_INSPECAO.LOCAL_DESTINO AND INSPECIONADO = 'S' AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND QA_INSPECAO_SAIDA.NUMODF = @` + NamedOdf + `
AND QA_INSPECAO_SAIDA.CODINSP = @` + NamedCodigoInspecaoSaida + `
@AdvancedFilter`

const GetAllInspecaoSaidaItensHistoricoInspecao = `
SELECT DISTINCT
    CAST(QA_INSPECAO_SAIDA.Id AS VARCHAR(36)) as IdInspecao,
	QA_INSPECAO_SAIDA.CODINSP AS CodigoInspecao,
	QA_INSPECAO_SAIDA.R_E_C_N_O_ AS RecnoInspecao,
	QA_INSPECAO_SAIDA.NUMODF AS OrdemFabricacao,
	COALESCE(PPEDLISE_ORDEM_FABRICACAO.NUMODF, QA_INSPECAO_SAIDA.NUMODF) AS OdfApontada,
	ESTOQUE.CODIGO AS CodigoProduto,
	ESTOQUE.DESCRI AS DescricaoProduto,
	QA_INSPECAO_SAIDA.QTD_INSPECAO AS QuantidadeInspecao,
	QA_INSPECAO_SAIDA.TIPOINSP AS TipoInspecao,
	QA_INSPECAO_SAIDA.DATAINSP AS DataInspecao,
	QA_INSPECAO_SAIDA.INSPETOR AS Inspetor,
	QA_INSPECAO_SAIDA.RESULTADO AS Resultado,
	QA_INSPECAO_SAIDA.QTD_RETRABALHO AS QuantidadeRetrabalhada,
	QA_INSPECAO_SAIDA.QTD_APROVADO AS QuantidadeAprovada,
	QA_INSPECAO_SAIDA.QTD_REJEITADO AS QuantidadeReprovada,
	QA_INSPECAO_SAIDA.CLIENTE AS Cliente,
    QA_INSPECAO_SAIDA.NUMPED AS NumeroPedido,
    InspecaoSaidaExecutadoWeb.ID_RNC AS IdRnc,
	InspecaoSaidaExecutadoWeb.CODIGO_RNC AS CodigoRnc
FROM QA_INSPECAO_SAIDA
INNER JOIN QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO = QA_INSPECAO_SAIDA.R_E_C_N_O_
INNER JOIN HISREAL AS HISREAL_INSPECAO ON HISREAL_INSPECAO.R_E_C_N_O_ = QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
INNER JOIN LOCAIS ON LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON HISREAL_INSPECAO.CODIGO = ESTOQUE.CODIGO
INNER JOIN InspecaoSaidaExecutadoWeb ON InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA = QA_INSPECAO_SAIDA.R_E_C_N_O_
LEFT JOIN HISREAL ON
	HISREAL.LOTE = HISREAL_INSPECAO.LOTE AND HISREAL.CODIGO = HISREAL_INSPECAO.CODIGO AND HISREAL.LOCAL_DESTINO = LOCAIS.CODIGO AND
	HISREAL.FORMA = 'E' AND HISREAL.ESTORNADO_APT_PRODUCAO = 'N' AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = QA_INSPECAO_SAIDA.NUMODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = QA_INSPECAO_SAIDA.CODIGO_PRODUTO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@JoinFilters
WHERE Estorno = 0 AND LOCAIS.CODIGO <> HISREAL_INSPECAO.LOCAL_DESTINO AND INSPECIONADO = 'S' AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND QA_INSPECAO_SAIDA.NUMODF = @` + NamedOdf + `
AND QA_INSPECAO_SAIDA.CODINSP = @` + NamedCodigoInspecaoSaida + `
@AdvancedFilter`

const GetInspecaoSaidaItensHistoricoInspecaoPagination = `
@Sorting
OFFSET @Skip ROWS
FETCH NEXT @PageSize ROWS ONLY
`
