package queries

const GetPlanosNovaInspecao = `
SELECT 
	CASE WHEN PLANOINSP_PROCESSO.DESCRICAO IS NULL THEN QA_PLANO_INS_SAIDA.DESC1 
	ELSE PLANOINSP_PROCESSO.DESCRICAO 
	END AS Descricao, 
	QA_PLANO_INS_SAIDA.ID AS Id, 
	QA_PLANO_INS_SAIDA.PLANO AS Plano, 
	QA_PLANO_INS_SAIDA.SEQUENCIA AS Sequencia, 
	QA_PLANO_INS_SAIDA.METODO AS Metodo, 
	CASE WHEN PLANOINSP_PROCESSO.QTD_INSP_MAXIMA IS NOT NULL THEN PLANOINSP_PROCESSO.QTD_INSP_MAXIMA 
	ELSE QA_PLANO_INS_SAIDA.MAIORVALOR 
	END AS MaiorValorBase, 
	CASE WHEN PLANOINSP_PROCESSO.QTD_INSP_MINIMA IS NOT NULL THEN PLANOINSP_PROCESSO.QTD_INSP_MINIMA
	ELSE QA_PLANO_INS_SAIDA.MENORVALOR 
	END AS MenorValorBase 
FROM QA_PLANO_INS_SAIDA 
LEFT JOIN PLANOINSP_PROCESSO ON QA_PLANO_INS_SAIDA.R_E_C_N_O_ = PLANOINSP_PROCESSO.RECNO_PLANOINSP 
AND PLANOINSP_PROCESSO.RECNO_PROCESSO = @` + NamedRecnoProcesso + " \n" +
	`WHERE QA_PLANO_INS_SAIDA.PLANO = @` + NamedPlano + " \n" +
	`ORDER BY QA_PLANO_INS_SAIDA.SEQUENCIA` + " \n"

const GetPlanosNovaInspecaoPagination = "OFFSET @" + NamedSkip + " ROWS \n" +
	"FETCH NEXT @" + NamedPageSize + " ROWS ONLY"

const GetCountPlanosNovaInspecao = "SELECT COUNT(*) \n" +
	"FROM QA_PLANO_INS_SAIDA \n" +
	"LEFT JOIN PLANOINSP_PROCESSO ON QA_PLANO_INS_SAIDA.R_E_C_N_O_ = PLANOINSP_PROCESSO.RECNO_PLANOINSP \n" +
	"AND PLANOINSP_PROCESSO.RECNO_PROCESSO = @" + NamedRecnoProcesso + " \n" +
	"WHERE QA_PLANO_INS_SAIDA.PLANO = @" + NamedPlano

const GetInspecaoItensSelect = "QA_ITEM_INSPECAO_SAIDA.ID AS Id, QA_ITEM_INSPECAO_SAIDA.PLANO AS Plano," +
	"QA_ITEM_INSPECAO_SAIDA.OBSERVACAO AS Observacao, QA_ITEM_INSPECAO_SAIDA.NUMODF AS Odf, QA_ITEM_INSPECAO_SAIDA.DESCRICAO AS Descricao, QA_ITEM_INSPECAO_SAIDA.METODO AS Metodo," +
	"QA_ITEM_INSPECAO_SAIDA.SEQUENCIA AS Sequencia, QA_ITEM_INSPECAO_SAIDA.RESULTADO AS Resultado," +
	"QA_ITEM_INSPECAO_SAIDA.MAIORVALOR AS MaiorValor, QA_ITEM_INSPECAO_SAIDA.MENORVALOR AS MenorValor," +
	"QA_PLANO_INS_SAIDA.MAIORVALOR AS MaiorValorBase, QA_PLANO_INS_SAIDA.MENORVALOR AS MenorValorBase," +
	"QA_ITEM_INSPECAO_SAIDA.CODINSP AS CodigoInspecao, QA_ITEM_INSPECAO_SAIDA.EMPRESA_RECNO AS IdEmpresa"

const GetInspecaoItensJoin = "INNER JOIN QA_PLANO_INS_SAIDA\n" +
	"ON QA_ITEM_INSPECAO_SAIDA.SEQUENCIA = QA_PLANO_INS_SAIDA.SEQUENCIA\n" +
	"AND QA_ITEM_INSPECAO_SAIDA.PLANO = QA_PLANO_INS_SAIDA.PLANO"

const GetInspecaoSaidaCodigo = `
SELECT
	QA_INSPECAO_SAIDA.R_E_C_N_O_ AS Recno,
	QA_INSPECAO_SAIDA.CODINSP AS CodigoInspecao,
	QA_INSPECAO_SAIDA.CLIENTE AS Cliente,
	QA_INSPECAO_SAIDA.NUMPED AS Pedido,
	QA_INSPECAO_SAIDA.NUMODF AS Odf,
	QA_INSPECAO_SAIDA.DATAINSP AS DataInspecao,
	QA_INSPECAO_SAIDA.INSPETOR AS Inspetor,
	QA_INSPECAO_SAIDA.QTD_LOTE AS QtdLote,
	QA_INSPECAO_SAIDA.QTD_INSPECAO AS QtdInspecao,
	QA_INSPECAO_SAIDA.EMPRESA_RECNO AS IdEmpresa,
	QA_INSPECAO_SAIDA.RESULTADO AS Resultado,
	QA_INSPECAO_SAIDA.QTD_ACEITO AS QuantidadeAceita,
	QA_INSPECAO_SAIDA.QTD_RETRABALHO AS QuantidadeRetrabalhada,
	QA_INSPECAO_SAIDA.QTD_APROVADO AS QuantidadeAprovada,
	QA_INSPECAO_SAIDA.QTD_REJEITADO AS QuantidadeReprovada,
	ESTOQUE_LOCAL.CODIGO AS CodigoProduto,
	ESTOQUE_LOCAL.LOTE AS Lote,
	CASE WHEN PPEDLISE.NUMPED IS NOT NULL THEN
		PPEDLISE.NUMPED ELSE
		FECHA.NUMPED
	END AS NumeroPedido,
	CASE WHEN PPEDLISE.QTPEDI IS NOT NULL THEN
		CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > PPEDLISE.QTPEDI THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE PPEDLISE.QTPEDI END
	ELSE
		CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > FECHA.QTPEDE THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE FECHA.QTPEDE END
	END AS QuantidadeOrdem
FROM QA_INSPECAO_SAIDA
INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.R_E_C_N_O_ IN (
	SELECT TOP 1 R_E_C_N_O_ FROM ESTOQUE_LOCAL WHERE 
	ESTOQUE_LOCAL.ODF = QA_INSPECAO_SAIDA.NUMODF AND
	ESTOQUE_LOCAL.EMPRESA_RECNO = QA_INSPECAO_SAIDA.EMPRESA_RECNO AND
	ESTOQUE_LOCAL.LOTE = QA_INSPECAO_SAIDA.LOTE
)
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	PPEDLISE.NUMODF = ESTOQUE_LOCAL.ODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	FECHA.NODF = ESTOQUE_LOCAL.ODF
LEFT JOIN ESTOQUE_PEDIDO_VENDA ON
	(ESTOQUE_PEDIDO_VENDA.NUMPED = PPEDLISE.NUMPED OR ESTOQUE_PEDIDO_VENDA.NUMPED = FECHA.NUMPED) AND
	ESTOQUE_PEDIDO_VENDA.NUMODF = ESTOQUE_LOCAL.ODF AND ESTOQUE_PEDIDO_VENDA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	ESTOQUE_PEDIDO_VENDA.CODIGO = ESTOQUE_LOCAL.CODIGO
LEFT JOIN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL ON
	ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_LOCAL = ESTOQUE_LOCAL.R_E_C_N_O_ AND
	ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_PEDIDO_VENDA = ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_
WHERE QA_INSPECAO_SAIDA.CODINSP = @` + NamedCodigoInspecaoSaida
