package queries

const GetCountInspecaoSaidaCabecalhoHistoricoInspecao = `
SELECT
COUNT(DISTINCT InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA)
FROM QA_INSPECAO_SAIDA
INNER JOIN QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO = QA_INSPECAO_SAIDA.R_E_C_N_O_
INNER JOIN HISREAL AS HISREAL_INSPECAO ON HISREAL_INSPECAO.R_E_C_N_O_ = QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
INNER JOIN ESTOQUE_LOCAL ON
	HISREAL_INSPECAO.LOTE = ESTOQUE_LOCAL.LOTE AND HISREAL_INSPECAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	HISREAL_INSPECAO.CODIGO = ESTOQUE_LOCAL.CODIGO AND HISREAL_INSPECAO.LOCAL_DESTINO = ESTOQUE_LOCAL.LOCAL
INNER JOIN LOCAIS ON LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON ESTOQUE_LOCAL.CODIGO = ESTOQUE.CODIGO
INNER JOIN InspecaoSaidaExecutadoWeb ON InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA = QA_INSPECAO_SAIDA.R_E_C_N_O_
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	PPEDLISE.NUMODF = ESTOQUE_LOCAL.ODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	FECHA.NODF = ESTOQUE_LOCAL.ODF
LEFT JOIN ENGENHARIA_ROTEIRO_PROCESSO ON
	ENGENHARIA_ROTEIRO_PROCESSO.R_E_C_N_O_ = HISREAL_INSPECAO.RECNO_ENGENHARIA_ROTEIRO_PROCESSO
INNER JOIN PROCESSO ON
	PROCESSO.NUMPEC = ESTOQUE_LOCAL.CODIGO AND
	(PROCESSO.REVISAO = PPEDLISE.REVISAO OR PROCESSO.REVISAO = FECHA.REVISAO OR ENGENHARIA_ROTEIRO_PROCESSO.RECNO_PROCESSO = PROCESSO.R_E_C_N_O_)
INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO
    ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = ESTOQUE_LOCAL.ODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = ESTOQUE_LOCAL.CODIGO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
@JoinFilters
WHERE Estorno = 0 AND LOCAIS.CODIGO <> ESTOQUE_LOCAL.LOCAL AND INSPECIONADO = 'S' AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@AdvancedFilter
@CommonFilters
`

const GetAllInspecaoSaidaCabecalhoHistoricoInspecao = `
SELECT DISTINCT
    QA_INSPECAO_SAIDA.CLIENTE AS Cliente,
    QA_INSPECAO_SAIDA.NUMPED AS NumeroPedido,
	QA_INSPECAO_SAIDA.NUMODF AS OrdemFabricacao,
	COALESCE(PPEDLISE_ORDEM_FABRICACAO.NUMODF, QA_INSPECAO_SAIDA.NUMODF) AS OdfApontada,
	ESTOQUE.CODIGO AS CodigoProduto,
	ESTOQUE.DESCRI AS DescricaoProduto,
	QA_INSPECAO_SAIDA.QTD_LOTE AS QuantidadeLote,
	QA_INSPECAO_SAIDA.QTD_INSPECAO AS QuantidadeInspecao,
	ESTOQUE_LOCAL.LOTE AS Lote,
	PROCESSO.PLANO_INSP AS Plano,
	QA_PLANO_INS_SAIDA_CABECALHO.DESCRICAO AS DescricaoPlano,
	PPEDLISE.DTNEGO AS DataNegociado,
	QA_INSPECAO_SAIDA.CODINSP AS CodigoInspecao,
	CASE WHEN PPEDLISE.REVISAO IS NOT NULL THEN
	PPEDLISE.REVISAO ELSE
	FECHA.REVISAO
	END AS Revisao
FROM QA_INSPECAO_SAIDA
INNER JOIN QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO = QA_INSPECAO_SAIDA.R_E_C_N_O_
INNER JOIN HISREAL AS HISREAL_INSPECAO ON HISREAL_INSPECAO.R_E_C_N_O_ = QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
INNER JOIN ESTOQUE_LOCAL ON
	HISREAL_INSPECAO.LOTE = ESTOQUE_LOCAL.LOTE AND HISREAL_INSPECAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	HISREAL_INSPECAO.CODIGO = ESTOQUE_LOCAL.CODIGO AND HISREAL_INSPECAO.LOCAL_DESTINO = ESTOQUE_LOCAL.LOCAL
INNER JOIN LOCAIS ON LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON ESTOQUE_LOCAL.CODIGO = ESTOQUE.CODIGO
INNER JOIN InspecaoSaidaExecutadoWeb ON InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA = QA_INSPECAO_SAIDA.R_E_C_N_O_
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	PPEDLISE.NUMODF = ESTOQUE_LOCAL.ODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	FECHA.NODF = ESTOQUE_LOCAL.ODF
LEFT JOIN ENGENHARIA_ROTEIRO_PROCESSO ON
	ENGENHARIA_ROTEIRO_PROCESSO.R_E_C_N_O_ = HISREAL_INSPECAO.RECNO_ENGENHARIA_ROTEIRO_PROCESSO
INNER JOIN PROCESSO ON
	PROCESSO.NUMPEC = ESTOQUE_LOCAL.CODIGO AND
	(PROCESSO.REVISAO = PPEDLISE.REVISAO OR PROCESSO.REVISAO = FECHA.REVISAO OR ENGENHARIA_ROTEIRO_PROCESSO.RECNO_PROCESSO = PROCESSO.R_E_C_N_O_)
INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO
    ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = ESTOQUE_LOCAL.ODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = ESTOQUE_LOCAL.CODIGO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
@JoinFilters
WHERE Estorno = 0 AND LOCAIS.CODIGO <> ESTOQUE_LOCAL.LOCAL AND INSPECIONADO = 'S' AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
@AdvancedFilter
@CommonFilters
`

const GetInspecaoSaidaCabecalhoHistoricoInspecaoPagination = `
@Sorting
OFFSET @Skip ROWS
FETCH NEXT @PageSize ROWS ONLY
`

const GetCountInspecaoSaidaItensHistoricoInspecao = `
SELECT
COUNT(DISTINCT InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA)
FROM QA_INSPECAO_SAIDA
INNER JOIN QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO = QA_INSPECAO_SAIDA.R_E_C_N_O_
INNER JOIN HISREAL AS HISREAL_INSPECAO ON HISREAL_INSPECAO.R_E_C_N_O_ = QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
LEFT JOIN ESTOQUE_LOCAL ON
	HISREAL_INSPECAO.LOTE = ESTOQUE_LOCAL.LOTE AND HISREAL_INSPECAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	HISREAL_INSPECAO.CODIGO = ESTOQUE_LOCAL.CODIGO AND HISREAL_INSPECAO.LOCAL_DESTINO = ESTOQUE_LOCAL.LOCAL
INNER JOIN LOCAIS ON LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON HISREAL_INSPECAO.CODIGO = ESTOQUE.CODIGO
INNER JOIN InspecaoSaidaExecutadoWeb ON InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA = QA_INSPECAO_SAIDA.R_E_C_N_O_
LEFT JOIN HISREAL ON
	HISREAL.LOTE = HISREAL_INSPECAO.LOTE AND HISREAL.CODIGO = HISREAL_INSPECAO.CODIGO AND HISREAL.LOCAL_DESTINO = LOCAIS.CODIGO AND
	HISREAL.FORMA = 'E' AND HISREAL.ESTORNADO_APT_PRODUCAO = 'N' AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = ESTOQUE_LOCAL.ODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = ESTOQUE_LOCAL.CODIGO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
@JoinFilters
WHERE Estorno = 0 AND LOCAIS.CODIGO <> HISREAL_INSPECAO.LOCAL_DESTINO AND INSPECIONADO = 'S' AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND QA_INSPECAO_SAIDA.NUMODF = @` + NamedOdf + `
AND QA_INSPECAO_SAIDA.CODINSP = @` + NamedCodigoInspecaoSaida + `
@AdvancedFilter`

const GetAllInspecaoSaidaItensHistoricoInspecao = `
SELECT DISTINCT
    CAST(QA_INSPECAO_SAIDA.Id AS VARCHAR(36)) as IdInspecao,
	QA_INSPECAO_SAIDA.CODINSP AS CodigoInspecao,
	QA_INSPECAO_SAIDA.R_E_C_N_O_ AS RecnoInspecao,
	QA_INSPECAO_SAIDA.NUMODF AS OrdemFabricacao,
	COALESCE(PPEDLISE_ORDEM_FABRICACAO.NUMODF, QA_INSPECAO_SAIDA.NUMODF) AS OdfApontada,
	ESTOQUE.CODIGO AS CodigoProduto,
	ESTOQUE.DESCRI AS DescricaoProduto,
	QA_INSPECAO_SAIDA.QTD_INSPECAO AS QuantidadeInspecao,
	QA_INSPECAO_SAIDA.TIPOINSP AS TipoInspecao,
	QA_INSPECAO_SAIDA.DATAINSP AS DataInspecao,
	QA_INSPECAO_SAIDA.INSPETOR AS Inspetor,
	QA_INSPECAO_SAIDA.RESULTADO AS Resultado,
	QA_INSPECAO_SAIDA.QTD_RETRABALHO AS QuantidadeRetrabalhada,
	QA_INSPECAO_SAIDA.QTD_APROVADO AS QuantidadeAprovada,
	QA_INSPECAO_SAIDA.QTD_REJEITADO AS QuantidadeReprovada,
	QA_INSPECAO_SAIDA.CLIENTE AS Cliente,
    QA_INSPECAO_SAIDA.NUMPED AS NumeroPedido,
    InspecaoSaidaExecutadoWeb.ID_RNC AS IdRnc,
	InspecaoSaidaExecutadoWeb.CODIGO_RNC AS CodigoRnc
FROM QA_INSPECAO_SAIDA
INNER JOIN QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO ON QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_INSPECAO = QA_INSPECAO_SAIDA.R_E_C_N_O_
INNER JOIN HISREAL AS HISREAL_INSPECAO ON HISREAL_INSPECAO.R_E_C_N_O_ = QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO.RECNO_HISREAL
LEFT JOIN ESTOQUE_LOCAL ON
	HISREAL_INSPECAO.LOTE = ESTOQUE_LOCAL.LOTE AND HISREAL_INSPECAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	HISREAL_INSPECAO.CODIGO = ESTOQUE_LOCAL.CODIGO AND HISREAL_INSPECAO.LOCAL_DESTINO = ESTOQUE_LOCAL.LOCAL
INNER JOIN LOCAIS ON LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON HISREAL_INSPECAO.CODIGO = ESTOQUE.CODIGO
INNER JOIN InspecaoSaidaExecutadoWeb ON InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA = QA_INSPECAO_SAIDA.R_E_C_N_O_
LEFT JOIN HISREAL ON
	HISREAL.LOTE = HISREAL_INSPECAO.LOTE AND HISREAL.CODIGO = HISREAL_INSPECAO.CODIGO AND HISREAL.LOCAL_DESTINO = LOCAIS.CODIGO AND
	HISREAL.FORMA = 'E' AND HISREAL.ESTORNADO_APT_PRODUCAO = 'N' AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = ESTOQUE_LOCAL.ODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = ESTOQUE_LOCAL.CODIGO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
@JoinFilters
WHERE Estorno = 0 AND LOCAIS.CODIGO <> HISREAL_INSPECAO.LOCAL_DESTINO AND INSPECIONADO = 'S' AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND QA_INSPECAO_SAIDA.NUMODF = @` + NamedOdf + `
AND QA_INSPECAO_SAIDA.CODINSP = @` + NamedCodigoInspecaoSaida + `
@AdvancedFilter`

const GetInspecaoSaidaItensHistoricoInspecaoPagination = `
@Sorting
OFFSET @Skip ROWS
FETCH NEXT @PageSize ROWS ONLY
`
