package queries

const GetOrdensInspecaoQuery = `
SELECT
    ESTOQUE_LOCAL.ODF AS ODF, 
	COALESCE(HISREAL.ODF, ESTOQUE_LOCAL.ODF) AS OdfApontada,
	ESTOQUE_LOCAL.CODIGO AS CodigoProduto, 
	ESTOQUE_LOCAL.LOTE AS Lote,
	ESTOQUE.DESCRI AS DescricaoProduto,
	PROCESSO.PLANO_INSP AS Plano,
	PROCESSO.R_E_C_N_O_ AS RecnoProcesso,
	QA_PLANO_INS_SAIDA_CABECALHO.DESCRICAO AS DescricaoPlano,
	CASE WHEN PPEDLISE.NUMPED IS NOT NULL THEN
	PPEDLISE.NUMPED ELSE
	FECHA.NUMPED
	END AS NumeroPedido,
	COALESCE(CRM_PEDIDO.CLIENTE, PPEDLISE.CLIENTE, FECHA.CODCLI, '000') AS Cliente, 
	CASE WHEN PPEDLISE.SITUACAO IS NOT NULL THEN
	PPEDLISE.SITUACAO ELSE
	FECHA.SITUACAO
	END AS Situacao,
	CASE WHEN PPEDLISE.REVISAO IS NOT NULL THEN
	PPEDLISE.REVISAO ELSE
	FECHA.REVISAO
	END AS Revisao,
	CASE WHEN PPEDLISE.DTINICIO IS NOT NULL THEN
	PPEDLISE.DTINICIO ELSE
	FECHA.DTINIC
	END AS DataInicio,
	CASE WHEN PPEDLISE.DTENPD IS NOT NULL THEN
	PPEDLISE.DTENPD ELSE
	FECHA.DTENTR
	END AS DataEntrega,
	CASE WHEN PPEDLISE.DTEMISSAO IS NOT NULL THEN
	PPEDLISE.DTEMISSAO ELSE
	FECHA.DTEMIS
	END AS DataEmissao,
    PPEDLISE.DTNEGO AS DataNegociado,
	CASE WHEN PPEDLISE.QTPEDI IS NOT NULL THEN
		CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > PPEDLISE.QTPEDI THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE PPEDLISE.QTPEDI END
	ELSE
		CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > FECHA.QTPEDE THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE FECHA.QTPEDE END
	END AS QuantidadeOrdem,
	ESTOQUE_LOCAL.QTDE QuantidadeProduzida,
	-- sum 
	ISNULL((SELECT SUM(QA_INSPECAO_SAIDA.QTD_INSPECAO)
	FROM 
	QA_INSPECAO_SAIDA
	WHERE 
	NUMODF = ESTOQUE_LOCAL.ODF AND
	QA_INSPECAO_SAIDA.LOTE = ESTOQUE_LOCAL.LOTE AND
	EMPRESA_RECNO = PPEDLISE.EMPRESA_RECNO), 0) 
	AS QuantidadeInspecionada,
	-- Quantidade Lote dando baixa nas quantidades mandadas para transferencia em background
	ESTOQUE_LOCAL.QTDE -
	ISNULL((
		SELECT 
			ISNULL(InspecaoSaidaExecutadoWeb.QUANTIDADE_TRANSFERIDA, 0)
		FROM InspecaoSaidaExecutadoWeb
		INNER JOIN QA_INSPECAO_SAIDA ON QA_INSPECAO_SAIDA.R_E_C_N_O_ = InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA
		WHERE InspecaoSaidaExecutadoWeb.ESTORNO = 0 AND QA_INSPECAO_SAIDA.INSPECIONADO <> 'S'), 
	0)
	AS QuantidadeLote
FROM ESTOQUE_LOCAL
INNER JOIN LOCAIS ON 
	LOCAIS.LOCAL_CQ_SAIDA = 'S' AND LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + ` 
INNER JOIN ESTOQUE ON 
	ESTOQUE.CODIGO = ESTOQUE_LOCAL.CODIGO
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	PPEDLISE.NUMODF = ESTOQUE_LOCAL.ODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	FECHA.NODF = ESTOQUE_LOCAL.ODF
LEFT JOIN ESTOQUE_PEDIDO_VENDA ON
	(ESTOQUE_PEDIDO_VENDA.NUMPED = PPEDLISE.NUMPED OR ESTOQUE_PEDIDO_VENDA.NUMPED = FECHA.NUMPED) AND
	ESTOQUE_PEDIDO_VENDA.NUMODF = ESTOQUE_LOCAL.ODF AND ESTOQUE_PEDIDO_VENDA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	ESTOQUE_PEDIDO_VENDA.CODIGO = ESTOQUE_LOCAL.CODIGO
LEFT JOIN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL ON
	ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_LOCAL = ESTOQUE_LOCAL.R_E_C_N_O_ AND
	ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_PEDIDO_VENDA = ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_
LEFT JOIN CRM_PEDIDO ON (CRM_PEDIDO.PEDIDO = PPEDLISE.NUMPED OR CRM_PEDIDO.PEDIDO = FECHA.NUMPED) AND CRM_PEDIDO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
LEFT JOIN HISREAL ON 
	HISREAL.LOTE = ESTOQUE_LOCAL.LOTE AND HISREAL.CODIGO = ESTOQUE_LOCAL.CODIGO AND HISREAL.LOCAL_DESTINO = ESTOQUE_LOCAL.LOCAL AND
	HISREAL.FORMA = 'E' AND HISREAL.ESTORNADO_APT_PRODUCAO = 'N' AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + ` 
LEFT JOIN ENGENHARIA_ROTEIRO_PROCESSO ON ENGENHARIA_ROTEIRO_PROCESSO.R_E_C_N_O_ = HISREAL.RECNO_ENGENHARIA_ROTEIRO_PROCESSO
INNER JOIN PROCESSO ON
	PROCESSO.NUMPEC = ESTOQUE_LOCAL.CODIGO AND
	(PROCESSO.REVISAO = PPEDLISE.REVISAO OR PROCESSO.REVISAO = FECHA.REVISAO OR ENGENHARIA_ROTEIRO_PROCESSO.RECNO_PROCESSO = PROCESSO.R_E_C_N_O_)
INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO 
    ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
WHERE 
ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO AND
ESTOQUE_LOCAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n"

const GetOrdensInspecaoPagination = "ORDER BY ESTOQUE_LOCAL.R_E_C_N_O_ \n" +
	"OFFSET @Skip ROWS \n" +
	"FETCH NEXT @PageSize ROWS ONLY \n"

const GetQuantidadeOrdensInspecao = `
SELECT
    COUNT(*)
FROM ESTOQUE_LOCAL
INNER JOIN LOCAIS ON 
	LOCAIS.LOCAL_CQ_SAIDA = 'S' AND LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + ` 
INNER JOIN ESTOQUE ON 
	ESTOQUE.CODIGO = ESTOQUE_LOCAL.CODIGO
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	PPEDLISE.NUMODF = ESTOQUE_LOCAL.ODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	FECHA.NODF = ESTOQUE_LOCAL.ODF
INNER JOIN PROCESSO ON
	PROCESSO.NUMPEC = ESTOQUE_LOCAL.CODIGO AND
	(PROCESSO.REVISAO = PPEDLISE.REVISAO OR PROCESSO.REVISAO = FECHA.REVISAO)
INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO 
    ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
WHERE 
ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO AND
ESTOQUE_LOCAL.EMPRESA_RECNO = @` + NamedEmpresaRecno

const GetOrdensInspecaoOdfFilter = `
AND ESTOQUE_LOCAL.ODF = ?
`
