package queries

const GetOrdensInspecaoQuery = `
WITH 
CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS AS (
	SELECT 
		ODF, CODIGO, LOTE, MAX(DATA_FABRICACAO) as DATA_FABRICACAO, MAX(DATA_VALIDADE) AS DATA_VALIDADE, EMPRESA_RECNO, LOCAL_DESTINO AS LOCAL, SUM(QTRECEB) AS QTRECEB_ENTRADA
	FROM HISREAL
	WHERE LOCAL_DESTINO IN (SELECT CODIGO FROM LOCAIS WHERE LOCAL_CQ_SAIDA = 'S') AND EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + ` AND ESTORNADO_APT_PRODUCAO = 'N' AND ((MOV_EFETIVA = 'S' AND FORMA = 'E') OR (MOV_EFETIVA = 'N' AND FORMA = 'P' AND OPERACAO IS NOT NULL)) -- Esse OR é para o cenario de ODF de retrabalho
	GROUP BY ODF, CODIGO, LOTE, EMPRESA_RECNO, LOCAL_DESTINO
),
CTE_ENTRADA_CQ_SAIDA AS (
	SELECT 
		ODF, CODIGO, LOTE, EMPRESA_RECNO, SUM(QTRECEB) AS QTRECEB_ENTRADA
	FROM HISREAL
	WHERE LOCAL_DESTINO IN (SELECT CODIGO FROM LOCAIS WHERE LOCAL_CQ_SAIDA = 'S') AND EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
	GROUP BY ODF, CODIGO, LOTE, EMPRESA_RECNO, LOCAL_DESTINO
),
CTE_SAIDA_CQ_SAIDA AS (
	SELECT 
		ODF, CODIGO, LOTE, MAX(DATA_FABRICACAO) as DATA_FABRICACAO, MAX(DATA_VALIDADE) AS DATA_VALIDADE, EMPRESA_RECNO, LOCAL_DESTINO AS LOCAL, SUM(QTRECEB) AS QTRECEB_SAIDA
	FROM HISREAL
	WHERE LOCAL_ORIGEM IN (SELECT CODIGO FROM LOCAIS WHERE LOCAL_CQ_SAIDA = 'S') AND EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
	GROUP BY ODF, CODIGO, LOTE, EMPRESA_RECNO, LOCAL_DESTINO
),
CTE_SALDO_CQ AS (
	SELECT 
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.ODF,
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.CODIGO,
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.LOTE,
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.DATA_FABRICACAO,
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.DATA_VALIDADE,
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.EMPRESA_RECNO,
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.LOCAL,
		CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.QTRECEB_ENTRADA,
		ISNULL(CTE_SAIDA_CQ_SAIDA.QTRECEB_SAIDA, 0) AS QTRECEB_SAIDA,
		(CTE_ENTRADA_CQ_SAIDA.QTRECEB_ENTRADA - ISNULL(CTE_SAIDA_CQ_SAIDA.QTRECEB_SAIDA, 0)) AS SALDO,
    	(CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.QTRECEB_ENTRADA - ISNULL((
        SELECT
        SUM(ISNULL(InspecaoSaidaExecutadoWeb.QUANTIDADE_TRANSFERIDA, 0))
        FROM InspecaoSaidaExecutadoWeb
        INNER JOIN QA_INSPECAO_SAIDA ON QA_INSPECAO_SAIDA.R_E_C_N_O_ = InspecaoSaidaExecutadoWeb.RECNO_INSPECAO_SAIDA
        WHERE InspecaoSaidaExecutadoWeb.ESTORNO = 0
        AND QA_INSPECAO_SAIDA.INSPECIONADO = 'S'
        AND QA_INSPECAO_SAIDA.NUMODF = CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.ODF
        AND QA_INSPECAO_SAIDA.LOTE = CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.LOTE
        AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
    ), 0)) AS QUANTIDADE_LOTE
	FROM CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS
	LEFT JOIN CTE_SAIDA_CQ_SAIDA
		ON CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.ODF = CTE_SAIDA_CQ_SAIDA.ODF 
		AND CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.CODIGO = CTE_SAIDA_CQ_SAIDA.CODIGO 
		AND CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.LOTE = CTE_SAIDA_CQ_SAIDA.LOTE
		AND CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.EMPRESA_RECNO = CTE_SAIDA_CQ_SAIDA.EMPRESA_RECNO
	LEFT JOIN CTE_ENTRADA_CQ_SAIDA
		ON CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.ODF = CTE_ENTRADA_CQ_SAIDA.ODF 
		AND CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.CODIGO = CTE_ENTRADA_CQ_SAIDA.CODIGO 
		AND CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.LOTE = CTE_ENTRADA_CQ_SAIDA.LOTE
		AND CTE_ENTRADA_CQ_SAIDA_NAO_ESTORNADOS.EMPRESA_RECNO = CTE_ENTRADA_CQ_SAIDA.EMPRESA_RECNO
)

-- query principal
SELECT DISTINCT
    CTE_SALDO_CQ.ODF AS ODF,
    COALESCE(PPEDLISE_ORDEM_FABRICACAO.NUMODF, CTE_SALDO_CQ.ODF) AS OdfApontada,
    CTE_SALDO_CQ.CODIGO AS CodigoProduto,
    CTE_SALDO_CQ.LOTE AS Lote,
    CTE_SALDO_CQ.DATA_FABRICACAO AS DataFabricacao,
    CTE_SALDO_CQ.DATA_VALIDADE AS DataValidade,
    ESTOQUE.DESCRI AS DescricaoProduto,
    PROCESSO.PLANO_INSP AS Plano,
    PROCESSO.R_E_C_N_O_ AS RecnoProcesso,
    QA_PLANO_INS_SAIDA_CABECALHO.DESCRICAO AS DescricaoPlano,
    CASE WHEN PPEDLISE.NUMPED IS NOT NULL THEN PPEDLISE.NUMPED ELSE FECHA.NUMPED END AS NumeroPedido,
    COALESCE(CRM_PEDIDO.CLIENTE, PPEDLISE.CLIENTE, FECHA.CODCLI, '000') AS Cliente,
    CASE WHEN PPEDLISE.SITUACAO IS NOT NULL THEN PPEDLISE.SITUACAO ELSE FECHA.SITUACAO END AS Situacao,
    CASE WHEN PPEDLISE.REVISAO IS NOT NULL THEN PPEDLISE.REVISAO ELSE FECHA.REVISAO END AS Revisao,
    CASE WHEN PPEDLISE.DTINICIO IS NOT NULL THEN PPEDLISE.DTINICIO ELSE FECHA.DTINIC END AS DataInicio,
    CASE WHEN PPEDLISE.DTENPD IS NOT NULL THEN PPEDLISE.DTENPD ELSE FECHA.DTENTR END AS DataEntrega, 
    CASE WHEN PPEDLISE.DTEMISSAO IS NOT NULL THEN PPEDLISE.DTEMISSAO ELSE FECHA.DTEMIS END AS DataEmissao,
    PPEDLISE.DTNEGO AS DataNegociado,
    CASE 
        WHEN PPEDLISE.QTPEDI IS NOT NULL THEN 
            CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > PPEDLISE.QTPEDI THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE PPEDLISE.QTPEDI END
        ELSE 
            CASE WHEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE > FECHA.QTPEDE THEN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.QUANTIDADE ELSE FECHA.QTPEDE END
    END AS QuantidadeOrdem,
    CTE_SALDO_CQ.QTRECEB_ENTRADA AS QuantidadeProduzida,
    ISNULL((
        SELECT SUM(QA_INSPECAO_SAIDA.QTD_INSPECAO)
        FROM QA_INSPECAO_SAIDA
        WHERE QA_INSPECAO_SAIDA.NUMODF = CTE_SALDO_CQ.ODF
        AND QA_INSPECAO_SAIDA.LOTE = CTE_SALDO_CQ.LOTE
        AND QA_INSPECAO_SAIDA.EMPRESA_RECNO = COALESCE(PPEDLISE.EMPRESA_RECNO, FECHA.EMPRESA_RECNO)
    ), 0) AS QuantidadeInspecionada,
    CTE_SALDO_CQ.QUANTIDADE_LOTE AS QuantidadeLote

FROM CTE_SALDO_CQ
INNER JOIN LOCAIS ON LOCAIS.LOCAL_CQ_SAIDA = 'S' AND LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + ` AND CTE_SALDO_CQ.LOCAL = LOCAIS.CODIGO
INNER JOIN ESTOQUE ON ESTOQUE.CODIGO = CTE_SALDO_CQ.CODIGO
INNER JOIN ESTOQUE_LOCAL ON ESTOQUE_LOCAL.CODIGO = CTE_SALDO_CQ.CODIGO AND ESTOQUE_LOCAL.LOTE = CTE_SALDO_CQ.LOTE AND ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO
LEFT JOIN PPEDLISE ON PPEDLISE.EMPRESA_RECNO = CTE_SALDO_CQ.EMPRESA_RECNO AND PPEDLISE.NUMODF = CTE_SALDO_CQ.ODF
LEFT JOIN FECHA ON FECHA.EMPRESA_RECNO = CTE_SALDO_CQ.EMPRESA_RECNO AND FECHA.NODF = CTE_SALDO_CQ.ODF
LEFT JOIN ESTOQUE_PEDIDO_VENDA ON 
    (ESTOQUE_PEDIDO_VENDA.NUMPED = PPEDLISE.NUMPED OR ESTOQUE_PEDIDO_VENDA.NUMPED = FECHA.NUMPED) AND
    ESTOQUE_PEDIDO_VENDA.NUMODF = CTE_SALDO_CQ.ODF AND 
    ESTOQUE_PEDIDO_VENDA.EMPRESA_RECNO = CTE_SALDO_CQ.EMPRESA_RECNO AND 
    ESTOQUE_PEDIDO_VENDA.CODIGO = CTE_SALDO_CQ.CODIGO
LEFT JOIN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL ON
    ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_PEDIDO_VENDA = ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_
LEFT JOIN CRM_PEDIDO ON (CRM_PEDIDO.PEDIDO = PPEDLISE.NUMPED OR CRM_PEDIDO.PEDIDO = FECHA.NUMPED) AND CRM_PEDIDO.EMPRESA_RECNO = CTE_SALDO_CQ.EMPRESA_RECNO
LEFT JOIN HISREAL ON
    HISREAL.LOTE = CTE_SALDO_CQ.LOTE AND HISREAL.CODIGO = CTE_SALDO_CQ.CODIGO AND HISREAL.LOCAL_DESTINO = CTE_SALDO_CQ.LOCAL AND
    HISREAL.FORMA = 'E' AND HISREAL.ESTORNADO_APT_PRODUCAO = 'N' AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + ` AND
    HISREAL.ID_APONTAMENTO IS NOT NULL
LEFT JOIN ENGENHARIA_ROTEIRO_PROCESSO ON ENGENHARIA_ROTEIRO_PROCESSO.R_E_C_N_O_ = HISREAL.RECNO_ENGENHARIA_ROTEIRO_PROCESSO
INNER JOIN PROCESSO ON
    PROCESSO.NUMPEC = CTE_SALDO_CQ.CODIGO AND
    (PROCESSO.REVISAO = PPEDLISE.REVISAO OR PROCESSO.REVISAO = FECHA.REVISAO OR ENGENHARIA_ROTEIRO_PROCESSO.RECNO_PROCESSO = PROCESSO.R_E_C_N_O_)
INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
LEFT JOIN PCP_ODF_PEDIDO ON PCP_ODF_PEDIDO.ODFPED = CTE_SALDO_CQ.ODF AND PCP_ODF_PEDIDO.EMPRESA_RECNO = CTE_SALDO_CQ.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON 
    PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF AND
    PPEDLISE_ORDEM_FABRICACAO.CODPCA = CTE_SALDO_CQ.CODIGO AND
    PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = CTE_SALDO_CQ.EMPRESA_RECNO
@JoinFilters
WHERE 
    CTE_SALDO_CQ.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
    AND CTE_SALDO_CQ.SALDO > 0
	AND CTE_SALDO_CQ.QUANTIDADE_LOTE > 0
@AdvancedFilter
@CommonFilters` + "\n"

const GetOrdensInspecaoPagination = "@Sorting \n" +
	"OFFSET @Skip ROWS \n" +
	"FETCH NEXT @PageSize ROWS ONLY \n"

const GetQuantidadeOrdensInspecao = `
SELECT
    COUNT(DISTINCT ESTOQUE_LOCAL.R_E_C_N_O_)
FROM ESTOQUE_LOCAL
INNER JOIN LOCAIS ON
	LOCAIS.LOCAL_CQ_SAIDA = 'S' AND LOCAIS.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + `
INNER JOIN ESTOQUE ON
	ESTOQUE.CODIGO = ESTOQUE_LOCAL.CODIGO
LEFT JOIN PPEDLISE ON
	PPEDLISE.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	PPEDLISE.NUMODF = ESTOQUE_LOCAL.ODF
LEFT JOIN FECHA ON
	FECHA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	FECHA.NODF = ESTOQUE_LOCAL.ODF
LEFT JOIN ESTOQUE_PEDIDO_VENDA ON
	(ESTOQUE_PEDIDO_VENDA.NUMPED = PPEDLISE.NUMPED OR ESTOQUE_PEDIDO_VENDA.NUMPED = FECHA.NUMPED) AND
	ESTOQUE_PEDIDO_VENDA.NUMODF = ESTOQUE_LOCAL.ODF AND ESTOQUE_PEDIDO_VENDA.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO AND
	ESTOQUE_PEDIDO_VENDA.CODIGO = ESTOQUE_LOCAL.CODIGO
LEFT JOIN ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL ON
	ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_LOCAL = ESTOQUE_LOCAL.R_E_C_N_O_ AND
	ESTOQUE_PEDIDO_VENDA_ESTOQUE_LOCAL.RECNO_ESTOQUE_PEDIDO_VENDA = ESTOQUE_PEDIDO_VENDA.R_E_C_N_O_
LEFT JOIN CRM_PEDIDO ON (CRM_PEDIDO.PEDIDO = PPEDLISE.NUMPED OR CRM_PEDIDO.PEDIDO = FECHA.NUMPED) AND CRM_PEDIDO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
LEFT JOIN HISREAL ON
	HISREAL.LOTE = ESTOQUE_LOCAL.LOTE AND HISREAL.CODIGO = ESTOQUE_LOCAL.CODIGO AND HISREAL.LOCAL_DESTINO = ESTOQUE_LOCAL.LOCAL AND
	HISREAL.FORMA = 'E' AND HISREAL.ESTORNADO_APT_PRODUCAO = 'N' AND HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + "\n" + ` AND HISREAL.ID_APONTAMENTO IS NOT NULL
LEFT JOIN ENGENHARIA_ROTEIRO_PROCESSO ON ENGENHARIA_ROTEIRO_PROCESSO.R_E_C_N_O_ = HISREAL.RECNO_ENGENHARIA_ROTEIRO_PROCESSO
INNER JOIN PROCESSO ON
	PROCESSO.NUMPEC = ESTOQUE_LOCAL.CODIGO AND
	(PROCESSO.REVISAO = PPEDLISE.REVISAO OR PROCESSO.REVISAO = FECHA.REVISAO OR ENGENHARIA_ROTEIRO_PROCESSO.RECNO_PROCESSO = PROCESSO.R_E_C_N_O_)
INNER JOIN QA_PLANO_INS_SAIDA_CABECALHO
    ON QA_PLANO_INS_SAIDA_CABECALHO.CODIGO = PROCESSO.PLANO_INSP
LEFT JOIN PCP_ODF_PEDIDO ON
	PCP_ODF_PEDIDO.ODFPED = ESTOQUE_LOCAL.ODF
	AND PCP_ODF_PEDIDO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
LEFT JOIN PPEDLISE AS PPEDLISE_ORDEM_FABRICACAO ON
	PPEDLISE_ORDEM_FABRICACAO.NUMODF = PCP_ODF_PEDIDO.NUMODF
	AND PPEDLISE_ORDEM_FABRICACAO.CODPCA = ESTOQUE_LOCAL.CODIGO
	AND PPEDLISE_ORDEM_FABRICACAO.EMPRESA_RECNO = ESTOQUE_LOCAL.EMPRESA_RECNO
@JoinFilters
WHERE
ESTOQUE_LOCAL.LOCAL = LOCAIS.CODIGO AND
ESTOQUE_LOCAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + ` AND
ISNULL((
	SELECT SUM(HISAPONTA.PC_BOAS) FROM HISAPONTA
	WHERE HISAPONTA.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
	AND HISAPONTA.ODF = ESTOQUE_LOCAL.ODF
	AND HISAPONTA.LOTE = ESTOQUE_LOCAL.LOTE
	AND HISAPONTA.CAMPO1 = 4
	AND HISAPONTA.NUMOPE = '999'
), 0) > ISNULL((
	SELECT SUM(QA_INSPECAO_SAIDA.QTD_INSPECAO)
	FROM
	QA_INSPECAO_SAIDA
	WHERE
	QA_INSPECAO_SAIDA.NUMODF = ESTOQUE_LOCAL.ODF AND
	QA_INSPECAO_SAIDA.LOTE = ESTOQUE_LOCAL.LOTE AND
	QA_INSPECAO_SAIDA.EMPRESA_RECNO = COALESCE(PPEDLISE.EMPRESA_RECNO, FECHA.EMPRESA_RECNO) AND
	QA_INSPECAO_SAIDA.INSPECIONADO = 'S'
), 0) AND
ISNULL((
	SELECT
	SUM(ISNULL(ESTOQUE_LOCAL_AUX.QTDE, 0))
	FROM ESTOQUE_LOCAL AS ESTOQUE_LOCAL_AUX
	WHERE ESTOQUE_LOCAL_AUX.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
	AND ESTOQUE_LOCAL_AUX.ODF = ESTOQUE_LOCAL.ODF
	AND ESTOQUE_LOCAL_AUX.LOTE = ESTOQUE_LOCAL.LOTE
	AND ESTOQUE_LOCAL_AUX.LOCAL = ESTOQUE_LOCAL.LOCAL
), 0) > 0
@AdvancedFilter
@CommonFilters`

const GetOrdensInspecaoOdfFilter = `
AND CTE_SALDO_CQ.ODF = ?
AND CTE_SALDO_CQ.LOTE = ?
`

const GetHisrealRelatorio = `
SELECT
	DISTINCT
	HISREAL.CODIGO AS CodigoProduto,
	HISREAL.LOTE AS Lote,
	HISREAL.DATA_FABRICACAO AS DataFabricacao,
	HISREAL.DATA_VALIDADE AS DataValidade,
	HISREAL.DESCRICAO AS DescricaoProduto
FROM HISREAL
WHERE
HISREAL.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND HISREAL.ODF = @` + NamedOdf + `
AND HISREAL.CODIGO = @` + NamedProdutoCodigo + `
ORDER BY HISREAL.DATA_VALIDADE DESC
`

const GetClienteRelatorio = `
SELECT Cliente.RASSOC FROM PCP_ODF_PEDIDO AS OdfPedido
LEFT JOIN CRM_PEDIDO AS Pedido ON Pedido.PEDIDO = OdfPedido.NUMPED
LEFT JOIN CLIENTES AS Cliente ON Cliente.CODIGO = Pedido.CLIENTE
WHERE
OdfPedido.EMPRESA_RECNO = @` + NamedEmpresaRecno + `
AND OdfPedido.NUMODF = @` + NamedOdf + `
`
