// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viasoft.Qualidade.RNC.Core.Infrastructure.EntityFrameworkCore;

#nullable disable

namespace Viasoft.Qualidade.RNC.Core.Infrastructure.Migrations
{
    [DbContext(typeof(ViasoftQualidadeRNCCoreDbContext))]
    [Migration("20240509125552_ConvertendoIdPedidoParaNumeroPedido")]
    partial class ConvertendoIdPedidoParaNumeroPedido
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.AcaoPreventivaNaoConformidades.AcaoPreventivaNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("acao");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<DateTime?>("DataAnalise")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataanalise");

                    b.Property<DateTime?>("DataPrevistaImplantacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataprevistaimplantacao");

                    b.Property<DateTime?>("DataVerificacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataverificacao");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdAcaoPreventiva")
                        .HasColumnType("uuid")
                        .HasColumnName("idacaopreventiva");

                    b.Property<Guid?>("IdAuditor")
                        .HasColumnType("uuid")
                        .HasColumnName("idauditor");

                    b.Property<Guid>("IdDefeitoNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("iddefeitonaoconformidade");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<Guid?>("IdResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("idresponsavel");

                    b.Property<bool>("Implementada")
                        .HasColumnType("boolean")
                        .HasColumnName("implementada");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<DateTime?>("NovaData")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("novadata");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_acaopreventivanaoconformidade");

                    b.ToTable("acaopreventivanaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.AcoesPreventivas.AcaoPreventiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Codigo"), 1L, null, 1L, null, null, null);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid?>("IdResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("idresponsavel");

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isativo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_acaopreventiva");

                    b.ToTable("acaopreventiva", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.CausaNaoConformidades.CausaNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdCausa")
                        .HasColumnType("uuid")
                        .HasColumnName("idcausa");

                    b.Property<Guid>("IdDefeitoNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("iddefeitonaoconformidade");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_causanaoconformidade");

                    b.ToTable("causanaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Causas.Causa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Codigo"), 1L, null, 1L, null, null, null);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isativo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_causa");

                    b.ToTable("causa", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.CentroCustos.CentroCusto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsSintetico")
                        .HasColumnType("boolean")
                        .HasColumnName("issintetico");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_centrocusto");

                    b.ToTable("centrocusto", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("razaosocial");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.ConclusaoNaoConformidades.ConclusaoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CicloDeTempo")
                        .HasColumnType("integer")
                        .HasColumnName("ciclodetempo");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<DateTime?>("DataReuniao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datareuniao");

                    b.Property<DateTime>("DataVerificacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataverificacao");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<bool>("Eficaz")
                        .HasColumnType("boolean")
                        .HasColumnName("eficaz");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<string>("Evidencia")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("evidencia");

                    b.Property<Guid>("IdAuditor")
                        .HasColumnType("uuid")
                        .HasColumnName("idauditor");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<Guid>("IdNovoRelatorio")
                        .HasColumnType("uuid")
                        .HasColumnName("idnovorelatorio");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<bool>("NovaReuniao")
                        .HasColumnType("boolean")
                        .HasColumnName("novareuniao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_conclusaonaoconformidade");

                    b.ToTable("conclusaonaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Configuracoes.Gerais.ConfiguracaoGeral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ConsiderarApenasSaldoApontado")
                        .HasColumnType("boolean")
                        .HasColumnName("considerarapenassaldoapontado");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_configuracaogeral");

                    b.ToTable("configuracaogeral", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.DefeitoNaoConformidades.DefeitoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdDefeito")
                        .HasColumnType("uuid")
                        .HasColumnName("iddefeito");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_defeitonaoconformidade");

                    b.ToTable("defeitonaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Defeitos.Defeito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Codigo"), 1L, null, 1L, null, null, null);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid?>("IdCausa")
                        .HasColumnType("uuid")
                        .HasColumnName("idcausa");

                    b.Property<Guid?>("IdSolucao")
                        .HasColumnType("uuid")
                        .HasColumnName("idsolucao");

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isativo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_defeito");

                    b.ToTable("defeito", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.ImplementacaoEvitarReincidenciaNaoConformidades.ImplementacaoEvitarReincidenciaNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcaoImplementada")
                        .HasColumnType("boolean")
                        .HasColumnName("acaoimplementada");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<DateTime?>("DataAnalise")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataanalise");

                    b.Property<DateTime?>("DataPrevistaImplantacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataprevistaimplantacao");

                    b.Property<DateTime?>("DataVerificacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataverificacao");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Descricao")
                        .HasColumnType("bytea")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid?>("IdAuditor")
                        .HasColumnType("uuid")
                        .HasColumnName("idauditor");

                    b.Property<Guid>("IdDefeitoNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("iddefeitonaoconformidade");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<Guid?>("IdResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("idresponsavel");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<DateTime?>("NovaData")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("novadata");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_implementacaoevitarreincidencianaoconformidade");

                    b.HasIndex("IdNaoConformidade")
                        .HasDatabaseName("ix_implementacaoevitarreincidencianaoconformidade_idnaoconform~");

                    b.ToTable("implementacaoevitarreincidencianaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.NaoConformidades.CentroCustoNaoConformidades.CentroCustoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdCentroCusto")
                        .HasColumnType("uuid")
                        .HasColumnName("idcentrocusto");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_centrocustonaoconformidades");

                    b.ToTable("centrocustonaoconformidades", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.NaoConformidades.NaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AceitoConcessao")
                        .HasColumnType("boolean")
                        .HasColumnName("aceitoconcessao");

                    b.Property<string>("CampoNf")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("camponf");

                    b.Property<int?>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datacriacao");

                    b.Property<DateTime?>("DataFabricacaoLote")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datafabricacaolote");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Descricao")
                        .HasColumnType("bytea")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<string>("Equipe")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("equipe");

                    b.Property<Guid>("IdCriador")
                        .HasColumnType("uuid")
                        .HasColumnName("idcriador");

                    b.Property<Guid?>("IdLote")
                        .HasColumnType("uuid")
                        .HasColumnName("idlote");

                    b.Property<Guid>("IdNatureza")
                        .HasColumnType("uuid")
                        .HasColumnName("idnatureza");

                    b.Property<Guid?>("IdNotaFiscal")
                        .HasColumnType("uuid")
                        .HasColumnName("idnotafiscal");

                    b.Property<Guid?>("IdPedido")
                        .HasColumnType("uuid")
                        .HasColumnName("idpedido");

                    b.Property<Guid?>("IdPessoa")
                        .HasColumnType("uuid")
                        .HasColumnName("idpessoa");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("idproduto");

                    b.Property<Guid?>("IdProdutoFaturamento")
                        .HasColumnType("uuid")
                        .HasColumnName("idprodutofaturamento");

                    b.Property<bool>("Incompleta")
                        .HasColumnType("boolean")
                        .HasColumnName("incompleta");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<bool>("LoteParcial")
                        .HasColumnType("boolean")
                        .HasColumnName("loteparcial");

                    b.Property<bool>("LoteTotal")
                        .HasColumnType("boolean")
                        .HasColumnName("lotetotal");

                    b.Property<bool>("MelhoriaEmPotencial")
                        .HasColumnType("boolean")
                        .HasColumnName("melhoriaempotencial");

                    b.Property<bool>("NaoConformidadeEmPotencial")
                        .HasColumnType("boolean")
                        .HasColumnName("naoconformidadeempotencial");

                    b.Property<string>("NumeroLote")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("numerolote");

                    b.Property<string>("NumeroNotaFiscal")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("numeronotafiscal");

                    b.Property<string>("NumeroOdf")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("numeroodf");

                    b.Property<int?>("NumeroOdfAsInt")
                        .HasColumnType("integer")
                        .HasColumnName("numeroodfasint");

                    b.Property<int?>("NumeroOdfFaturamento")
                        .HasColumnType("integer")
                        .HasColumnName("numeroodffaturamento");

                    b.Property<string>("NumeroPedido")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("numeropedido");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<bool>("Rejeitado")
                        .HasColumnType("boolean")
                        .HasColumnName("rejeitado");

                    b.Property<bool>("RelatoNaoConformidade")
                        .HasColumnType("boolean")
                        .HasColumnName("relatonaoconformidade");

                    b.Property<bool>("RetrabalhoNoCliente")
                        .HasColumnType("boolean")
                        .HasColumnName("retrabalhonocliente");

                    b.Property<bool>("RetrabalhoPeloCliente")
                        .HasColumnType("boolean")
                        .HasColumnName("retrabalhopelocliente");

                    b.Property<string>("Revisao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("revisao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_naoconformidade");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_naoconformidade_codigo")
                        .HasFilter("\"isdeleted\" = false");

                    b.ToTable("naoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Naturezas.Natureza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Codigo"), 1L, null, 1L, null, null, null);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isativo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_natureza");

                    b.ToTable("natureza", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.OperacaoRetrabalhoNaoConformidades.OperacaoRetrabalhoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<string>("NumeroOperacaoARetrabalhar")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("numerooperacaoaretrabalhar");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_operacaoretrabalhonaoconformidade");

                    b.HasIndex("IdNaoConformidade")
                        .IsUnique()
                        .HasDatabaseName("ix_operacaoretrabalhonaoconformidade_idnaoconformidade");

                    b.ToTable("operacaoretrabalhonaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.OperacaoRetrabalhoNaoConformidades.Operacoes.Operacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdOperacaoRetrabalhoNaoConformdiade")
                        .HasColumnType("uuid")
                        .HasColumnName("idoperacaoretrabalhonaoconformdiade");

                    b.Property<Guid>("IdRecurso")
                        .HasColumnType("uuid")
                        .HasColumnName("idrecurso");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<string>("NumeroOperacao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("numerooperacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_operacao");

                    b.HasIndex("IdOperacaoRetrabalhoNaoConformdiade")
                        .HasDatabaseName("ix_operacao_idoperacaoretrabalhonaoconformdiade");

                    b.ToTable("operacao", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.OrdemRetrabalhoNaoConformidades.OrdemRetrabalhoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoArmazem")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("codigoarmazem");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datafabricacao");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datavalidade");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid?>("IdEstoqueLocalDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("idestoquelocaldestino");

                    b.Property<Guid>("IdLocalDestino")
                        .HasColumnType("uuid")
                        .HasColumnName("idlocaldestino");

                    b.Property<Guid>("IdLocalOrigem")
                        .HasColumnType("uuid")
                        .HasColumnName("idlocalorigem");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<byte[]>("MovimentacaoEstoqueMensagemRetorno")
                        .HasColumnType("bytea")
                        .HasColumnName("movimentacaoestoquemensagemretorno");

                    b.Property<int>("NumeroOdfRetrabalho")
                        .HasColumnType("integer")
                        .HasColumnName("numeroodfretrabalho");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_ordemretrabalhonaoconformidade");

                    b.HasIndex("IdNaoConformidade")
                        .HasDatabaseName("ix_ordemretrabalhonaoconformidade_idnaoconformidade");

                    b.ToTable("ordemretrabalhonaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.PedidoVendas.PedidoVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<string>("NumeroPedido")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("numeropedido");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_pedidovenda");

                    b.ToTable("pedidovenda", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.ProdutoNaoConformidades.ProdutoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("idproduto");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<byte[]>("OperacaoEngenharia")
                        .HasColumnType("bytea")
                        .HasColumnName("operacaoengenharia");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_produtonaoconformidade");

                    b.ToTable("produtonaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Produtos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid?>("IdCategoria")
                        .HasColumnType("uuid")
                        .HasColumnName("idcategoria");

                    b.Property<Guid>("IdUnidadeMedida")
                        .HasColumnType("uuid")
                        .HasColumnName("idunidademedida");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_produto");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.ReclamacaoNaoConformidades.ReclamacaoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<bool>("DevolucaoFornecedor")
                        .HasColumnType("boolean")
                        .HasColumnName("devolucaofornecedor");

                    b.Property<int>("DisposicaoProdutosAprovados")
                        .HasColumnType("integer")
                        .HasColumnName("disposicaoprodutosaprovados");

                    b.Property<int>("DisposicaoProdutosConcessao")
                        .HasColumnType("integer")
                        .HasColumnName("disposicaoprodutosconcessao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<int>("Improcedentes")
                        .HasColumnType("integer")
                        .HasColumnName("improcedentes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<byte[]>("Observacao")
                        .HasColumnType("bytea")
                        .HasColumnName("observacao");

                    b.Property<int>("Procedentes")
                        .HasColumnType("integer")
                        .HasColumnName("procedentes");

                    b.Property<decimal>("QuantidadeLote")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidadelote");

                    b.Property<decimal>("QuantidadeNaoConformidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidadenaoconformidade");

                    b.Property<bool>("Recodificar")
                        .HasColumnType("boolean")
                        .HasColumnName("recodificar");

                    b.Property<int>("Rejeitado")
                        .HasColumnType("integer")
                        .HasColumnName("rejeitado");

                    b.Property<int>("Retrabalho")
                        .HasColumnType("integer")
                        .HasColumnName("retrabalho");

                    b.Property<bool>("RetrabalhoComOnus")
                        .HasColumnType("boolean")
                        .HasColumnName("retrabalhocomonus");

                    b.Property<bool>("RetrabalhoSemOnus")
                        .HasColumnType("boolean")
                        .HasColumnName("retrabalhosemonus");

                    b.Property<bool>("Sucata")
                        .HasColumnType("boolean")
                        .HasColumnName("sucata");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_reclamacaonaoconformidade");

                    b.ToTable("reclamacaonaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Recursos.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_recurso");

                    b.ToTable("recurso", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.SeederManagers.SeederManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ConverterIdPedidoParaNumeroPedidoSeederFinalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("converteridpedidoparanumeropedidoseederfinalizado");

                    b.Property<bool>("ConverterNumeroOdfParaNumeroOdfAsIntSeederFinalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("converternumeroodfparanumeroodfasintseederfinalizado");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("PreencherCentroCustosSeederFinalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("preenchercentrocustosseederfinalizado");

                    b.Property<bool>("PreencherCodigoRecursosSeederFinalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("preenchercodigorecursosseederfinalizado");

                    b.Property<bool>("PreencherDataCriacaoNaoConformidadeSeederFinalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("preencherdatacriacaonaoconformidadeseederfinalizado");

                    b.Property<bool>("PreencherIdCategoriaProdutosSeederFinalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("preencheridcategoriaprodutosseederfinalizado");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_seedermanager");

                    b.ToTable("seedermanager", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.ServicoNaoConformidades.ServicoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<int>("Horas")
                        .HasColumnType("integer")
                        .HasColumnName("horas");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<Guid?>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("idproduto");

                    b.Property<Guid>("IdRecurso")
                        .HasColumnType("uuid")
                        .HasColumnName("idrecurso");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<int>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos");

                    b.Property<byte[]>("OperacaoEngenharia")
                        .HasColumnType("bytea")
                        .HasColumnName("operacaoengenharia");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_serviconaoconformidade");

                    b.ToTable("serviconaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.SolucaoNaoConformidades.SolucaoNaoConformidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("companyid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<decimal>("CustoEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("custoestimado");

                    b.Property<DateTime?>("DataAnalise")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataanalise");

                    b.Property<DateTime?>("DataPrevistaImplantacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataprevistaimplantacao");

                    b.Property<DateTime?>("DataVerificacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataverificacao");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid?>("IdAuditor")
                        .HasColumnType("uuid")
                        .HasColumnName("idauditor");

                    b.Property<Guid>("IdDefeitoNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("iddefeitonaoconformidade");

                    b.Property<Guid>("IdNaoConformidade")
                        .HasColumnType("uuid")
                        .HasColumnName("idnaoconformidade");

                    b.Property<Guid?>("IdResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("idresponsavel");

                    b.Property<Guid>("IdSolucao")
                        .HasColumnType("uuid")
                        .HasColumnName("idsolucao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<DateTime?>("NovaData")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("novadata");

                    b.Property<bool>("SolucaoImediata")
                        .HasColumnType("boolean")
                        .HasColumnName("solucaoimediata");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_solucaonaoconformidade");

                    b.ToTable("solucaonaoconformidade", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Solucoes.ProdutoSolucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("idproduto");

                    b.Property<Guid>("IdSolucao")
                        .HasColumnType("uuid")
                        .HasColumnName("idsolucao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<byte[]>("OperacaoEngenharia")
                        .HasColumnType("bytea")
                        .HasColumnName("operacaoengenharia");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_produtosolucao");

                    b.ToTable("produtosolucao", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Solucoes.ServicoSolucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<int>("Horas")
                        .HasColumnType("integer")
                        .HasColumnName("horas");

                    b.Property<Guid?>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("idproduto");

                    b.Property<Guid>("IdRecurso")
                        .HasColumnType("uuid")
                        .HasColumnName("idrecurso");

                    b.Property<Guid>("IdSolucao")
                        .HasColumnType("uuid")
                        .HasColumnName("idsolucao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<int>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos");

                    b.Property<byte[]>("OperacaoEngenharia")
                        .HasColumnType("bytea")
                        .HasColumnName("operacaoengenharia");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_servicosolucao");

                    b.ToTable("servicosolucao", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Solucoes.Solucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Codigo"), 1L, null, 1L, null, null, null);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<byte[]>("Detalhamento")
                        .HasColumnType("bytea")
                        .HasColumnName("detalhamento");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("Imediata")
                        .HasColumnType("boolean")
                        .HasColumnName("imediata");

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isativo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_solucao");

                    b.ToTable("solucao", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.UnidadeMedidaProdutos.UnidadeMedidaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<string>("Descricao")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_unidademedidaproduto");

                    b.ToTable("unidademedidaproduto", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creationtime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creatorid");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleterid");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deletiontime");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmentid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("lastmodifierid");

                    b.Property<string>("Nome")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("nome");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("sobrenome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.OperacaoRetrabalhoNaoConformidades.OperacaoRetrabalhoNaoConformidade", b =>
                {
                    b.HasOne("Viasoft.Qualidade.RNC.Core.Domain.NaoConformidades.NaoConformidade", "NaoConformidade")
                        .WithOne("OperacaoRetrabalho")
                        .HasForeignKey("Viasoft.Qualidade.RNC.Core.Domain.OperacaoRetrabalhoNaoConformidades.OperacaoRetrabalhoNaoConformidade", "IdNaoConformidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operacaoretrabalhonaoconformidade_naoconformidade_idnaoconf~");

                    b.Navigation("NaoConformidade");
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.OperacaoRetrabalhoNaoConformidades.Operacoes.Operacao", b =>
                {
                    b.HasOne("Viasoft.Qualidade.RNC.Core.Domain.OperacaoRetrabalhoNaoConformidades.OperacaoRetrabalhoNaoConformidade", "OperacaoRetrabalhoNaoConformidade")
                        .WithMany("Operacoes")
                        .HasForeignKey("IdOperacaoRetrabalhoNaoConformdiade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operacao_operacaoretrabalhonaoconformidade_idoperacaoretrab~");

                    b.Navigation("OperacaoRetrabalhoNaoConformidade");
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.NaoConformidades.NaoConformidade", b =>
                {
                    b.Navigation("OperacaoRetrabalho");
                });

            modelBuilder.Entity("Viasoft.Qualidade.RNC.Core.Domain.OperacaoRetrabalhoNaoConformidades.OperacaoRetrabalhoNaoConformidade", b =>
                {
                    b.Navigation("Operacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
