// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IInspecaoSaidaItemRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/entities"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoSaidaItemRepository is a mock of IInspecaoSaidaItemRepository interface.
type MockIInspecaoSaidaItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoSaidaItemRepositoryMockRecorder
}

// MockIInspecaoSaidaItemRepositoryMockRecorder is the mock recorder for MockIInspecaoSaidaItemRepository.
type MockIInspecaoSaidaItemRepositoryMockRecorder struct {
	mock *MockIInspecaoSaidaItemRepository
}

// NewMockIInspecaoSaidaItemRepository creates a new mock instance.
func NewMockIInspecaoSaidaItemRepository(ctrl *gomock.Controller) *MockIInspecaoSaidaItemRepository {
	mock := &MockIInspecaoSaidaItemRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoSaidaItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoSaidaItemRepository) EXPECT() *MockIInspecaoSaidaItemRepositoryMockRecorder {
	return m.recorder
}

// AtualizarInspecaoSaidaItens mocks base method.
func (m *MockIInspecaoSaidaItemRepository) AtualizarInspecaoSaidaItens(arg0 []*entities.InspecaoSaidaItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarInspecaoSaidaItens", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarInspecaoSaidaItens indicates an expected call of AtualizarInspecaoSaidaItens.
func (mr *MockIInspecaoSaidaItemRepositoryMockRecorder) AtualizarInspecaoSaidaItens(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarInspecaoSaidaItens", reflect.TypeOf((*MockIInspecaoSaidaItemRepository)(nil).AtualizarInspecaoSaidaItens), arg0)
}

// BuscarInspecaoSaidaItensEntitiesPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaItemRepository) BuscarInspecaoSaidaItensEntitiesPeloCodigo(arg0 int) ([]*entities.InspecaoSaidaItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaItensEntitiesPeloCodigo", arg0)
	ret0, _ := ret[0].([]*entities.InspecaoSaidaItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoSaidaItensEntitiesPeloCodigo indicates an expected call of BuscarInspecaoSaidaItensEntitiesPeloCodigo.
func (mr *MockIInspecaoSaidaItemRepositoryMockRecorder) BuscarInspecaoSaidaItensEntitiesPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaItensEntitiesPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaItemRepository)(nil).BuscarInspecaoSaidaItensEntitiesPeloCodigo), arg0)
}

// BuscarInspecaoSaidaItensPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaItemRepository) BuscarInspecaoSaidaItensPeloCodigo(arg0 int, arg1 *models.BaseFilter) ([]*models.InspecaoSaidaItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaItensPeloCodigo", arg0, arg1)
	ret0, _ := ret[0].([]*models.InspecaoSaidaItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoSaidaItensPeloCodigo indicates an expected call of BuscarInspecaoSaidaItensPeloCodigo.
func (mr *MockIInspecaoSaidaItemRepositoryMockRecorder) BuscarInspecaoSaidaItensPeloCodigo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaItemRepository)(nil).BuscarInspecaoSaidaItensPeloCodigo), arg0, arg1)
}

// BuscarQuantidadeInspecaoSaidaItensPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaItemRepository) BuscarQuantidadeInspecaoSaidaItensPeloCodigo(arg0 int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeInspecaoSaidaItensPeloCodigo", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeInspecaoSaidaItensPeloCodigo indicates an expected call of BuscarQuantidadeInspecaoSaidaItensPeloCodigo.
func (mr *MockIInspecaoSaidaItemRepositoryMockRecorder) BuscarQuantidadeInspecaoSaidaItensPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeInspecaoSaidaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaItemRepository)(nil).BuscarQuantidadeInspecaoSaidaItensPeloCodigo), arg0)
}

// CriarItensInspecao mocks base method.
func (m *MockIInspecaoSaidaItemRepository) CriarItensInspecao(arg0 []*models.InspecaoSaidaItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CriarItensInspecao", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CriarItensInspecao indicates an expected call of CriarItensInspecao.
func (mr *MockIInspecaoSaidaItemRepositoryMockRecorder) CriarItensInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CriarItensInspecao", reflect.TypeOf((*MockIInspecaoSaidaItemRepository)(nil).CriarItensInspecao), arg0)
}

// RemoverInspecaoSaidaItensPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaItemRepository) RemoverInspecaoSaidaItensPeloCodigo(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverInspecaoSaidaItensPeloCodigo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverInspecaoSaidaItensPeloCodigo indicates an expected call of RemoverInspecaoSaidaItensPeloCodigo.
func (mr *MockIInspecaoSaidaItemRepositoryMockRecorder) RemoverInspecaoSaidaItensPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverInspecaoSaidaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaItemRepository)(nil).RemoverInspecaoSaidaItensPeloCodigo), arg0)
}
