// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IEmpresaRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIEmpresaRepository is a mock of IEmpresaRepository interface.
type MockIEmpresaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIEmpresaRepositoryMockRecorder
}

// MockIEmpresaRepositoryMockRecorder is the mock recorder for MockIEmpresaRepository.
type MockIEmpresaRepositoryMockRecorder struct {
	mock *MockIEmpresaRepository
}

// NewMockIEmpresaRepository creates a new mock instance.
func NewMockIEmpresaRepository(ctrl *gomock.Controller) *MockIEmpresaRepository {
	mock := &MockIEmpresaRepository{ctrl: ctrl}
	mock.recorder = &MockIEmpresaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEmpresaRepository) EXPECT() *MockIEmpresaRepositoryMockRecorder {
	return m.recorder
}

// BuscarLogo mocks base method.
func (m *MockIEmpresaRepository) BuscarLogo(arg0 int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarLogo", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarLogo indicates an expected call of BuscarLogo.
func (mr *MockIEmpresaRepositoryMockRecorder) BuscarLogo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarLogo", reflect.TypeOf((*MockIEmpresaRepository)(nil).BuscarLogo), arg0)
}
