// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IExternalInspecaoSaidaSagaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockIExternalInspecaoSaidaSagaService is a mock of IExternalInspecaoSaidaSagaService interface.
type MockIExternalInspecaoSaidaSagaService struct {
	ctrl     *gomock.Controller
	recorder *MockIExternalInspecaoSaidaSagaServiceMockRecorder
}

// MockIExternalInspecaoSaidaSagaServiceMockRecorder is the mock recorder for MockIExternalInspecaoSaidaSagaService.
type MockIExternalInspecaoSaidaSagaServiceMockRecorder struct {
	mock *MockIExternalInspecaoSaidaSagaService
}

// NewMockIExternalInspecaoSaidaSagaService creates a new mock instance.
func NewMockIExternalInspecaoSaidaSagaService(ctrl *gomock.Controller) *MockIExternalInspecaoSaidaSagaService {
	mock := &MockIExternalInspecaoSaidaSagaService{ctrl: ctrl}
	mock.recorder = &MockIExternalInspecaoSaidaSagaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExternalInspecaoSaidaSagaService) EXPECT() *MockIExternalInspecaoSaidaSagaServiceMockRecorder {
	return m.recorder
}

// BuscarSaga mocks base method.
func (m *MockIExternalInspecaoSaidaSagaService) BuscarSaga(arg0 string) (*dto.SagaInspecaoSaidaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSaga", arg0)
	ret0, _ := ret[0].(*dto.SagaInspecaoSaidaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSaga indicates an expected call of BuscarSaga.
func (mr *MockIExternalInspecaoSaidaSagaServiceMockRecorder) BuscarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSaga", reflect.TypeOf((*MockIExternalInspecaoSaidaSagaService)(nil).BuscarSaga), arg0)
}

// BuscarSagas mocks base method.
func (m *MockIExternalInspecaoSaidaSagaService) BuscarSagas(arg0, arg1 int, arg2 *dto.ProcessamentoInspecaoSaidaFilters, arg3 bool) (*dto.GetAllSagaInspecaoSaidaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSagas", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.GetAllSagaInspecaoSaidaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSagas indicates an expected call of BuscarSagas.
func (mr *MockIExternalInspecaoSaidaSagaServiceMockRecorder) BuscarSagas(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSagas", reflect.TypeOf((*MockIExternalInspecaoSaidaSagaService)(nil).BuscarSagas), arg0, arg1, arg2, arg3)
}

// PublicarSaga mocks base method.
func (m *MockIExternalInspecaoSaidaSagaService) PublicarSaga(arg0 interface{}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicarSaga", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicarSaga indicates an expected call of PublicarSaga.
func (mr *MockIExternalInspecaoSaidaSagaServiceMockRecorder) PublicarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicarSaga", reflect.TypeOf((*MockIExternalInspecaoSaidaSagaService)(nil).PublicarSaga), arg0)
}

// RemoverSaga mocks base method.
func (m *MockIExternalInspecaoSaidaSagaService) RemoverSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverSaga indicates an expected call of RemoverSaga.
func (mr *MockIExternalInspecaoSaidaSagaServiceMockRecorder) RemoverSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverSaga", reflect.TypeOf((*MockIExternalInspecaoSaidaSagaService)(nil).RemoverSaga), arg0)
}

// ReprocessarSaga mocks base method.
func (m *MockIExternalInspecaoSaidaSagaService) ReprocessarSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessarSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReprocessarSaga indicates an expected call of ReprocessarSaga.
func (mr *MockIExternalInspecaoSaidaSagaServiceMockRecorder) ReprocessarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessarSaga", reflect.TypeOf((*MockIExternalInspecaoSaidaSagaService)(nil).ReprocessarSaga), arg0)
}
