// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IInspecaoSaidaHistoricoService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoSaidaHistoricoService is a mock of IInspecaoSaidaHistoricoService interface.
type MockIInspecaoSaidaHistoricoService struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoSaidaHistoricoServiceMockRecorder
}

// MockIInspecaoSaidaHistoricoServiceMockRecorder is the mock recorder for MockIInspecaoSaidaHistoricoService.
type MockIInspecaoSaidaHistoricoServiceMockRecorder struct {
	mock *MockIInspecaoSaidaHistoricoService
}

// NewMockIInspecaoSaidaHistoricoService creates a new mock instance.
func NewMockIInspecaoSaidaHistoricoService(ctrl *gomock.Controller) *MockIInspecaoSaidaHistoricoService {
	mock := &MockIInspecaoSaidaHistoricoService{ctrl: ctrl}
	mock.recorder = &MockIInspecaoSaidaHistoricoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoSaidaHistoricoService) EXPECT() *MockIInspecaoSaidaHistoricoServiceMockRecorder {
	return m.recorder
}

// GetAllInspecaoSaidaHistoricoCabecalho mocks base method.
func (m *MockIInspecaoSaidaHistoricoService) GetAllInspecaoSaidaHistoricoCabecalho(arg0 *models.BaseFilter, arg1 *dto.InspecaoSaidaHistoricoCabecalhoFilters) (*dto.GetAllInspecaoSaidaHistoricoCabecalhoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInspecaoSaidaHistoricoCabecalho", arg0, arg1)
	ret0, _ := ret[0].(*dto.GetAllInspecaoSaidaHistoricoCabecalhoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInspecaoSaidaHistoricoCabecalho indicates an expected call of GetAllInspecaoSaidaHistoricoCabecalho.
func (mr *MockIInspecaoSaidaHistoricoServiceMockRecorder) GetAllInspecaoSaidaHistoricoCabecalho(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInspecaoSaidaHistoricoCabecalho", reflect.TypeOf((*MockIInspecaoSaidaHistoricoService)(nil).GetAllInspecaoSaidaHistoricoCabecalho), arg0, arg1)
}

// GetAllInspecaoSaidaHistoricoItems mocks base method.
func (m *MockIInspecaoSaidaHistoricoService) GetAllInspecaoSaidaHistoricoItems(arg0 *models.BaseFilter, arg1 *dto.InspecaoSaidaHistoricoCabecalhoFilters, arg2, arg3 int) (*dto.GetAllInspecaoSaidaHistoricoItemsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInspecaoSaidaHistoricoItems", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.GetAllInspecaoSaidaHistoricoItemsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInspecaoSaidaHistoricoItems indicates an expected call of GetAllInspecaoSaidaHistoricoItems.
func (mr *MockIInspecaoSaidaHistoricoServiceMockRecorder) GetAllInspecaoSaidaHistoricoItems(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInspecaoSaidaHistoricoItems", reflect.TypeOf((*MockIInspecaoSaidaHistoricoService)(nil).GetAllInspecaoSaidaHistoricoItems), arg0, arg1, arg2, arg3)
}
