// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IInspecaoSaidaHistoricoRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoSaidaHistoricoRepository is a mock of IInspecaoSaidaHistoricoRepository interface.
type MockIInspecaoSaidaHistoricoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoSaidaHistoricoRepositoryMockRecorder
}

// MockIInspecaoSaidaHistoricoRepositoryMockRecorder is the mock recorder for MockIInspecaoSaidaHistoricoRepository.
type MockIInspecaoSaidaHistoricoRepositoryMockRecorder struct {
	mock *MockIInspecaoSaidaHistoricoRepository
}

// NewMockIInspecaoSaidaHistoricoRepository creates a new mock instance.
func NewMockIInspecaoSaidaHistoricoRepository(ctrl *gomock.Controller) *MockIInspecaoSaidaHistoricoRepository {
	mock := &MockIInspecaoSaidaHistoricoRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoSaidaHistoricoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoSaidaHistoricoRepository) EXPECT() *MockIInspecaoSaidaHistoricoRepositoryMockRecorder {
	return m.recorder
}

// CountInspecaoSaidaHistoricoCabecalho mocks base method.
func (m *MockIInspecaoSaidaHistoricoRepository) CountInspecaoSaidaHistoricoCabecalho(arg0 *models.BaseFilter, arg1 *dto.InspecaoSaidaHistoricoCabecalhoFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInspecaoSaidaHistoricoCabecalho", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInspecaoSaidaHistoricoCabecalho indicates an expected call of CountInspecaoSaidaHistoricoCabecalho.
func (mr *MockIInspecaoSaidaHistoricoRepositoryMockRecorder) CountInspecaoSaidaHistoricoCabecalho(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInspecaoSaidaHistoricoCabecalho", reflect.TypeOf((*MockIInspecaoSaidaHistoricoRepository)(nil).CountInspecaoSaidaHistoricoCabecalho), arg0, arg1)
}

// CountInspecaoSaidaHistoricoItems mocks base method.
func (m *MockIInspecaoSaidaHistoricoRepository) CountInspecaoSaidaHistoricoItems(arg0 *models.BaseFilter, arg1 *dto.InspecaoSaidaHistoricoCabecalhoFilters, arg2, arg3 int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInspecaoSaidaHistoricoItems", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInspecaoSaidaHistoricoItems indicates an expected call of CountInspecaoSaidaHistoricoItems.
func (mr *MockIInspecaoSaidaHistoricoRepositoryMockRecorder) CountInspecaoSaidaHistoricoItems(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInspecaoSaidaHistoricoItems", reflect.TypeOf((*MockIInspecaoSaidaHistoricoRepository)(nil).CountInspecaoSaidaHistoricoItems), arg0, arg1, arg2, arg3)
}

// GetAllInspecaoSaidaHistoricoCabecalho mocks base method.
func (m *MockIInspecaoSaidaHistoricoRepository) GetAllInspecaoSaidaHistoricoCabecalho(arg0 *models.BaseFilter, arg1 *dto.InspecaoSaidaHistoricoCabecalhoFilters) ([]dto.InspecaoSaidaHistoricoCabecalhoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInspecaoSaidaHistoricoCabecalho", arg0, arg1)
	ret0, _ := ret[0].([]dto.InspecaoSaidaHistoricoCabecalhoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInspecaoSaidaHistoricoCabecalho indicates an expected call of GetAllInspecaoSaidaHistoricoCabecalho.
func (mr *MockIInspecaoSaidaHistoricoRepositoryMockRecorder) GetAllInspecaoSaidaHistoricoCabecalho(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInspecaoSaidaHistoricoCabecalho", reflect.TypeOf((*MockIInspecaoSaidaHistoricoRepository)(nil).GetAllInspecaoSaidaHistoricoCabecalho), arg0, arg1)
}

// GetAllInspecaoSaidaHistoricoItems mocks base method.
func (m *MockIInspecaoSaidaHistoricoRepository) GetAllInspecaoSaidaHistoricoItems(arg0 *models.BaseFilter, arg1 *dto.InspecaoSaidaHistoricoCabecalhoFilters, arg2, arg3 int) ([]dto.InspecaoSaidaHistoricoItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllInspecaoSaidaHistoricoItems", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]dto.InspecaoSaidaHistoricoItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllInspecaoSaidaHistoricoItems indicates an expected call of GetAllInspecaoSaidaHistoricoItems.
func (mr *MockIInspecaoSaidaHistoricoRepositoryMockRecorder) GetAllInspecaoSaidaHistoricoItems(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllInspecaoSaidaHistoricoItems", reflect.TypeOf((*MockIInspecaoSaidaHistoricoRepository)(nil).GetAllInspecaoSaidaHistoricoItems), arg0, arg1, arg2, arg3)
}
