// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IProdutoRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIProdutoRepository is a mock of IProdutoRepository interface.
type MockIProdutoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIProdutoRepositoryMockRecorder
}

// MockIProdutoRepositoryMockRecorder is the mock recorder for MockIProdutoRepository.
type MockIProdutoRepositoryMockRecorder struct {
	mock *MockIProdutoRepository
}

// NewMockIProdutoRepository creates a new mock instance.
func NewMockIProdutoRepository(ctrl *gomock.Controller) *MockIProdutoRepository {
	mock := &MockIProdutoRepository{ctrl: ctrl}
	mock.recorder = &MockIProdutoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProdutoRepository) EXPECT() *MockIProdutoRepositoryMockRecorder {
	return m.recorder
}

// BuscarProdutoDescricao mocks base method.
func (m *MockIProdutoRepository) BuscarProdutoDescricao(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutoDescricao", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutoDescricao indicates an expected call of BuscarProdutoDescricao.
func (mr *MockIProdutoRepositoryMockRecorder) BuscarProdutoDescricao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutoDescricao", reflect.TypeOf((*MockIProdutoRepository)(nil).BuscarProdutoDescricao), arg0)
}

// BuscarProdutoPeloCodigo mocks base method.
func (m *MockIProdutoRepository) BuscarProdutoPeloCodigo(arg0 string) (*dto.ProdutoOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutoPeloCodigo", arg0)
	ret0, _ := ret[0].(*dto.ProdutoOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutoPeloCodigo indicates an expected call of BuscarProdutoPeloCodigo.
func (mr *MockIProdutoRepositoryMockRecorder) BuscarProdutoPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutoPeloCodigo", reflect.TypeOf((*MockIProdutoRepository)(nil).BuscarProdutoPeloCodigo), arg0)
}

// BuscarProdutos mocks base method.
func (m *MockIProdutoRepository) BuscarProdutos(arg0 *models.BaseFilter) ([]dto.ProdutoOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutos", arg0)
	ret0, _ := ret[0].([]dto.ProdutoOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutos indicates an expected call of BuscarProdutos.
func (mr *MockIProdutoRepositoryMockRecorder) BuscarProdutos(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutos", reflect.TypeOf((*MockIProdutoRepository)(nil).BuscarProdutos), arg0)
}

// BuscarProdutosTotalCount mocks base method.
func (m *MockIProdutoRepository) BuscarProdutosTotalCount(arg0 *models.BaseFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutosTotalCount", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutosTotalCount indicates an expected call of BuscarProdutosTotalCount.
func (mr *MockIProdutoRepositoryMockRecorder) BuscarProdutosTotalCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutosTotalCount", reflect.TypeOf((*MockIProdutoRepository)(nil).BuscarProdutosTotalCount), arg0)
}
