// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IOrdemProducaoRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIOrdemProducaoRepository is a mock of IOrdemProducaoRepository interface.
type MockIOrdemProducaoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOrdemProducaoRepositoryMockRecorder
}

// MockIOrdemProducaoRepositoryMockRecorder is the mock recorder for MockIOrdemProducaoRepository.
type MockIOrdemProducaoRepositoryMockRecorder struct {
	mock *MockIOrdemProducaoRepository
}

// NewMockIOrdemProducaoRepository creates a new mock instance.
func NewMockIOrdemProducaoRepository(ctrl *gomock.Controller) *MockIOrdemProducaoRepository {
	mock := &MockIOrdemProducaoRepository{ctrl: ctrl}
	mock.recorder = &MockIOrdemProducaoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOrdemProducaoRepository) EXPECT() *MockIOrdemProducaoRepositoryMockRecorder {
	return m.recorder
}

// BuscarOrdem mocks base method.
func (m *MockIOrdemProducaoRepository) BuscarOrdem(arg0 int) *models.OrdemProducao {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarOrdem", arg0)
	ret0, _ := ret[0].(*models.OrdemProducao)
	return ret0
}

// BuscarOrdem indicates an expected call of BuscarOrdem.
func (mr *MockIOrdemProducaoRepositoryMockRecorder) BuscarOrdem(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarOrdem", reflect.TypeOf((*MockIOrdemProducaoRepository)(nil).BuscarOrdem), arg0)
}

// BuscarOrdemPaiHistoricoMovimentacao mocks base method.
func (m *MockIOrdemProducaoRepository) BuscarOrdemPaiHistoricoMovimentacao(arg0, arg1 string, arg2 int) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarOrdemPaiHistoricoMovimentacao", arg0, arg1, arg2)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarOrdemPaiHistoricoMovimentacao indicates an expected call of BuscarOrdemPaiHistoricoMovimentacao.
func (mr *MockIOrdemProducaoRepositoryMockRecorder) BuscarOrdemPaiHistoricoMovimentacao(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarOrdemPaiHistoricoMovimentacao", reflect.TypeOf((*MockIOrdemProducaoRepository)(nil).BuscarOrdemPaiHistoricoMovimentacao), arg0, arg1, arg2)
}

// BuscarOrdensInspecao mocks base method.
func (m *MockIOrdemProducaoRepository) BuscarOrdensInspecao(arg0 *models.BaseFilter, arg1 *dto.OrdemProducaoFilters) ([]models.OrdemProducao, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarOrdensInspecao", arg0, arg1)
	ret0, _ := ret[0].([]models.OrdemProducao)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarOrdensInspecao indicates an expected call of BuscarOrdensInspecao.
func (mr *MockIOrdemProducaoRepositoryMockRecorder) BuscarOrdensInspecao(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarOrdensInspecao", reflect.TypeOf((*MockIOrdemProducaoRepository)(nil).BuscarOrdensInspecao), arg0, arg1)
}

// BuscarQuantidadeOrdensInspecao mocks base method.
func (m *MockIOrdemProducaoRepository) BuscarQuantidadeOrdensInspecao(arg0 *models.BaseFilter, arg1 *dto.OrdemProducaoFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeOrdensInspecao", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeOrdensInspecao indicates an expected call of BuscarQuantidadeOrdensInspecao.
func (mr *MockIOrdemProducaoRepositoryMockRecorder) BuscarQuantidadeOrdensInspecao(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeOrdensInspecao", reflect.TypeOf((*MockIOrdemProducaoRepository)(nil).BuscarQuantidadeOrdensInspecao), arg0, arg1)
}
