// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IInspecaoSaidaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoSaidaService is a mock of IInspecaoSaidaService interface.
type MockIInspecaoSaidaService struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoSaidaServiceMockRecorder
}

// MockIInspecaoSaidaServiceMockRecorder is the mock recorder for MockIInspecaoSaidaService.
type MockIInspecaoSaidaServiceMockRecorder struct {
	mock *MockIInspecaoSaidaService
}

// NewMockIInspecaoSaidaService creates a new mock instance.
func NewMockIInspecaoSaidaService(ctrl *gomock.Controller) *MockIInspecaoSaidaService {
	mock := &MockIInspecaoSaidaService{ctrl: ctrl}
	mock.recorder = &MockIInspecaoSaidaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoSaidaService) EXPECT() *MockIInspecaoSaidaServiceMockRecorder {
	return m.recorder
}

// AtualizarInspecao mocks base method.
func (m *MockIInspecaoSaidaService) AtualizarInspecao(arg0 *dto.AtualizarInspecaoInput) *dto.ValidacaoDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarInspecao", arg0)
	ret0, _ := ret[0].(*dto.ValidacaoDTO)
	return ret0
}

// AtualizarInspecao indicates an expected call of AtualizarInspecao.
func (mr *MockIInspecaoSaidaServiceMockRecorder) AtualizarInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarInspecao", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).AtualizarInspecao), arg0)
}

// BuscarInspecaoSaidaItensPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaService) BuscarInspecaoSaidaItensPeloCodigo(arg0 int, arg1 *models.BaseFilter) (*dto.GetInspecaoSaidaItensDTO, *dto.ValidacaoDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaItensPeloCodigo", arg0, arg1)
	ret0, _ := ret[0].(*dto.GetInspecaoSaidaItensDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	return ret0, ret1
}

// BuscarInspecaoSaidaItensPeloCodigo indicates an expected call of BuscarInspecaoSaidaItensPeloCodigo.
func (mr *MockIInspecaoSaidaServiceMockRecorder) BuscarInspecaoSaidaItensPeloCodigo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaItensPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).BuscarInspecaoSaidaItensPeloCodigo), arg0, arg1)
}

// BuscarInspecaoSaidaPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaService) BuscarInspecaoSaidaPeloCodigo(arg0 int) (*dto.InspecaoSaidaDTO, *dto.ValidacaoDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaPeloCodigo", arg0)
	ret0, _ := ret[0].(*dto.InspecaoSaidaDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	return ret0, ret1
}

// BuscarInspecaoSaidaPeloCodigo indicates an expected call of BuscarInspecaoSaidaPeloCodigo.
func (mr *MockIInspecaoSaidaServiceMockRecorder) BuscarInspecaoSaidaPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).BuscarInspecaoSaidaPeloCodigo), arg0)
}

// BuscarInspecoesSaida mocks base method.
func (m *MockIInspecaoSaidaService) BuscarInspecoesSaida(arg0 int, arg1 *models.BaseFilter, arg2 *dto.InspecaoSaidaFilters) (*dto.GetInspecaoSaidaDTO, *dto.ValidacaoDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecoesSaida", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.GetInspecaoSaidaDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	return ret0, ret1
}

// BuscarInspecoesSaida indicates an expected call of BuscarInspecoesSaida.
func (mr *MockIInspecaoSaidaServiceMockRecorder) BuscarInspecoesSaida(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecoesSaida", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).BuscarInspecoesSaida), arg0, arg1, arg2)
}

// BuscarPlanosNovaInspecao mocks base method.
func (m *MockIInspecaoSaidaService) BuscarPlanosNovaInspecao(arg0 int, arg1 string, arg2 *models.BaseFilter) (*dto.GetPlanosInspecaoDTO, *dto.ValidacaoDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarPlanosNovaInspecao", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.GetPlanosInspecaoDTO)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	return ret0, ret1
}

// BuscarPlanosNovaInspecao indicates an expected call of BuscarPlanosNovaInspecao.
func (mr *MockIInspecaoSaidaServiceMockRecorder) BuscarPlanosNovaInspecao(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarPlanosNovaInspecao", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).BuscarPlanosNovaInspecao), arg0, arg1, arg2)
}

// BuscarResultadoInspecao mocks base method.
func (m *MockIInspecaoSaidaService) BuscarResultadoInspecao(arg0 int) (string, *dto.ValidacaoDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarResultadoInspecao", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	return ret0, ret1
}

// BuscarResultadoInspecao indicates an expected call of BuscarResultadoInspecao.
func (mr *MockIInspecaoSaidaServiceMockRecorder) BuscarResultadoInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarResultadoInspecao", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).BuscarResultadoInspecao), arg0)
}

// CriarInspecao mocks base method.
func (m *MockIInspecaoSaidaService) CriarInspecao(arg0 *dto.NovaInspecaoInput) (*models.InspecaoSaida, *dto.ValidacaoDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CriarInspecao", arg0)
	ret0, _ := ret[0].(*models.InspecaoSaida)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	return ret0, ret1
}

// CriarInspecao indicates an expected call of CriarInspecao.
func (mr *MockIInspecaoSaidaServiceMockRecorder) CriarInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CriarInspecao", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).CriarInspecao), arg0)
}

// ImprimirInspecaoSaida mocks base method.
func (m *MockIInspecaoSaidaService) ImprimirInspecaoSaida(arg0 int) ([]byte, *dto.ValidacaoDTO) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImprimirInspecaoSaida", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	return ret0, ret1
}

// ImprimirInspecaoSaida indicates an expected call of ImprimirInspecaoSaida.
func (mr *MockIInspecaoSaidaServiceMockRecorder) ImprimirInspecaoSaida(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImprimirInspecaoSaida", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).ImprimirInspecaoSaida), arg0)
}

// RemoverInspecaoSaidaPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaService) RemoverInspecaoSaidaPeloCodigo(arg0 int) *dto.ValidacaoDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverInspecaoSaidaPeloCodigo", arg0)
	ret0, _ := ret[0].(*dto.ValidacaoDTO)
	return ret0
}

// RemoverInspecaoSaidaPeloCodigo indicates an expected call of RemoverInspecaoSaidaPeloCodigo.
func (mr *MockIInspecaoSaidaServiceMockRecorder) RemoverInspecaoSaidaPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverInspecaoSaidaPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaService)(nil).RemoverInspecaoSaidaPeloCodigo), arg0)
}
