// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IParametroRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIParametroRepository is a mock of IParametroRepository interface.
type MockIParametroRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIParametroRepositoryMockRecorder
}

// MockIParametroRepositoryMockRecorder is the mock recorder for MockIParametroRepository.
type MockIParametroRepositoryMockRecorder struct {
	mock *MockIParametroRepository
}

// NewMockIParametroRepository creates a new mock instance.
func NewMockIParametroRepository(ctrl *gomock.Controller) *MockIParametroRepository {
	mock := &MockIParametroRepository{ctrl: ctrl}
	mock.recorder = &MockIParametroRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIParametroRepository) EXPECT() *MockIParametroRepositoryMockRecorder {
	return m.recorder
}

// BuscarParametroBool mocks base method.
func (m *MockIParametroRepository) BuscarParametroBool(arg0, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarParametroBool", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarParametroBool indicates an expected call of BuscarParametroBool.
func (mr *MockIParametroRepositoryMockRecorder) BuscarParametroBool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarParametroBool", reflect.TypeOf((*MockIParametroRepository)(nil).BuscarParametroBool), arg0, arg1)
}
