// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IInspecaoSaidaExecutadoWebRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoSaidaExecutadoWebRepository is a mock of IInspecaoSaidaExecutadoWebRepository interface.
type MockIInspecaoSaidaExecutadoWebRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder
}

// MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder is the mock recorder for MockIInspecaoSaidaExecutadoWebRepository.
type MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder struct {
	mock *MockIInspecaoSaidaExecutadoWebRepository
}

// NewMockIInspecaoSaidaExecutadoWebRepository creates a new mock instance.
func NewMockIInspecaoSaidaExecutadoWebRepository(ctrl *gomock.Controller) *MockIInspecaoSaidaExecutadoWebRepository {
	mock := &MockIInspecaoSaidaExecutadoWebRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoSaidaExecutadoWebRepository) EXPECT() *MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder {
	return m.recorder
}

// BuscarInspecaoSaidaExecutadoWeb mocks base method.
func (m *MockIInspecaoSaidaExecutadoWebRepository) BuscarInspecaoSaidaExecutadoWeb(arg0 int) (*entities.InspecaoSaidaExecutadoWeb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaExecutadoWeb", arg0)
	ret0, _ := ret[0].(*entities.InspecaoSaidaExecutadoWeb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoSaidaExecutadoWeb indicates an expected call of BuscarInspecaoSaidaExecutadoWeb.
func (mr *MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder) BuscarInspecaoSaidaExecutadoWeb(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaExecutadoWeb", reflect.TypeOf((*MockIInspecaoSaidaExecutadoWebRepository)(nil).BuscarInspecaoSaidaExecutadoWeb), arg0)
}

// InserirInspecaoSaidaExecutadoWeb mocks base method.
func (m *MockIInspecaoSaidaExecutadoWebRepository) InserirInspecaoSaidaExecutadoWeb(arg0 *entities.InspecaoSaidaExecutadoWeb) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InserirInspecaoSaidaExecutadoWeb", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// InserirInspecaoSaidaExecutadoWeb indicates an expected call of InserirInspecaoSaidaExecutadoWeb.
func (mr *MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder) InserirInspecaoSaidaExecutadoWeb(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InserirInspecaoSaidaExecutadoWeb", reflect.TypeOf((*MockIInspecaoSaidaExecutadoWebRepository)(nil).InserirInspecaoSaidaExecutadoWeb), arg0)
}

// RemoverSaga mocks base method.
func (m *MockIInspecaoSaidaExecutadoWebRepository) RemoverSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverSaga indicates an expected call of RemoverSaga.
func (mr *MockIInspecaoSaidaExecutadoWebRepositoryMockRecorder) RemoverSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverSaga", reflect.TypeOf((*MockIInspecaoSaidaExecutadoWebRepository)(nil).RemoverSaga), arg0)
}
