// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IInspecaoSaidaSagaService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoSaidaSagaService is a mock of IInspecaoSaidaSagaService interface.
type MockIInspecaoSaidaSagaService struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoSaidaSagaServiceMockRecorder
}

// MockIInspecaoSaidaSagaServiceMockRecorder is the mock recorder for MockIInspecaoSaidaSagaService.
type MockIInspecaoSaidaSagaServiceMockRecorder struct {
	mock *MockIInspecaoSaidaSagaService
}

// NewMockIInspecaoSaidaSagaService creates a new mock instance.
func NewMockIInspecaoSaidaSagaService(ctrl *gomock.Controller) *MockIInspecaoSaidaSagaService {
	mock := &MockIInspecaoSaidaSagaService{ctrl: ctrl}
	mock.recorder = &MockIInspecaoSaidaSagaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoSaidaSagaService) EXPECT() *MockIInspecaoSaidaSagaServiceMockRecorder {
	return m.recorder
}

// BuscarSagas mocks base method.
func (m *MockIInspecaoSaidaSagaService) BuscarSagas(arg0 *models.BaseFilter, arg1 *dto.ProcessamentoInspecaoSaidaFilters, arg2 bool) (*dto.GetAllProcessamentoInspecaoSaidaOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSagas", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.GetAllProcessamentoInspecaoSaidaOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSagas indicates an expected call of BuscarSagas.
func (mr *MockIInspecaoSaidaSagaServiceMockRecorder) BuscarSagas(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSagas", reflect.TypeOf((*MockIInspecaoSaidaSagaService)(nil).BuscarSagas), arg0, arg1, arg2)
}

// PublicarSagaInspecaoSaida mocks base method.
func (m *MockIInspecaoSaidaSagaService) PublicarSagaInspecaoSaida(arg0 *dto.FinalizarInspecaoInput) (bool, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicarSagaInspecaoSaida", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PublicarSagaInspecaoSaida indicates an expected call of PublicarSagaInspecaoSaida.
func (mr *MockIInspecaoSaidaSagaServiceMockRecorder) PublicarSagaInspecaoSaida(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicarSagaInspecaoSaida", reflect.TypeOf((*MockIInspecaoSaidaSagaService)(nil).PublicarSagaInspecaoSaida), arg0)
}

// PublicarSagaInspecaoSaidaEstorno mocks base method.
func (m *MockIInspecaoSaidaSagaService) PublicarSagaInspecaoSaidaEstorno(arg0 int) (bool, *dto.ValidacaoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicarSagaInspecaoSaidaEstorno", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*dto.ValidacaoDTO)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PublicarSagaInspecaoSaidaEstorno indicates an expected call of PublicarSagaInspecaoSaidaEstorno.
func (mr *MockIInspecaoSaidaSagaServiceMockRecorder) PublicarSagaInspecaoSaidaEstorno(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicarSagaInspecaoSaidaEstorno", reflect.TypeOf((*MockIInspecaoSaidaSagaService)(nil).PublicarSagaInspecaoSaidaEstorno), arg0)
}

// RemoverSaga mocks base method.
func (m *MockIInspecaoSaidaSagaService) RemoverSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverSaga indicates an expected call of RemoverSaga.
func (mr *MockIInspecaoSaidaSagaServiceMockRecorder) RemoverSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverSaga", reflect.TypeOf((*MockIInspecaoSaidaSagaService)(nil).RemoverSaga), arg0)
}

// ReprocessarSaga mocks base method.
func (m *MockIInspecaoSaidaSagaService) ReprocessarSaga(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReprocessarSaga", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReprocessarSaga indicates an expected call of ReprocessarSaga.
func (mr *MockIInspecaoSaidaSagaServiceMockRecorder) ReprocessarSaga(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReprocessarSaga", reflect.TypeOf((*MockIInspecaoSaidaSagaService)(nil).ReprocessarSaga), arg0)
}
