// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IInspecaoSaidaRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/dto"
	entities "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/entities"
	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIInspecaoSaidaRepository is a mock of IInspecaoSaidaRepository interface.
type MockIInspecaoSaidaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIInspecaoSaidaRepositoryMockRecorder
}

// MockIInspecaoSaidaRepositoryMockRecorder is the mock recorder for MockIInspecaoSaidaRepository.
type MockIInspecaoSaidaRepositoryMockRecorder struct {
	mock *MockIInspecaoSaidaRepository
}

// NewMockIInspecaoSaidaRepository creates a new mock instance.
func NewMockIInspecaoSaidaRepository(ctrl *gomock.Controller) *MockIInspecaoSaidaRepository {
	mock := &MockIInspecaoSaidaRepository{ctrl: ctrl}
	mock.recorder = &MockIInspecaoSaidaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIInspecaoSaidaRepository) EXPECT() *MockIInspecaoSaidaRepositoryMockRecorder {
	return m.recorder
}

// AtualizarQuantidadeInspecaoPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaRepository) AtualizarQuantidadeInspecaoPeloCodigo(arg0 int, arg1 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarQuantidadeInspecaoPeloCodigo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarQuantidadeInspecaoPeloCodigo indicates an expected call of AtualizarQuantidadeInspecaoPeloCodigo.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) AtualizarQuantidadeInspecaoPeloCodigo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarQuantidadeInspecaoPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).AtualizarQuantidadeInspecaoPeloCodigo), arg0, arg1)
}

// BuscarInformacoesPreenchimentoRNC mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarInformacoesPreenchimentoRNC(arg0 int) (*dto.RncDetailsOutputDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInformacoesPreenchimentoRNC", arg0)
	ret0, _ := ret[0].(*dto.RncDetailsOutputDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInformacoesPreenchimentoRNC indicates an expected call of BuscarInformacoesPreenchimentoRNC.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarInformacoesPreenchimentoRNC(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInformacoesPreenchimentoRNC", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarInformacoesPreenchimentoRNC), arg0)
}

// BuscarInspecaoSaidaDetalhesPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarInspecaoSaidaDetalhesPeloCodigo(arg0 int) (*models.InspecaoSaida, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaDetalhesPeloCodigo", arg0)
	ret0, _ := ret[0].(*models.InspecaoSaida)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoSaidaDetalhesPeloCodigo indicates an expected call of BuscarInspecaoSaidaDetalhesPeloCodigo.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarInspecaoSaidaDetalhesPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaDetalhesPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarInspecaoSaidaDetalhesPeloCodigo), arg0)
}

// BuscarInspecaoSaidaPeloCodigo mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarInspecaoSaidaPeloCodigo(arg0 int) (*entities.InspecaoSaida, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaPeloCodigo", arg0)
	ret0, _ := ret[0].(*entities.InspecaoSaida)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoSaidaPeloCodigo indicates an expected call of BuscarInspecaoSaidaPeloCodigo.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarInspecaoSaidaPeloCodigo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaPeloCodigo", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarInspecaoSaidaPeloCodigo), arg0)
}

// BuscarInspecaoSaidaPeloRecno mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarInspecaoSaidaPeloRecno(arg0 int) (*entities.InspecaoSaida, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecaoSaidaPeloRecno", arg0)
	ret0, _ := ret[0].(*entities.InspecaoSaida)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecaoSaidaPeloRecno indicates an expected call of BuscarInspecaoSaidaPeloRecno.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarInspecaoSaidaPeloRecno(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecaoSaidaPeloRecno", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarInspecaoSaidaPeloRecno), arg0)
}

// BuscarInspecoesSaida mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarInspecoesSaida(arg0 int, arg1 *models.BaseFilter, arg2 *dto.InspecaoSaidaFilters) ([]*models.InspecaoSaida, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInspecoesSaida", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.InspecaoSaida)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInspecoesSaida indicates an expected call of BuscarInspecoesSaida.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarInspecoesSaida(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInspecoesSaida", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarInspecoesSaida), arg0, arg1, arg2)
}

// BuscarNovoCodigoInspecao mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarNovoCodigoInspecao() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarNovoCodigoInspecao")
	ret0, _ := ret[0].(int)
	return ret0
}

// BuscarNovoCodigoInspecao indicates an expected call of BuscarNovoCodigoInspecao.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarNovoCodigoInspecao() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarNovoCodigoInspecao", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarNovoCodigoInspecao))
}

// BuscarQuantidadeInspecoesSaida mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarQuantidadeInspecoesSaida(arg0 int, arg1 *models.BaseFilter, arg2 *dto.InspecaoSaidaFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarQuantidadeInspecoesSaida", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarQuantidadeInspecoesSaida indicates an expected call of BuscarQuantidadeInspecoesSaida.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarQuantidadeInspecoesSaida(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarQuantidadeInspecoesSaida", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarQuantidadeInspecoesSaida), arg0, arg1, arg2)
}

// CriarInspecao mocks base method.
func (m *MockIInspecaoSaidaRepository) CriarInspecao(arg0 *models.InspecaoSaida) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CriarInspecao", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CriarInspecao indicates an expected call of CriarInspecao.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) CriarInspecao(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CriarInspecao", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).CriarInspecao), arg0)
}

// PreencherInformacoesMaquinaRetrabalho mocks base method.
func (m *MockIInspecaoSaidaRepository) PreencherInformacoesMaquinaRetrabalho(arg0 dto.RncInputDTO, arg1 *dto.InspecaoSaidaOrdemRetrabalhoBackgroundDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreencherInformacoesMaquinaRetrabalho", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreencherInformacoesMaquinaRetrabalho indicates an expected call of PreencherInformacoesMaquinaRetrabalho.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) PreencherInformacoesMaquinaRetrabalho(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreencherInformacoesMaquinaRetrabalho", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).PreencherInformacoesMaquinaRetrabalho), arg0, arg1)
}

// PreencherInformacoesMaterialRetrabalho mocks base method.
func (m *MockIInspecaoSaidaRepository) PreencherInformacoesMaterialRetrabalho(arg0 dto.RncInputDTO, arg1 *dto.InspecaoSaidaOrdemRetrabalhoBackgroundDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreencherInformacoesMaterialRetrabalho", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreencherInformacoesMaterialRetrabalho indicates an expected call of PreencherInformacoesMaterialRetrabalho.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) PreencherInformacoesMaterialRetrabalho(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreencherInformacoesMaterialRetrabalho", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).PreencherInformacoesMaterialRetrabalho), arg0, arg1)
}

// RemoverInspecaoSaida mocks base method.
func (m *MockIInspecaoSaidaRepository) RemoverInspecaoSaida(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverInspecaoSaida", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverInspecaoSaida indicates an expected call of RemoverInspecaoSaida.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) RemoverInspecaoSaida(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverInspecaoSaida", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).RemoverInspecaoSaida), arg0)
}

// BuscarNotasRelatorio mocks base method.
func (m *MockIInspecaoSaidaRepository) BuscarNotasRelatorio(arg0 string, arg1 string, arg2 *models.BaseFilter) (models.PagedResultDto[models.NotaFiscal], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarNotasRelatorio", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.PagedResultDto[models.NotaFiscal])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarNotasRelatorio indicates an expected call of BuscarNotasRelatorio.
func (mr *MockIInspecaoSaidaRepositoryMockRecorder) BuscarNotasRelatorio(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarNotasRelatorio", reflect.TypeOf((*MockIInspecaoSaidaRepository)(nil).BuscarNotasRelatorio), arg0, arg1, arg2)
}
