// Code generated by MockGen. DO NOT EDIT.
// Source: bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/interfaces (interfaces: IEstoquePedidoVendaRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "bitbucket.org/viasoftkorp/Korp.Qualidade.InspecaoSaida/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIEstoquePedidoVendaRepository is a mock of IEstoquePedidoVendaRepository interface.
type MockIEstoquePedidoVendaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIEstoquePedidoVendaRepositoryMockRecorder
}

// MockIEstoquePedidoVendaRepositoryMockRecorder is the mock recorder for MockIEstoquePedidoVendaRepository.
type MockIEstoquePedidoVendaRepositoryMockRecorder struct {
	mock *MockIEstoquePedidoVendaRepository
}

// NewMockIEstoquePedidoVendaRepository creates a new mock instance.
func NewMockIEstoquePedidoVendaRepository(ctrl *gomock.Controller) *MockIEstoquePedidoVendaRepository {
	mock := &MockIEstoquePedidoVendaRepository{ctrl: ctrl}
	mock.recorder = &MockIEstoquePedidoVendaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEstoquePedidoVendaRepository) EXPECT() *MockIEstoquePedidoVendaRepositoryMockRecorder {
	return m.recorder
}

// BuscarEstoqueLocalValoresPorProduto mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarEstoqueLocalValoresPorProduto(arg0, arg1 string, arg2, arg3 int) (*models.EstoqueLocalValores, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarEstoqueLocalValoresPorProduto", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.EstoqueLocalValores)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarEstoqueLocalValoresPorProduto indicates an expected call of BuscarEstoqueLocalValoresPorProduto.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarEstoqueLocalValoresPorProduto(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarEstoqueLocalValoresPorProduto", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarEstoqueLocalValoresPorProduto), arg0, arg1, arg2, arg3)
}

// BuscarPacotes mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarPacotes(arg0 int) ([]models.Pacote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarPacotes", arg0)
	ret0, _ := ret[0].([]models.Pacote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarPacotes indicates an expected call of BuscarPacotes.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarPacotes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarPacotes", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarPacotes), arg0)
}

// BuscarSeries mocks base method.
func (m *MockIEstoquePedidoVendaRepository) BuscarSeries(arg0 int) ([]models.Serie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarSeries", arg0)
	ret0, _ := ret[0].([]models.Serie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarSeries indicates an expected call of BuscarSeries.
func (mr *MockIEstoquePedidoVendaRepositoryMockRecorder) BuscarSeries(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarSeries", reflect.TypeOf((*MockIEstoquePedidoVendaRepository)(nil).BuscarSeries), arg0)
}
