import { QualidadeInspecaoEntradaI18N } from '../interfaces/qualidade-inspecao-entrada-i18n.interface';

export const QUALIDADE_INSPECAO_ENTRADA_I18N_PT: QualidadeInspecaoEntradaI18N = {
  QualidadeInspecaoEntrada: {
    Atencao: 'Atenção',
    Filtrar: 'Filtrar',
    Filtros: 'Filtros',
    Limpar: 'Limpar',
    Lote: 'Lote',
    NotaFiscal: 'Nota Fiscal',
    NumeroLote: 'Número Lote',
    Produto: 'Produto',
    Quantidade: 'Quantidade',
    QuebrarLote: 'Quebrar Lote',
    InspecaoEntradaGrid: {
      DataInspecao: 'Data Inspeção',
      Inspetor: 'Inspetor',
      Resultado: 'Resultado',
      QuantidadeInspecao: 'Qtd. Inspeção',
      QuantidadeLote: 'Qtd. Lote',
      QuantidadeAceita: 'Qtd. Aceita',
      QuantidadeAprovada: 'Qtd. Aprovada',
      QuantidadeReprovada: 'Qtd. Reprovada',
      EditarInspecao: 'Editar',
      ExcluirInspecao: 'Excluir',
      ImprimirInspecao: 'Imprimir',
    },
    InspecaoDetails: {
      NovaInspecao: 'Nova Inspeção',
      EditarInspecao: 'Editar Inspeção',
      Finalizar: 'Finalizar',
      CodProduto: 'Cód. Produto',
      QuantidadeLote: 'Qtd. Lote',
      QuantidadeInspecao: 'Qtd. Inspeção',
      QuantidadeInspecionada: 'Qtd. Inspecionada',
      QuantidadeInspecionar: 'Qtd. Inspecionar',
      QuantidadeInspecaoValidacao: 'Quantidade de inspeção/lote não pode ultrapassar a quantidade restante para inspecionar',
      Descricao: 'Descrição',
      Resultado: 'Resultado',
      MenorValor: 'Menor Valor',
      MaiorValor: 'Maior Valor',
      MenorValorBase: 'Menor Valor Base',
      MaiorValorBase: 'Maior Valor Base',
      Salvar: 'Salvar',
      SomaLoteInvalida: 'A quantidade quebrada em lotes não pode ser maior que a quantidade aprovada',
      Observacao: 'Observação',
      AlterarDadosInspecaoModal: {
        Titulo: 'Alterar dados',
        Aprovado: 'Aprovado',
        NaoAplicavel: 'Não aplicável',
        NaoConforme: 'Não conforme',
        ParcialmenteAprovado: 'Parcialmente Aprov.',
        Alterar: 'Alterar',
      },
      AlterarDadosFinalizacaoModal: {
        Titulo: 'Alterar dados',
        LocalPrincipal: 'Local Aprovados',
        LocalReprovado: 'Local Reprovados',
        NumeroPedido: 'Numero Pedido',
        Odf: 'ODF',
        QuantidadeAprovada: 'Qtd. Aprovada',
        QuantidadeRejeitada: 'Qtd. Reprovada',
        QuantidadePedido: 'Qtd. Pedido',
        QuantidadeEntrada: 'Qtd. Entrada',
        SaldoInspecionar: 'Saldo a Inspecionar',
        QuantidadeInspecao: 'Qtd. Inspeção'
      },
      FinalizarInspecaoModal: {
        Titulo: 'Finalizar Inspeção',
        DistribuirQuantidadesCheckbox: 'Distribuir quantidades para cada resultado',
        QuantidadeAprovada: 'Qtd. Aprovada',
        QuantidadeRejeitada: 'Qtd. Rejeitada',
        LocalPrincipal: 'Destino unidades aprovadas',
        LocalReprovado: 'Destino unidades reprovadas',
        NumODF: 'Número ODF',
        NumPedido: 'Número Pedido',
        Error: {
          AlocacaoQuantidadeRestante: 'Atenção! A distribuição das quantidades é superior à quantidade restante para distribuição.',
          AlocacaoQuantidadeSuperiorInspecao: 'Atenção! A distribuição das quantidades é superior à quantidade da inspeção.',
          AlocacaoQuantidadeInferiorInspecao: 'Atenção! A distribuição das quantidades é inferior à quantidade da inspeção.',
          AlocacaoQuantidadeEntrada: 'Atenção! A distribuição das quantidades é superior à quantidade de entrada.'
        },
        GridFinalizacao: {
          Pedido: 'Pedido',
          Odf: 'ODF',
          QuantidadeLote: 'Qtd. Lote',
          QuantidadePedido: 'Qtd. Pedido',
          QuantidadeEntrada: 'Qtd. Entrada',
          SaldoInspecionar: 'Saldo a Inspecionar',
          QuantidadeAprovada: 'Qtd. Aprovada',
          QuantidadeReprovada: 'Qtd. Reprovada',
          LocalAprovado: 'Local Aprovados',
          LocalReprovado: 'Local Reprovados',
          AlteraraDadosFinalizacaoGrid: 'Alterar dados finalização',
        }
      },
      Error: {
        AlocacaoSuperiorInspecao: "Atenção! A distribuição das quantidades é superior à quantidade da inspeção.",
        AlocacaoInferiorInspecao: "Atenção! A distribuição das quantidades é inferior à quantidade da inspeção.",
      }
    },
    Titulo: 'Inspeção de Entrada',
    Pesquisar: 'Pesquisar',
    NotaFiscalGrid: {
      CodigoProduto: 'Cód. Produto',
      DescricaoProduto: 'Desc. Produto',
      DescricaoForneced: 'Desc. Fornecedor',
      Lote: 'Lote',
      Situacao: 'Situação',
      Revisao: 'Revisão',
      Quantidade: 'Quantidade',
      QuantidadeInspecionada: 'Qtd. Inspecionada',
      QuantidadeInspecionar: 'Qtd. Inspecionar',
      DataEntrada: 'Data Entrada',
      Plano: 'Cód. Plano Insp.',
      DescricaoPlano: 'Desc. Plano Insp.',
      Observacao: 'Observação'
    },
    Resultados: {
      Aprovado: 'Aprovado',
      NaoAplicavel: 'Não aplicável',
      NaoConforme: 'Não conforme',
      ParcialmenteAprovado: 'Parcialmente Aprov.'
    }
  },
  HistoricoInspecao: {
    Metricas: 'Métricas',
    Plano: 'Cód. Plano Insp.',
    DescricaoPlano: 'Desc. Plano Insp.',
    DescricaoFornecedor: 'Desc. Fornecedor',
    Transferencias: 'Transferências',
    Filtrar: 'Filtrar',
    Filtros: 'Filtros',
    Limpar: 'Limpar',
    Status: 'Status',
    NumeroExecucoes: 'Número Execuções',
    NumeroRetentativas: 'Número Retentativas',
    Erro: 'Erro',
    Resultado: 'Resultado',
    Quantidade: 'Quantidade',
    QuantidadeTotal: 'Qtd. Total',
    Produto: 'Produto',
    NumeroPedido: 'Número Pedido',
    NotaFiscal: 'Nota Fiscal',
    Odf: 'ODF',
    LocalOrigem: 'Local Origem',
    LocalDestino: 'Local Destino',
    UsuarioExecucao: 'Usuário Execução',
    DataExecucao: 'Data Execução',
    CodigoProduto: 'Cód. Produto',
    DescricaoProduto: 'Desc. Produto',
    QuantidadeLote: 'Qtd. Lote',
    QuantidadeInspecao: 'Qtd. Inspecionada',
    DataInspecao: 'Data Inspeção',
    Inspetor: 'Inspetor',
    QuantidadeRetrabalhada: 'Qtd. Retrabalhada',
    QuantidadeAprovada: 'Qtd. Aprovada',
    QuantidadeReprovada: 'Qtd. Reprovada',
    Lote: 'Lote',
    Rnc: 'Relatório Não Conformidade',
    MovimentarInspecaoStatus: {
      Inicio: 'Início',
      EmProcesso: 'Em Processo',
      Falha: 'Falha',
      Sucesso: 'Sucesso'
    },
    Estornar: 'Estornar',
    Transferencia: {
      TipoTransferencia: 'Tipo Transferência',
      TipoTransferencias: {
        Aprovado: 'Aprovado',
        Reprovado: 'Reprovado',
        Retrabalhado: 'Retrabalhado',
      },
      Quantidade: 'Quantidade',
      DescricaoLocalOrigem: 'Local Origem',
      DescricaoLocalDestino: 'Local Destino',
      NumeroPedido: 'Número Pedido'
    },
    Resultados: {
      Aprovado: 'Aprovado',
      NaoAplicavel: 'Não aplicável',
      NaoConforme: 'Não conforme',
      ParcialmenteAprovado: 'Parcialmente Aprov.'
    }
  },
  FiltrosInspecao: {
    Filtrar: 'Filtrar',
    Metricas: 'Métricas',
    Observacao: 'Observação',
    Aplicar: 'Aplicar',
    Limpar: 'Limpar'
  }
};
