-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[InspecaoEntradaExecutadoWeb]'))
BEGIN
CREATE TABLE [dbo].[InspecaoEntradaExecutadoWeb](
	[id] [nvarchar](256) NOT NULL,
	[RECNO_INSPECAO_Entrada] [int] NULL,
	[CODIGO_PRODUTO] [nvarchar](450) NULL,
	[ID_INSPECAO_Entrada_SAGA] [nvarchar](450) NULL,
	[ESTORNO] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB]'))
BEGIN
CREATE TABLE [dbo].[QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB](
	[ID] [nvarchar](256) NOT NULL,
	[RECNO_INSPECAO_ENTRADA] [bigint] NULL,
	[RECNO_ESTOQUE_PEDIDO_VENDA] [bigint] NULL,
	[NUMERO_PEDIDO] [nvarchar](max) NULL,
	[QUANTIDADE_APROVAR] [decimal](19, 6) NULL,
	[QUANTIDADE_REPROVAR] [decimal](19, 6) NULL,
	[CODIGO_LOCAL_APROVAR] [bigint] NULL,
	[CODIGO_LOCAL_REPROVAR] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[InspecaoEntradaExecutadoWeb]') AND type in (N'U'))
BEGIN
DROP TABLE [dbo].[InspecaoEntradaExecutadoWeb]
END

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB]') AND type in (N'U'))
BEGIN
DROP TABLE [dbo].[QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB]
END
-- +goose StatementEnd