-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB_LOTE]'))
BEGIN
CREATE TABLE [dbo].[QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB_LOTE](
    [Id] UNIQUEIDENTIFIER UNIQUE NOT NULL DEFAULT NEWID(),
    [ID_INSPECAO_ENTRADA_PEDIDO_VENDA] [nvarchar](256) NOT NULL,
    [NUMERO_LOTE] [nvarchar](50) NOT NULL,
    [QUANTIDADE] [decimal](19, 6) NOT NULL
    CONSTRAINT [PK_QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB_LOTE] PRIMARY KEY ([Id])
)
    ALTER TABLE [QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB_LOTE] ADD CONSTRAINT [FK_QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB]
    FOREIGN KEY ([ID_INSPECAO_ENTRADA_PEDIDO_VENDA])
    REFERENCES [QA_INSPECAO_ENTRADA_PEDIDO_VENDA_WEB] ([id])
END
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- +goose StatementEnd
