-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QA_INSPECAO_ENTRADA' AND COLUMN_NAME = 'RECNO_HISTLISE')
BEGIN
ALTER TABLE QA_INSPECAO_ENTRADA ADD RECNO_HISTLISE INT

ALTER TABLE [QA_INSPECAO_ENTRADA] ADD CONSTRAINT [FK_HISTLISE]
FOREIGN KEY ([RECNO_HISTLISE])
REFERENCES [HISTLISE] ([R_E_C_N_O_])
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QA_INSPECAO_ENTRADA' AND COLUMN_NAME = 'CODIGO_PRODUTO')
BEGIN
ALTER TABLE QA_INSPECAO_ENTRADA ADD CODIGO_PRODUTO VARCHAR(50)

ALTER TABLE [QA_INSPECAO_ENTRADA] ADD CONSTRAINT [FK_ESTOQUE]
FOREIGN KEY ([CODIGO_PRODUTO])
REFERENCES [ESTOQUE] ([CODIGO])
END
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
