-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS]'))
BEGIN
CREATE TABLE [dbo].[QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS](
    [Id] UNIQUEIDENTIFIER UNIQUE NOT NULL DEFAULT NEWID(),
    [IdNotaFiscal] [nvarchar](256) NOT NULL,
    OBSERVACAO VARCHAR(MAX) NULL
    CONSTRAINT [PK_QA_INSPECAO_ENTRADA_NOTA_FISCAL_DADOS_ADICIONAIS] PRIMARY KEY ([Id])
    )
END
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
