-- +goose Up
-- +goose StatementBegin
IF (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QA_INSPECAO_ENTRADA' AND (COLUMN_NAME = 'RECNO_HISTLISE' OR COLUMN_NAME = 'CODIGO_PRODUTO')) = 2
BEGIN
UPDATE QA_INSPECAO_ENTRADA
SET RECNO_HISTLISE = (
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM HISTLISE
            JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
            JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
            LEFT JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
            WHERE QA_INSPECAO_ENTRADA.CODNOTA = HISTLISE.NFISCAL
            AND QA_INSPECAO_ENTRADA.LOTE = COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE)
            AND QA_INSPECAO_ENTRADA.QTD_LOTE = HISTLISE.QTPED
        )
        THEN (
            SELECT TOP (1)
            HISTLISE.R_E_C_N_O_
            FROM HISTLISE
            JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
            JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
            LEFT JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
            WHERE QA_INSPECAO_ENTRADA.CODNOTA = HISTLISE.NFISCAL
            AND QA_INSPECAO_ENTRADA.LOTE = COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE)
            AND QA_INSPECAO_ENTRADA.QTD_LOTE = HISTLISE.QTPED
        )
        ELSE (
            SELECT TOP (1)
            HISTLISE.R_E_C_N_O_
            FROM HISTLISE
            JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
            JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
            LEFT JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
            WHERE QA_INSPECAO_ENTRADA.CODNOTA = HISTLISE.NFISCAL
            AND QA_INSPECAO_ENTRADA.LOTE = COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE)
        )
    END
)
WHERE
QA_INSPECAO_ENTRADA.RECNO_HISTLISE IS NULL
AND QA_INSPECAO_ENTRADA.LOTE IS NOT NULL
AND QA_INSPECAO_ENTRADA.LOTE != ''

UPDATE QA_INSPECAO_ENTRADA
SET CODIGO_PRODUTO = (
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM HISTLISE
            JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
            JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
            LEFT JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
            WHERE QA_INSPECAO_ENTRADA.CODNOTA = HISTLISE.NFISCAL
            AND QA_INSPECAO_ENTRADA.LOTE = COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE)
            AND QA_INSPECAO_ENTRADA.QTD_LOTE = HISTLISE.QTPED
        )
        THEN (
            SELECT TOP (1)
            HISTLISE.ITEM
            FROM HISTLISE
            JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
            JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
            LEFT JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
            WHERE QA_INSPECAO_ENTRADA.CODNOTA = HISTLISE.NFISCAL
            AND QA_INSPECAO_ENTRADA.LOTE = COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE)
            AND QA_INSPECAO_ENTRADA.QTD_LOTE = HISTLISE.QTPED
        )
        ELSE (
            SELECT TOP (1)
            HISTLISE.ITEM
            FROM HISTLISE
            JOIN FORNECED ON FORNECED.CODIGO = HISTLISE.FORNECE
            JOIN ESTOQUE ON ESTOQUE.CODIGO = HISTLISE.ITEM AND ESTOQUE.PLAINS IS NOT NULL AND ESTOQUE.PLAINS <> ''
            LEFT JOIN HISTLISE_RATEIO_LOTE ON HISTLISE.R_E_C_N_O_ = HISTLISE_RATEIO_LOTE.RECNO_HISTLISE
            WHERE QA_INSPECAO_ENTRADA.CODNOTA = HISTLISE.NFISCAL
            AND QA_INSPECAO_ENTRADA.LOTE = COALESCE(HISTLISE_RATEIO_LOTE.LOTE, HISTLISE.LOTE)
        )
    END
)
WHERE
QA_INSPECAO_ENTRADA.CODIGO_PRODUTO IS NULL
AND QA_INSPECAO_ENTRADA.LOTE IS NOT NULL
AND QA_INSPECAO_ENTRADA.LOTE != ''
END
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
