-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QA_ITEM_INSPECAO_ENTRADA' AND COLUMN_NAME = 'RECNO_PLANO_INSPECAO')
BEGIN
ALTER TABLE QA_ITEM_INSPECAO_ENTRADA ADD RECNO_PLANO_INSPECAO INT

ALTER TABLE [QA_ITEM_INSPECAO_ENTRADA] ADD CONSTRAINT [FK_PLANOINS]
FOREIGN KEY ([RECNO_PLANO_INSPECAO])
REFERENCES [PLANOINS] ([R_E_C_N_O_])

EXEC('UPDATE QA_ITEM_INSPECAO_ENTRADA
SET RECNO_PLANO_INSPECAO = (
	SELECT R_E_C_N_O_ FROM PLANOINS
	WHERE QA_ITEM_INSPECAO_ENTRADA.PLANO = PLANOINS.PLANO
	AND QA_ITEM_INSPECAO_ENTRADA.SEQUENCIA = PLANOINS.SEQUENCIA
)
WHERE RECNO_PLANO_INSPECAO IS NULL')
END
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
