-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'QA_ITEM_INSPECAO_SAIDA' AND COLUMN_NAME = 'RECNO_PLANO_INSPECAO')
BEGIN
ALTER TABLE QA_ITEM_INSPECAO_SAIDA ADD RECNO_PLANO_INSPECAO INT

ALTER TABLE [QA_ITEM_INSPECAO_SAIDA] ADD CONSTRAINT [FK_QA_PLANO_INS_SAIDA]
FOREIGN KEY ([RECNO_PLANO_INSPECAO])
REFERENCES [QA_PLANO_INS_SAIDA] ([R_E_C_N_O_])

EXEC('UPDATE QA_ITEM_INSPECAO_SAIDA
SET RECNO_PLANO_INSPECAO = (
	SELECT R_E_C_N_O_ FROM QA_PLANO_INS_SAIDA
	WHERE QA_ITEM_INSPECAO_SAIDA.PLANO = QA_PLANO_INS_SAIDA.PLANO
	AND QA_ITEM_INSPECAO_SAIDA.SEQUENCIA = QA_PLANO_INS_SAIDA.SEQUENCIA
)
WHERE RECNO_PLANO_INSPECAO IS NULL')
END
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
