-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO')
BEGIN
CREATE TABLE QA_INSPECAO_SAIDA_MOVIMENTACAO_HISTORICO (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
    RECNO_HISREAL INT,
    RECNO_INSPECAO INT,
    ID_TRANSFERENCIA INT
    );
END;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
