-- +goose Up
-- +goose StatementBegin
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QA_INSPECAO_SAIDA_CONFIGURACAO')
BEGIN
CREATE TABLE QA_INSPECAO_SAIDA_CONFIGURACAO (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
    USAR_NOTA_IMPRESSAO_RELATORIO BIT
    );

INSERT INTO QA_INSPECAO_SAIDA_CONFIGURACAO (USAR_NOTA_IMPRESSAO_RELATORIO) VALUES (0);
END;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
