-- +goose Up
-- +goose StatementBegin
IF EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'QA_ITEM_INSPECAO_SAIDA' 
    AND COLUMN_NAME = 'PLANO'
)
AND EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'QA_ITEM_INSPECAO_SAIDA' 
    AND COLUMN_NAME = 'DESCRICAO'
)
BEGIN
    ALTER TABLE QA_ITEM_INSPECAO_SAIDA ALTER COLUMN PLANO VARCHAR(20)
    ALTER TABLE QA_ITEM_INSPECAO_SAIDA ALTER COLUMN DESCRICAO VARCHAR(150)
END

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
